### ISSUE TITLE
Error after following installation steps

### ISSUE THREAD

**Issue by fminkin** [mozilla/DeepSpeech#1030]
I followed through the installation steps for gpu deepspeech, it succeeded.
Although the command `bin/run-ldc93s1.sh` failed with message:
```+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/f-minkin/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/f-minkin/.local/share/deepspeech/ldc93s1
ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "DeepSpeech.py", line 482, in <module>
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/f-minkin/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/f-minkin/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory
```

I changed requirements.txt to 1.3.0 tensorflow, because it seemed to be right thing to do due to your ops is compiled for 1.3.0, but the command `bin/run-ldc93s1.sh` failed, so did the simple importing

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2017-11-27 21:14:01.386755: F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use AVX2 instructions, but these aren't available on your machine.
[1]    1030704 abort      python
```

**Comment by lissyx** [comment]
@fminkin Could you move this discussion to https://discourse.mozilla.org/c/deep-speech please ? Also, `deepspeech-gpu` packages are for **inference** not training. If you wish to train, please follow the (documented steps)[README.md#training]
