### ISSUE TITLE
UnicodeEncodeError on print()

### ISSUE THREAD

**Issue by nobuf** [mozilla/DeepSpeech#1137]
`print()` in python2.7 has [some glitches with unicode](https://pythonhosted.org/kitchen/unicode-frustrations.html#frustration-3-inconsistent-treatment-of-output), and when alphabet.txt contains any unicode character + redirect stdout to a file, it'd get the below error:

```shell
python -u DeepSpeech.py \
  ...
  > log/somewhere
```
```
Traceback (most recent call last):
  File "DeepSpeech.py", line 1633, in train
    job = COORD.next_job(job)
  File "DeepSpeech.py", line 1431, in next_job
    log_info('%s' % epoch)
  File "DeepSpeech.py", line 341, in log_info
    prefix_print('I ', message)
  File "DeepSpeech.py", line 329, in prefix_print
    print(prefix + ('\n' + prefix).join(message.split('\n')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 295: ordinal not in range(128)
```

```shell
python -V
Python 2.7.14
```

```shell
git rev-parse HEAD
a2df4fbedc4bee83a6c4cf7147f5c91204f0007a
```

To reproduce:
- run `./bin/run-ldc93s1.sh`
- add `é` to `data/alphabet.txt`
- modify `data/ldc93s1/ldc93s1.csv` with `é` at the end of the sentence
- then run `./bin/run-ldc93s1.sh >/tmp/output.log`

Note that it won't raise any error without redirection.

Having `export PYTHONIOENCODING=utf-8` is a workaround, though I think using built-in `logging` would be nicer instead of the current `prefix_print()`/`print()`.

ref. https://discourse.mozilla.org/t/alternative-to-print/23736

**Comment by lissyx** [comment]
Interesting, because we have people using UTF-8 without any issue so far, including french alphabet, (so `é` should be there), like @elpimous for instance. But some other reported issued, that might be because of the with / without redirection different behavior. I tend to remember that @tilmankamp PR #890 does a lot of refactoring around logging, and thus it might fix it at the same time?

**Comment by nirabhratapaswi** [comment]
@lissyx , I am very new to opensource ,but this issue seems to be easy. Can I try fixing it?

**Comment by lissyx** [comment]
Of course you are welcome to send a PR. Just make sure it's not already being taken care of in PR #890 so you avoid merge / rebase conflicts :)
