### ISSUE TITLE
about the NotFoundError: native_client/libctc_decoder_with_kenlm.so: invalid ELF header

### ISSUE THREAD

**Issue by crazygirl1992** [mozilla/DeepSpeech#1148]
i have the native_client file,i don't know how to deal with this,thank you!
the information of error as following:
Traceback (most recent call last):
  File "DeepSpeech.py", line 482, in <module>
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: invalid ELF header

**Comment by lissyx** [comment]
@crazygirl1992 As documented in the `--help` output of `DeepSpeech.py`, please place `libctc_decoder_with_kenlm.so` in `native_client/` directory, or give its path using the argument `--decoder_library_path`. Next time, if you need help, please use discourse unless you have a documented bug, Github issues are only to track work.
