### ISSUE TITLE
Deepspeech bindings for python 3

### ISSUE THREAD

**Issue by ajaygchavda** [mozilla/DeepSpeech#1163]
If you've found a bug, or have a feature request, then please create an issue with the following information:

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
-     TensorFlow installed from (our builds, or upstream TensorFlow): mozilla fork of tensorflow as metioned in read.me
-     TensorFlow version: 1.4.0
-     Python version: 3.5.0
-     Bazel version (if compiling from source): bazel release 0.9.0
-     GCC/Compiler version (if compiling from source): 5.4.0
-     Exact command to reproduce:

After building deepspeech, created binding for it for python3. While using I got following error:

```
Unhandled exception in thread started by <function check_errors..wrapper at 0x7f4c1467dd90>
Traceback (most recent call last):
File "/home/ajayc/.local/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
fn(*args, **kwargs)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
self.check(display_num_errors=True)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
include_deployment_checks=include_deployment_checks,
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
return checks.run_checks(**kwargs)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
new_errors = check(app_configs=app_configs)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
return check_resolver(resolver)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
return check_method()
File "/home/ajayc/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 397, in check
for pattern in self.url_patterns:
File "/home/ajayc/.local/lib/python3.5/site-packages/django/utils/functional.py", line 36, in get
res = instance.dict[self.name] = self.func(instance)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/utils/functional.py", line 36, in get
res = instance.dict[self.name] = self.func(instance)
File "/home/ajayc/.local/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
return import_module(self.urlconf_name)
File "/usr/lib/python3.5/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 986, in _gcd_import
File "", line 969, in _find_and_load
File "", line 958, in _find_and_load_unlocked
File "", line 673, in _load_unlocked
File "", line 665, in exec_module
File "", line 222, in _call_with_frames_removed
File "/home/ajayc/workspace/trunk/deepspeech/django-deepspeech-server/SpeechServer/urls.py", line 22, in
url('dsserver/', include('speech_server_main.urls')),
File "/home/ajayc/.local/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
urlconf_module = import_module(urlconf_module)
File "/usr/lib/python3.5/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 986, in _gcd_import
File "", line 969, in _find_and_load
File "", line 958, in _find_and_load_unlocked
File "", line 673, in _load_unlocked
File "", line 665, in exec_module
File "", line 222, in _call_with_frames_removed
File "/home/ajayc/workspace/trunk/deepspeech/django-deepspeech-server/speech_server_main/urls.py", line 7, in
from . import views
File "/home/ajayc/workspace/trunk/deepspeech/django-deepspeech-server/speech_server_main/views.py", line 5, in
from .deepspeech import deepspeech as ds
File "/home/ajayc/workspace/trunk/deepspeech/django-deepspeech-server/speech_server_main/deepspeech/deepspeech.py", line 3, in
from deepspeech.model import Model
File "/home/ajayc/.local/lib/python3.5/site-packages/deepspeech/model.py", line 28, in
_model = swig_import_helper()
File "/home/ajayc/.local/lib/python3.5/site-packages/deepspeech/model.py", line 24, in swig_import_helper
_mod = imp.load_module('_model', fp, pathname, description)
File "/usr/lib/python3.5/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: /home/ajayc/.local/lib/python3.5/site-packages/deepspeech/_model.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10DeepSpeech5ModelD1Ev
```

Is there some proper way for making bindings for python3, that I may be missing? Bindings for python2 works properly.

**Comment by lissyx** [comment]
@ajaygchavda Is there any reason you rebuild yourself? We already provide Python 3.5 bindings. Debugging loading failure from Django is going to be painful, except if you can trigger that from CLI. Then passing `LD_DEBUG=libs` might help finding why it fails to find the symbol (it should be provided by `libdeepspeech.so`).

**Comment by ajaygchavda** [comment]
@lissyx  reason behind rebuilding is my cpu is intel i7 3rd generation which doesn't support AVX2/FMA instructions set
I have tried with CLI as well but it was same issue there as well. 
Let me try LD_DEBUG=libs and will share my results.

**Comment by lissyx** [comment]
@ajaygchavda Our pypi registry packages are not yet updated, but https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.cpu/artifacts/public/deepspeech-0.1.0-cp35-cp35m-manylinux1_x86_64.whl should work on your CPU.

**Comment by ajaygchavda** [comment]
@lissyx Thanks a lot! it works for me you made my day :)

**Comment by lissyx** [comment]
Thank!
