### ISSUE TITLE
ImportError: No module named '_model'

### ISSUE THREAD

**Issue by danielsjf** [mozilla/DeepSpeech#1182]
I'm on Windows and I'm following the WSL tutorial here:
https://fotidim.com/deepspeech-on-windows-wsl-287cb27557d4 

Yesterday everything worked fine. Today I tried to get deepspeech-server up and running and now the original command is failing with the error in the title. It might be because I had to install some Python 3 packages. However I'm not certain how to fix the error. I also tried the approach in #1094 but that didn't solve my problem.

`´´´
$ deepspeech ../models/output_graph.pb ../audio/2830-3980-0043. wav ../models/alphabet.txt ../models/lm.binary ../models/trie
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/model.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: libcusolver.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_model'
´´´`

**Comment by kdavis-mozilla** [comment]
This is better dealt with in the [Discourse Forum](https://discourse.mozilla.org/c/deep-speech) or through [deepspeech-server](https://github.com/MainRo/deepspeech-server), a third-party project, support as this is not a bug or enhancement for Deep Speech as Deep Speech, up until deepspeech-server installation worked.
