### ISSUE TITLE
issue with undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by eweiss97** [mozilla/DeepSpeech#1186]
I get the following when I try ./DeepSpeech.py --help

Would appreciate any help on this. Installed a fresh version today

```
Traceback (most recent call last):
  File "./DeepSpeech.py", line 21, in <module>
    from tensorflow.contrib.session_bundle import exporter
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/__init__.py", line 28, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 33, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnCompatibleGRUCell
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 21, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/rnn/__init__.py", line 83, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/tmp/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

```

**Comment by lissyx** [comment]
@eweiss97 Please document exactly your installation steps ?

**Comment by lissyx** [comment]
I'm pretty sure you installed TensorFlow from https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl and not upstream TensorFlow. We are in the process of merging some changes and stopping to produce those wheel, because there is no good reason anymore and it brings confusion. Docs have not been updated yet but I already merged an incompatible change last friday.

**Comment by lissyx** [comment]
Just filed https://github.com/mozilla/DeepSpeech/issues/1187 to fix that.

**Comment by benitoski** [comment]
@lissyx 
I just receive the same error when try to train and after installing tensorflow 1.4
I used pip install tensorflow==1.4 and I'm not sure if it was pulled from the link you mentioned above.
Do I need to reinstall tensorflow?
Below is the error

(deepspeech-venv) oscar@ubuntuDS:~/DeepSpeech$ ./bin/run-oscar.sh
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py --train_files /home/oscar/Documentos/SpeechToText/Corpus/train.csv --dev_files /home/oscar/Documentos/SpeechToText/Corpus/dev.csv --test_files /home/oscar/Documentos/SpeechToText/Corpus/test.csv --train_batch_size 80 --dev_batch_size 80 --test_batch_size 40 --n_hidden 375 --epoch 33 --validation_step 1 --early_stop True --earlystop_nsteps 6 --estop_mean_thresh 0.1 --estop_std_thresh 0.1 --dropout_rate 0.22 --learning_rate 0.00095 --report_count 100 --use_seq_length False --export_dir /home/oscar/Documentos/SpeechToText/Resultados/model_export/ --checkpoint_dir /home/oscar/Documentos/SpeechToText/Resultados/checkout/ --decoder_library_path /home/oscar/Documentos/SpeechToText/libctc_decoder_with_kenlm.so --alphabet_config_path /home/oscar/Documentos/SpeechToText/alphabet_pt.txt --lm_binary_path /home/oscar/Documentos/SpeechToText/lm.binary --lm_trie_path /home/oscar/Documentos/SpeechToText/trie
Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/home/oscar/Documentos/SpeechToText/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/oscar/Documentos/SpeechToText/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/oscar/Documentos/SpeechToText/deepspeech-venv/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/oscar/Documentos/SpeechToText/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow20OpKernelConstruction21CtxFailureWithWarningEPKciRKNS_6StatusE

**Comment by lissyx** [comment]
@benitoski You are using a libctc decoder library that is not matching your tensorflow version.

**Comment by benitoski** [comment]
@lissyx 
Thanks for your response. I used util/taskcluster.py as [suggested](https://github.com/mozilla/DeepSpeech) to download the native client and this is the origin of the libctc_decoder_with_kenlm.so I have...
Do I need to download another native client? or use the --artifact parameter to download another version?

**Comment by lissyx** [comment]
@benitoski Actually this piece of code is more tailored by default for downloading latest master builds, but you can override that with `TASKCLUSTER_SCHEME=https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.v0.1.1.% python util/taskcluster.py [...]`
