### ISSUE TITLE
problem downloading deepspeech

### ISSUE THREAD

**Issue by Macha-Pujitha** [mozilla/DeepSpeech#1258]
**deepspeech -h gives the following error**
raceback (most recent call last):
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/site-packages/deepspeech/model.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/tmp/deepspeech-venv2/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/site-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/site-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/home/ubuntu/tmp/deepspeech-venv2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_model'

**Comment by lissyx** [comment]
It seems like you are using the `deepspeech-gpu` Python package. You need to have CUDA 8.0 and CuDNN v6 installed. This error shows it is not the case.

**Comment by lissyx** [comment]
Next time, please open thread on Discourse of you are reaching for help, instead of opening an issue.
