### ISSUE TITLE
Error: Alphabet size does not match loaded model

### ISSUE THREAD

**Issue by jj64966680** [mozilla/DeepSpeech#1274]
Hi,

When running 

deepspeech models/output_graph.pbmm models/alphabet.txt models/lm.binary

I'm getting:

Error: Alphabet size does not match loaded model: alphabet has size 3349619, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.

and 

ValueError: File format '# Ea'... not understood.

I'm using macOS, I think the problem is alphabet.txt cannot be parsed properly since '# Ea'... is the first line of alphabet.txt, but I failed to find a way out...

```
Full Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 11, in <module>
      sys.exit(main())
  File "/Library/Python/2.7/site-packages/deepspeech/client.py", line 66, in main
      fs, audio = wav.read(args.audio)
  File "/Library/Python/2.7/site-packages/scipy/io/wavfile.py", line 236, in read
      file_size, is_big_endian = _read_riff_chunk(fid)
  File "/Library/Python/2.7/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
      "understood.".format(repr(str1)))
ValueError: File format '# Ea'... not understood.
```

Anyone could help?...

**Comment by jj64966680** [comment]
Full Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/deepspeech/client.py", line 66, in main
    fs, audio = wav.read(args.audio)
  File "/Library/Python/2.7/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/Library/Python/2.7/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format '# Ea'... not understood.

**Comment by lissyx** [comment]
@jj64966680 How did you installed deepspeech ?

**Comment by lissyx** [comment]
@jj64966680 Ok, you are passing the wrong arguments. Please run `deepspeech` with no argument to get propre usage info. The stack shows you are passing the alphabet file to what expects a WAV file.
