### ISSUE TITLE
No libctc_decoder_with_kenlm.so

### ISSUE THREAD

**Issue by MekliCZ** [mozilla/DeepSpeech#1306]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: mozilla/tensorflow
- **TensorFlow version (use command below)**: ('v1.6.0-0-gd2e24b6039', '1.6.0')
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 6.3.0
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: bazel build -c opt --copt=-O3 //native_client:libctc_decoder_with_kenlm.so

Hello, I'm trying to build my own DeepSpeech native_client. I'm following the guide from this repo step by step but everytime I try to run deepspeech (after building everything and running `make deepspeech`), I get this error:
```
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory
```

There is no `libctc_decoder_with_kenlm.so` even if I built it. Why?

**Comment by lissyx** [comment]
@MekliCZ Any reason you need to rebuild this yourself ? Can you share the output of your build command? It should tell you that it failed.

**Comment by lissyx** [comment]
@MekliCZ Is it possible that you are just calling `DeepSpeech.py` without giving any `--decoder_library_path` ? If so, try with `--decoder_library_path ${TFDIR}/bazel-bin/native_client/libctc_decoder_with_kenlm.so` with TFDIR the path to your TensorFlow directory ?

**Comment by MekliCZ** [comment]
@lissyx Better, but still:
```
tensorflow.python.framework.errors_impl.NotFoundError: /root/voice/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
```

**Comment by lissyx** [comment]
@MekliCZ Mismatching String ABI between your tensorflow and the binary your built. Likely you need to add `--copt=-D_GLIBCXX_USE_CXX11_ABI=0`

**Comment by ducbm95** [comment]
Currently, I am facing with a problem that similar to @MekliCZ. I use this './bin/run-ldc93s1.sh' to build an example, but it throw an error 'tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory'.
When I add '--decoder_library_path ${TFDIR}/bazel-bin/native_client/libctc_decoder_with_kenlm.so', it throw a different error 'tensorflow.python.framework.errors_impl.NotFoundError: /home/monster/Desktop/workspace/tensorflow/bazel-bin/native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
'.
Can you help me to fix that problem :(

**Comment by lissyx** [comment]
@ducbm95 well you need to read my latest answer. Is there any legit reason for you to rebuild that from scratch instead of using pre-built binaries?

**Comment by DewiBrynJones** [comment]
I'm getting the same problem within a Docker container built from the 'official' Dockerfile:

https://github.com/mozilla/DeepSpeech/blob/master/Dockerfile

(although I had to update the TF_CUDNN_VERSION env variable from 7.1.1 to 7.1.4)

```
root@02f8c6a1a062:/DeepSpeech# ./bin/run-librivox.sh 
+ [ ! -f DeepSpeech.py ]
+ [ ! -d  ]
+ COMPUTE_DATA_DIR=data
+ [ ! -f data/librivox-train-clean-100.csv ]
+ echo Warning: It looks like you don't have the LibriSpeech corpus downloaded and preprocessed. Make sure $COMPUTE_DATA_DIR points to the folder where the LibriSpeech data is located, and that you ran the importer script at bin/import_librivox.py before running this script.
Warning: It looks like you don't have the LibriSpeech corpus downloaded and preprocessed. Make sure $COMPUTE_DATA_DIR points to the folder where the LibriSpeech data is located, and that you ran the importer script at bin/import_librivox.py before running this script.
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/librivox"))
+ checkpoint_dir=/root/.local/share/deepspeech/librivox
+ python -u DeepSpeech.py --train_files data/librivox-train-clean-100.csv,data/librivox-train-clean-360.csv,data/librivox-train-other-500.csv --dev_files data/librivox-dev-clean.csv,data/librivox-dev-other.csv --test_files data/librivox-test-clean.csv,data/librivox-test-other.csv --train_batch_size 12 --dev_batch_size 12 --test_batch_size 12 --learning_rate 0.0001 --epoch 15 --display_step 5 --validation_step 5 --dropout_rate 0.30 --default_stddev 0.046875 --checkpoint_dir /root/.local/share/deepspeech/librivox
Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```

**Comment by lissyx** [comment]
The contributor who sent the dockerfile did sent a PR a few days ago to fix something related, adding copt for String ABI. Make sure you test with that and there's no caching fun with docker?

**Comment by DewiBrynJones** [comment]
Thanks! Confirmed! Did a pull, rebuilt the image and voila :

```
root@c4d73751e58f:/DeepSpeech# ./bin/run-librivox.sh 
+ [ ! -f DeepSpeech.py ]
+ [ ! -d  ]
+ COMPUTE_DATA_DIR=data
+ [ ! -f data/librivox-train-clean-100.csv ]
+ echo Warning: It looks like you don't have the LibriSpeech corpus downloaded and preprocessed. Make sure $COMPUTE_DATA_DIR points to the folder where the LibriSpeech data is located, and that you ran the importer script at bin/import_librivox.py before running this script.
Warning: It looks like you don't have the LibriSpeech corpus downloaded and preprocessed. Make sure $COMPUTE_DATA_DIR points to the folder where the LibriSpeech data is located, and that you ran the importer script at bin/import_librivox.py before running this script.
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/librivox"))
+ checkpoint_dir=/root/.local/share/deepspeech/librivox
+ python -u DeepSpeech.py --train_files data/librivox-train-clean-100.csv,data/librivox-train-clean-360.csv,data/librivox-train-other-500.csv --dev_files data/librivox-dev-clean.csv,data/librivox-dev-other.csv --test_files data/librivox-test-clean.csv,data/librivox-test-other.csv --train_batch_size 12 --dev_batch_size 12 --test_batch_size 12 --learning_rate 0.0001 --epoch 15 --display_step 5 --validation_step 5 --dropout_rate 0.30 --default_stddev 0.046875 --checkpoint_dir /root/.local/share/deepspeech/librivox
Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1795, in main
    train()
  File "DeepSpeech.py", line 1468, in train
    next_index=lambda i: COORD.get_next_index('train'))
  File "/DeepSpeech/util/feeding.py", line 90, in __init__
    file = pandas.read_csv(csv, encoding='utf-8', na_filter=False)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File data/librivox-train-clean-100.csv does not exist
```
Error gone and I'm able to move on to `import-librivox.sh` :) Hope the Dockerfile can be of help to @MekliCZ's setup. Thanks @GeorgeFedoseev !

**Comment by lissyx** [comment]
Thanks for the  feedback, then I'm guessing we should close this :-).
