### ISSUE TITLE
running ldc93s1.sh training example gets and error on xdg.py

### ISSUE THREAD

**Issue by benitoski** [mozilla/DeepSpeech#1326]
I'm running the training ldc93s1example and get an error on xdg.py:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: None
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04 on windows10 VirtualBox
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: python, with 
 `pip install --upgrade tensorflow`
- **TensorFlow version (use command below)**:1.7.0
- **Python version**: 2.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**: only CPU
- **Exact command to reproduce**: run-ldc93s1.sh

The complete error:

```
(deepspeech-venv) oscar@ubuntuDS:~/DeepSpeech$ ./bin/run-ldc93s1.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oscar/Documentos/OI_SpeechToText/deepspeech-venv/local/lib/python2.7/site-packages/xdg.py", line 41
    def _getenv(variable: str, default: str) -> str:
                        ^
SyntaxError: invalid syntax
+ checkpoint_dir=
(deepspeech-venv) oscar@ubuntuDS:~/DeepSpeech$ 

```

**Comment by lissyx** [comment]
@benitoski Have you used `pip install --upgrade -r requirements.txt` ? The `pyxdg` wheel should not install any `xdg.py` file, that would be from the `xdg` module. So please remove `xdg` and install `pyxdg`.

**Comment by benitoski** [comment]
@lissyx No, I used `pip install -r requirements.txt`. I will remove xdg.py and re-install the requirements according to your suggestion. Let see what happens. Thank you

**Comment by benitoski** [comment]
@lissyx I deleted xpg.py and run the install with upgrade. No pyxdg was generated. Is that ok?

**Comment by lissyx** [comment]
@benitoski Please `pip uninstall xdg; pip install --upgrade pyxdg`. The `xdg` is NOT the module we want to use.
