### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 55 and 29. Shapes are [55] and [29]. for 'Assign_12' (op: 'Assign') with input shapes: [55], [29].

### ISSUE THREAD

**Issue by arunimathappa** [mozilla/DeepSpeech#1330]
- i am trying to train with my own audios and have made a csv file according to it 
i am running the following command to train it
  **python DeepSpeech.py --n_hidden 2048 --initialize_from_frozen_model ../output_graph.pb --checkpoint_dir ../mymodel/check --export_dir ../mymodel/export --epoch 25 --train_files ../mymodel/train/train.csv --dev_files ../mymodel/dev/dev.csv --test_files ../mymodel/test/test.csv --learning_rate 0.001--train_batch_size 16 --dev_batch_size 16 --test_batch_size 16 --display_step 1 --validation_step 1**
-  **Distribution (e.g., Linux RHEL7):**
- **TensorFlow version- v1.6.0-0-gd2e24b6039 1.6.0**:
- **Python version- 3.6**: 

this is the following error i get -
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 55 and 29. Shapes are [55] and [29]. for 'Assign_12' (op: 'Assign') with input shapes: [55], [29].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1795, in main
    train()
  File "DeepSpeech.py", line 1570, in train
    assign_ops.append(tf.assign(training_tensor, restored_tensor))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 280, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 58, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3273, in create_op
    compute_device=compute_device)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3313, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2501, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2474, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2404, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 55 and 29. Shapes are [55] and [29]. for 'Assign_12' (op: 'Assign') with input shapes: [55], [29].

**can anyone tell me what is it that i am doing wrong.**

**Comment by kdavis-mozilla** [comment]
@arunimathappa As you are using your own importer and this, initially at least, appears not to be a bug or feature request for the current code base, could you move this request to discourse[[1](https://discourse.mozilla.org/c/deep-speech)]? Thanks.

**Comment by reuben** [comment]
From the error it looks like you're trying to re-use our pretrained weights with a model that has a different alphabet, which is not going to work. What you can try instead is an approach similar to the one described here: https://www.tensorflow.org/tutorials/image_retraining

Sadly the tooling described in the article won't work on DeepSpeech, you'll need to change the code to only load the weights up to the last hidden layer, and then re-train the final layer with your new alphabet. Hopefully that helps. I'm gonna close this issue since it's more of an open ended discussion anyway, but feel free to reopen the discussion on [Discourse](https://discourse.mozilla.org/c/deep-speech).
