### ISSUE TITLE
`/bazel-bin/native_client` not found

### ISSUE THREAD

**Issue by m09** [mozilla/DeepSpeech#1348]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: no
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: from 'pip install tensorflow-gpu==1.6.0`
- **TensorFlow version (use command below)**: v1.6.0-0-gd2e24b6039 1.6.0
- **Python version**: 3.5.2
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0 7.1.3
- **GPU model and memory**: GTX1080 8Go
- **Exact command to reproduce**: `./DeepSpeech.py --train_files ../data/cv/cv-valid-train.csv,../data/cv/cv-other-train.csv --dev_files ../data/cv/cv-valid-dev.csv --test_files ../data/cv/cv-valid-test.csv --decoder_library_path ${TFDIR}/bazel-bin/native_client`
- **Extra info**: I've also installed the native client with `--arch gpu` specified.
- **Error**: `ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "./DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "./DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /bazel-bin/native_client: cannot open shared object file: No such file or directory`

If I don't specify the `--decoder_library_path` option, I get the following error: `ERROR: The decoder library file does not exist. Make sure you have downloaded or built the native client binaries and pass the appropriate path to the binaries in the --decoder_library_path parameter.
Traceback (most recent call last):
  File "./DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "./DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/mog/.virtualenvs/deep-speech/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: cannot open shared object file: No such file or directory`

**Comment by m09** [comment]
Obviously just when I post the issue I find that by giving the `--decoder_library_path` the path to the decoder directly (`./libctc_decoder_with_kenlm.so` in my case) it works.
