### ISSUE TITLE
version `GLIBC_2.14' not found 

### ISSUE THREAD

**Issue by coco90417** [mozilla/DeepSpeech#1370]
Dear developer,

I installed your deepspeech on my linux cluster and it turns out that I cannot run your model due to incompatibility of the GLIBC library (see below), please let me know how to resolve this (I do not have root access to the HPC)

###########################################

[guest245@cluster ~]$ deepspeech models/output_graph.pb models/alphabet.txt my_audio_file.wav

Traceback (most recent call last):
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/site-packages/deepspeech/model.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/guest245/usr/python-3.6.2/lib/python3.6/site-packages/deepspeech/_model.cpython-36m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guest245/usr/python-3.6.2/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/site-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/site-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/home/guest245/usr/python-3.6.2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_model'

**Comment by lissyx** [comment]
@coco90417 Which system are you running on?

**Comment by lissyx** [comment]
BTW, if you have an older glibc, you'll basically have to rebuild for your system.

**Comment by lissyx** [comment]
@coco90417 It might also be possible to trick it by building and installing locally in your home a glibc 2.14

**Comment by coco90417** [comment]
Thank you for your quick response! Please see the output below, do you know how to install locally in my home a glibc2.14 and configure it to be compatible with your deepspeech?

[guest245@cluster ~]$ uname -a
Linux cluster.hpc.org 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[guest245@cluster ~]$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6
Codename:	Final

**Comment by lissyx** [comment]
@coco90417 Maybe you can get a glibc2.14 package from a newer CentOS and extract it in your home directory, like `~/lib/`, then use `LD_LIBRARY_PATH`. But safer would be to rebuild for CentOS 6.6

**Comment by coco90417** [comment]
Thanks for your quick response, do you mean copy paste the glibc binary file from system library and set ~/.bash_rc path to include it?

**Comment by lissyx** [comment]
@coco90417 That might be something like that yes. I know RPM has an option to set installation prefix, so if you use that you should be able to have the matching glibc version in your home. Now, please note it is really hacky, you might hit some unexpected issues ..., it would be better you just rebuild against CentOS 6 with its older glibc.

**Comment by lissyx** [comment]
I'm going to close this, because it's not really a bug per-se. Feel free to take the discussion to Discourse.
