### ISSUE TITLE
Datatype error when converting wave file

### ISSUE THREAD

**Issue by jageshmaharjan** [mozilla/DeepSpeech#1380]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:  1.7.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:  0.12.0
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: CUDA 9.0 and cuDNN 7.0
- **GPU model and memory**: Tesla M60 (4x)
- **Exact command to reproduce**: 
`python DeepSpeech.py --train_files /data/zh_data/data_thchs30/mini_train.csv --dev_files /data/zh_data/data_thchs30/mini_dev.csv --test_files /data/zh_data/data_thchs30/mini_test.csv --alphabet_config_path /data/zh_data/alphabet.txt --lm_binary_path /data/zh_data/zh_lm.binary --lm_trie_path /data/zh_data/trie --decoder_library_path native_client/libctc_decoder_with_kenlm.so --checkpoint_dir /data/zh_data/checkpoint/ --validation_step 1`

I am not sure if the problem is with the downloaded Chinese audio (wave) files from "openslr.org/15".
I was trying to train on the Chinese language dataset, but i am getting this error message, 

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/maybe/anaconda3/envs/asr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/maybe/anaconda3/envs/asr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/jugs/asr/DeepSpeech/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/data/jugs/asr/DeepSpeech/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/maybe/anaconda3/envs/asr/lib/python3.6/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: integer argument expected, got float
```
Though, it was a wave file not in correct format, I checked the properties using sox library, everything seems fine,

```
Input File     : 'data_thchs30/dev/C8_747.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Duration       : 00:00:09.94 = 159000 samples ~ 745.312 CDDA sectors
File Size      : 318k
Bit Rate       : 256k
Sample Encoding: 16-bit Signed Integer PCM
```
Since, there were thousands of wave files, So wrote a small python script to check if numpy array of the wave file is really not integer,

```
import numpy as np
import python_speech_features as mfcc
from python_speech_features import mfcc
from six.moves import range
import scipy.io.wavfile as wav
import sys
import os
path = '/data/zh_data/data_thchs30/'
dir = os.fsencode(path +'test/')
for f in os.listdir(dir):
	fname = os.fsdecode(f)
	fs, audio = wav.read(path+'test/'+fname)
	if (audio.dtype != 'int16'):
		print(str(fs) + ' ' +str(audio.dtype) + ' ' + str(audio)) 
```
All result on train, test and dev data shows its integer type. 
However, with the Mozilla DeepSpeech training script, I am still getting that mismatched datatype error.

**Comment by jageshmaharjan** [comment]
Yea, the issue had been solved. 
Thanks.
