### ISSUE TITLE
ImportError: libcublas.so.8.0 with v0.1.1

### ISSUE THREAD

**Issue by xu-song** [mozilla/DeepSpeech#1388]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution**:  Ubuntu 16.04
- **TensorFlow installed from**: upstream TensorFlow
- **TensorFlow version**: 1.8.0
- **Python version**:  3.6.4 :: Anaconda,
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version**: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
- **CUDA/cuDNN version**: cuda-9.0
- **GPU model and memory**:
- **Exact command to reproduce**:

```
# pip3 install deepspeech-gpu
# deepspeech -h
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/deepspeech/model.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/root/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/root/anaconda3/lib/python3.6/site-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/root/anaconda3/lib/python3.6/site-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/root/anaconda3/lib/python3.6/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/root/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_model'

```

# info

I am using **cuda9.0**

deepspeech-gpu-0.1.1

**Comment by xu-song** [comment]
```
pip3 install deepspeech-gpu==0.2.0a5 
```
It works, thanks

**Comment by beeteax** [comment]
Thankyou So much for not providing an Updated Readme file.
Wasted my 15 days on this

**Comment by lissyx** [comment]
@beeteax Can you be more specific ?
