### ISSUE TITLE
TypeError : "sess" must be a session

### ISSUE THREAD

**Issue by rishit13** [mozilla/DeepSpeech#1409]
After waiting for hours of training no progress is shown and then i get this error
```
Traceback (most recent call last):
 File "./DeepSpeech.py", line 1838, in <module>
   tf.app.run()
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
   _sys.exit(main(argv))
 File "./DeepSpeech.py", line 1795, in main
   train()
 File "./DeepSpeech.py", line 1666, in train
   hook.end(session)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 469, in end
   self._save(session, last_step)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 480, in _save
   self._get_saver().save(session, self._save_path, global_step=step)
 File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1691, in save
   raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7fb826ebbda0>   
```

I am working a the p2.8xlarge instance . So please could u help out in this .

**Comment by lissyx** [comment]
Those EC2 instances are using too slow GPUs, so it's nor surprising being slow. The stack does not provide anything actionable. Can you give more details? And retry without using anaconda?

**Comment by rishit13** [comment]
It works well with the ldc93s1 dataset . And i have preinstalled everything as said in the documentation

**Comment by rishit13** [comment]
What would u recommend ,i work on ?

**Comment by lissyx** [comment]
@rishit13 There's really nothing that can be done with the current stack, there's no information. Please retry without anaconda.

**Comment by rishit13** [comment]
Could you guide on how to use it without anaconda on the server ?

**Comment by lissyx** [comment]
It's all in the documentation. There is nothing specific, just don't install anaconda and use virtualenv as documented

**Comment by lissyx** [comment]
@rishit13 Nothing actionable, no news from you, is that working ?
