### ISSUE TITLE
libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

### ISSUE THREAD

**Issue by beeteax** [mozilla/DeepSpeech#1415]
Traceback (most recent call last):
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1790, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/anaconda3/lib/python3.6/site-packages/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv

I keep on getting this error.
I installed Mozrilla's tensorflow with cuda support and i built deepspeech cuda support as well . I am stuck no idea what's going wrong

**Comment by beeteax** [comment]
I am using tensorflow 1.6 of Mozzrila.
I dont know what else is wrong with it

**Comment by lissyx** [comment]
@beeteax We don't provide tensorflow python packages anymore, so I don't know what you installed ... This error is symptomatic of either mismatching versions or improper build. Without more details on your steps, we cannot help you.
