### ISSUE TITLE
cv-corpus-v1 : Labels length is zero in batch 5

### ISSUE THREAD

**Issue by phoenixbai** [mozilla/DeepSpeech#1416]
I am trying to run cv-corpus-v1 with following command:
`python DeepSpeech.py --train_files data/cv_corpus_v1/cv-valid-train.csv,data/cv_corpus_v1/cv-other-train.csv --dev_files data/cv_corpus_v1/cv-valid-dev.csv --test_files data/cv_corpus_v1/cv-valid-test.csv --train_batch_size 10 --validation_step 1
`
and it throws with error below.  I googled and failed to find similar issue. 
what could it be the possible reason? I dont't think it is the corpus issue. 
could you help?

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: redhat-el7
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip install
- **TensorFlow version (use command below)**: 1.6.0
- **Python version**: Python 3.6.5 :: Anaconda, Inc.
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Tesla M40 , 12G
- **Exact command to reproduce**: 

Error below:

> Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Labels length is zero in batch 5
         [[Node: tower_1/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_1/logits/_1209, tower_1/ToInt64/_1211, tower_1/Gather, tower_1/Gather_1_DequeueMany:1)]]
         [[Node: tower_1/CTCLoss/_1215 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1962_tower_1/CTCLoss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "DeepSpeech.py", line 1637, in train
    _, current_step, batch_loss, batch_report = session.run([train_op, global_step, loss, report_params], **extra_params)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/opt/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Labels length is zero in batch 5
         [[Node: tower_1/CTCLoss = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_1/logits/_1209, tower_1/ToInt64/_1211, tower_1/Gather, tower_1/Gather_1_DequeueMany:1)]]
         [[Node: tower_1/CTCLoss/_1215 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_1962_tower_1/CTCLoss", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]

>Caused by op 'tower_1/CTCLoss', defined at:
  File "DeepSpeech.py", line 1838, in <module>
    tf.app.run()

**Comment by phoenixbai** [comment]
there is zero length label in other files. 
:-(
