### ISSUE TITLE
pip install doesn't ensure required version of numpy

### ISSUE THREAD

**Issue by nh2** [mozilla/DeepSpeech#1426]
From the README:

> Pre-built binaries that can be used for performing inference with a trained model can be installed with pip3. You can then use the deepspeech binary to do speech-to-text on an audio file:
>
> For the Python bindings, it is highly recommended that you perform the installation within a Python 3.5 or later virtual environment.

I'm on Ubuntu 16.04 with a Python 3.5 virtualenv.

`pip install deepspeech` ran through successfully, but when trying to run it I get:

```
% deepspeech models/output_graph.pb models/alphabet.txt my_audio_file.wav
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/model.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/niklas/python35env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niklas/python35env/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/client.py", line 10, in <module>
    from deepspeech.model import Model
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/model.py", line 21, in <module>
    _model = swig_import_helper()
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    return importlib.import_module('_model')
  File "/home/niklas/python35env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_model'
```

It seems like the `pip install` doesn't actually install the required version of `numpy`.

**Comment by nh2** [comment]
In case it helps, manually upgrading numpy seems to bring me further:

```
% pip install -U numpy
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/43/17/cd9fa14492dbef2aaf22622db79dba087c10f125473e730cda2f2019c40b/numpy-1.14.5-cp35-cp35m-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 154kB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.11.0
    Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /home/niklas/python35env
Successfully installed numpy-1.14.5
```

```
% deepspeech models/output_graph.pb models/alphabet.txt my_audio_file.wav
Loading model from file models/output_graph.pb
2018-07-02 12:12:41.259210: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error: Alphabet size does not match loaded model: alphabet has size 0, but model has 28 classes in its output. Make sure you're passing an alphabet file with the same size as the one used for training.
Loaded model in 0.265s.
Traceback (most recent call last):
  File "/home/niklas/python35env/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/client.py", line 66, in main
    fs, audio = wav.read(args.audio)
  File "/home/niklas/python35env/lib/python3.5/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/niklas/python35env/lib/python3.5/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b'# Ea'... not understood.
```

**Comment by nh2** [comment]
> `ValueError: File format b'# Ea'... not understood.`

This is due to #1427

**Comment by lissyx** [comment]
@nh2 Thanks, the deepspeech python package does have a numpy dependency, but we have put no version requirement. It's likely that you had a previously installed version (1.11.0 according to the logs) that's not compatible with the version we use. I'm not sure what the proper solution here should be, I'm quite unhappy as to forcing minimum version, open to any better idea

**Comment by nh2** [comment]
> I'm not sure what the proper solution here should be, I'm quite unhappy as to forcing minimum version, open to any better idea

Hmm, if you want people to be able to run your model files, I suppose you could either:

* generate the model files you offer for download in the oldest `numpy` format version you wish to support and set the minimum required version to _that_
* generate the model files in a format that is not susceptible to format changes (the numpy format seems to be)

**Comment by lissyx** [comment]
@nh2 Yes, that's what I meant. The model itself does not depend on numpy, only the Python code. We would like to get rid of it, and in the mean time, I'm ont sure on which version we should target to be broad enough.

**Comment by lissyx** [comment]
Okay, so the `SWIG` part should be okay going back to NumPy API v7, which is `numpy==1.7.0`. Let's give a try to this version.
