### ISSUE TITLE
16000Hz WAV file recorded by audacity is rejected

### ISSUE THREAD

**Issue by nh2** [mozilla/DeepSpeech#1428]
From the README:

> Once everything is installed you can then use the deepspeech binary to do speech-to-text on short, approximately 5 second, audio files (currently only WAVE files with 16-bit, 16 kHz, mono are supported in the Python client)

So I created a 16kHz with Audacity on Ubuntu 16.04 using the format selection `WAV (Microsoft) signed 16-bit PCM`:

```
% file ~/tmp/test.wav 
/home/niklas/tmp/test.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 44100 Hz
```

`deepspeech` rejects it with:

```
% deepspeech models/output_graph.pb ~/tmp/test.wav models/alphabet.txt 
Loading model from file models/output_graph.pb
2018-07-02 12:16:47.702686: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.249s.
Traceback (most recent call last):
  File "/home/niklas/python35env/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/home/niklas/python35env/lib/python3.5/site-packages/deepspeech/client.py", line 69, in main
    assert fs == 16000, "Only 16000Hz input WAV files are supported for now!"
AssertionError: Only 16000Hz input WAV files are supported for now!
```

It would probably be helpful if the assertion printed what it thinks the value of `fs` is.

My version as obtained via pip:

```
% deepspeech --version
usage: deepspeech [-h] model audio alphabet [lm] [trie]
deepspeech: error: the following arguments are required: model, audio, alphabet
```

**Comment by nh2** [comment]
My bad, I just didn't spot that in my second recording Audacity actually reset the `Project Rate (Hz)` dropdown box in the bottom (as `file` also told me above, it's `mono 44100 Hz`).
