### ISSUE TITLE
Op type not registered 'Assert' in binary

### ISSUE THREAD

**Issue by 9define** [mozilla/DeepSpeech#1486]
The following error occurs only on DS v0.2.0-alpha.9-0 (using the prebuilt binaries from taskcluster for GPU on linux), DS v0.2.0-alpha.8-0 works fine. This could be due to a few reasons:
* Am I using the wrong version of CUDA?
* Do I need to build/install **mozilla's** tensorflow from source? (if so, are there any non-python prebuilt versions available?)
* I'm using the v0.1.1 models (from the github release), are those incompatible with this version?

```
deepspeech --model /.../output_graph.pb --alphabet /.../alphabet.txt --lm /.../lm.binary --trie /.../trie --audio /.../audio/2830-3980-0043.wav
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-08-09 19:52:05.133544: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'Assert' in binary running on <hostname>. Make sure the Op and Kernel are registered in the binary running in this process.
Could not create model.
```

System info:
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Arch Linux (up to date as of 8/9/18)
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Upstream TensorFlow
- **TensorFlow version (use command below)**: 1.6.0-18-g5021473 (I'm not using python, so the python command won't work for me)
- **Python version**: N/A
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: ASUS ROG GTX 1070 w/ 8GB VRAM
- **Exact command to reproduce**: See above.

**Comment by lissyx** [comment]
@9define This is because alpha 9 switched to the new, incompatible streaming model. Use Alpha 8. cc  @reuben

**Comment by ChamathK** [comment]
Facing the same error following the readme. Can you help @lissyx to get me started.

```
installed python 3.6,
pip3 install deepspeech
downloaded the model from https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz
```
created a .wav (16bit, 16kHz, 3 seconds)
ran the following command.

```
$ deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio record-8-14-2018_5-33-59.wav
Loading model from file models/output_graph.pb
TensorFlow: v1.6.0-18-g50214731ea
DeepSpeech: unknown
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-08-14 19:17:35.938912: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'Assert' in binary running on cmlchkumarasing.local. Make sure the Op and Kernel are registered in the binary running in this process.
Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/deepspeech/client.py", line 76, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/usr/local/lib/python3.7/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5
```

**Comment by reuben** [comment]
Are you absolutely sure you did `pip3 install deepspeech`? This error should only happen if you try to use binary version v0.2.0-alpha.9 with the v0.1.1 models.

**Comment by ChamathK** [comment]
Just checked my console logs, 100% sure. Any workaround I can follow to get this working?

**Comment by lissyx** [comment]
@ChamathK Your usage of command line is inconsistent with v0.1.1 python wheel, but consistent with the 0.2.0 alphas.

**Comment by lissyx** [comment]
@ChamathK Also, your output shows:
```
TensorFlow: v1.6.0-18-g50214731ea
DeepSpeech: unknown
```

Which is consistent with binaries > 0.1.1 and inconsistent with our published wheels.

Also, your stack mentions `python3.7`.

This is all consistent with @reuben previous assessments.

This is what you should have had:
```
alexandre@serveur:~$ virtualenv -p python3.6 ~/tmp/ds-test/
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/alexandre/tmp/ds-test/bin/python3.6
Also creating executable in /home/alexandre/tmp/ds-test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
alexandre@serveur:~$ source ~/tmp/ds-test/bin/activate
(ds-test) alexandre@serveur:~$ pip install deepspeech==0.2.0a9
Collecting deepspeech==0.2.0a9
  Downloading https://files.pythonhosted.org/packages/a3/91/3c389779b531ce43982b61f3c6a4b65f2b82958685b5940f9830d755d90f/deepspeech-0.2.0a9-cp36-cp36m-manylinux1_x86_64.whl (7.8MB)
    100% |████████████████████████████████| 7.8MB 10.4MB/s 
Collecting numpy>=1.7.0 (from deepspeech==0.2.0a9)
  Downloading https://files.pythonhosted.org/packages/88/29/f4c845648ed23264e986cdc5fbab5f8eace1be5e62144ef69ccc7189461d/numpy-1.15.0-cp36-cp36m-manylinux1_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 7.3MB/s 
Installing collected packages: numpy, deepspeech
Successfully installed deepspeech-0.2.0a9 numpy-1.15.0
(ds-test) alexandre@serveur:~$ deepspeech --version a
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
(ds-test) alexandre@serveur:~$ which deepspeech
/home/alexandre/tmp/ds-test/bin/deepspeech
(ds-test) alexandre@serveur:~$ deactivate 
```

**Comment by ChamathK** [comment]
Thanks @reuben @lissyx got it sorted.

Did the following steps to get the result. Apologies for python version, it was 3.7.

installed virtualenv
`$ pip3 install virtualenv`
created virtual environment
`$ virtualenv -p python3 ~/tmp/ds-test/`
activated the virtual environment
`$ source ~/tmp/ds-test/bin/activate`
installed deepspeech 0.2.0a8 (as mentioned in above thread to support v.0.1.1 model)
`$ pip install deepspeech==0.2.0a8`

```
(ds-test) cmlchkumarasing:deepsearch cmlchkumarasing$ pip install deepspeech==0.2.0a8
Collecting deepspeech==0.2.0a8
  Downloading https://files.pythonhosted.org/packages/40/2e/0a763368b7de281ffbb0e0cf076e3f83f988f358bc71cf46978210aad1c4/deepspeech-0.2.0a8-cp37-cp37m-macosx_10_10_x86_64.whl (9.9MB)
    100% |████████████████████████████████| 9.9MB 1.4MB/s 
Collecting numpy>=1.14.5 (from deepspeech==0.2.0a8)
  Downloading https://files.pythonhosted.org/packages/3a/db/5c4dab58c03a7ea2561353cb240e96198415f09d65dd63d58058e135f2f9/numpy-1.15.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (24.5MB)
    100% |████████████████████████████████| 24.5MB 1.2MB/s 
Installing collected packages: numpy, deepspeech
Successfully installed deepspeech-0.2.0a8 numpy-1.15.0
```

```
(ds-test) cmlchkumarasing:deepsearch cmlchkumarasing$ deepspeech --version a
TensorFlow: v1.6.0-16-gc346f2c8fd
DeepSpeech: unknown
```
```

(ds-test) cmlchkumarasing:deepsearch cmlchkumarasing$ deepspeech --model models/output_graph.pb --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio record-8-14-2018_5-33-59.wav
Loading model from file models/output_graph.pb
TensorFlow: v1.6.0-16-gc346f2c8fd
DeepSpeech: unknown
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-08-15 10:58:42.007781: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 2.85s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 6.12s.
Running inference.
hi hello
Inference took 27.876s for 3.709s audio file.
```
