### ISSUE TITLE
ValueError: Variable lstm_fused_cell_1/kernel does not exist, or was not created with tf.get_variable()

### ISSUE THREAD

**Issue by sidedger** [mozilla/DeepSpeech#1500]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:
-centos 7:
- TensorFlow installed from pip:
- **TensorFlow version (1.10.0):
- **Python version 3.6: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

I update codes to the last version.
when i run the run-ldc93s1.sh，occur the error below:

```
Traceback (most recent call last):
  File "DeepSpeech.py", line 1945, in <module>
    tf.app.run(main)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1901, in main
    train()
  File "DeepSpeech.py", line 1499, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 634, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, dropout_rates)
  File "DeepSpeech.py", line 515, in calculate_mean_edit_distance_and_loss
    logits, _ = BiRNN(batch_x, batch_seq_len, dropout)
  File "DeepSpeech.py", line 448, in BiRNN
    output, output_state = fw_cell(inputs=layer_3, dtype=tf.float32, sequence_length=seq_length, initial_state=previous_state)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 362, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 728, in __call__
    self.build(input_shapes)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py", line 632, in build
    "kernel", [input_size + self._num_units, self._num_units * 4])
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 461, in add_variable
    return self.add_weight(*args, **kwargs)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 276, in add_weight
    getter=vs.get_variable)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 565, in add_weight
    aggregation=aggregation)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 535, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1467, in get_variable
    aggregation=aggregation)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1217, in get_variable
    aggregation=aggregation)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 527, in get_variable
    aggregation=aggregation)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 481, in _true_getter
    aggregation=aggregation)
  File "/home/zaki/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 866, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable lstm_fused_cell_1/kernel does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?
```

**Comment by lissyx** [comment]
You document `TensorFlow version (1.10.0)`, while our code is meant to run on r1.6.

**Comment by sidedger** [comment]
@lissyx  Thank you for your reply. I will create a new env for tf 1.6.

**Comment by reuben** [comment]
@lissyx this is a problem even on r1.6, but we don't have multi-GPU training tests. I'll fix it.

**Comment by lissyx** [comment]
Oh, sorry for the confusion then :/

**Comment by lissyx** [comment]
@sidedger Looks like you documented a legit issue :-)

**Comment by sidedger** [comment]
Yes. I create a new evn for tf 1.6. Occur the same error.  Thank you for your hard work.

**Comment by reuben** [comment]
@sidedger can you check if PR #1502 fixes it for you? Thanks!

**Comment by sidedger** [comment]
Sure, I am very glad to check it.

**Comment by sidedger** [comment]
I had download the native_client with gpu version.
when i run the run-ldc93s1.sh，occur the error below:
TypeError: ctc_beam_search_decoder_with_lm() missing 1 required positional argument: 'word_count_weight'

So i add the FLAGS.word_count_weight in the front of  DeepSpeech.py. 
And add word_count_weight=FLAGS.word_count_weight when call the custom_op_module.ctc_beam_search_decoder_with_lm in function named "decode_with_lm"

Then resolved error aboved, I occur a new error:

 Caused by op 'save_1/RestoreV2_1', defined at:
  File "DeepSpeech.py", line 1922, in <module>
    tf.app.run(main)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1878, in main
    train()
  File "DeepSpeech.py", line 1613, in train
    config=session_config) as session:
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 437, in create_session
    self._scaffold.finalize()
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 212, in finalize
    self._saver = training_saver._get_saver_or_default()  # pylint: disable=protected-access
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 871, in _get_saver_or_default
    saver = Saver(sharded=True, allow_empty=True)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1293, in __init__
    self.build()
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 790, in _build_internal
    restore_sequentially, reshape)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 502, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 449, in _AddRestoreOps
    restore_sequentially)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 847, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1030, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/home/zaki/anaconda3/envs/deepspeech/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key lstm_fused_cell/bias not found in checkpoint
         [[Node: save_1/RestoreV2_1 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_1/tensor_names, save_1/RestoreV2_1/shape_and_slices)]]

**Comment by reuben** [comment]
Are you using an existing checkpoint? The architecture has changed for the streaming API and it's not compatible with older checkpoints.
