### ISSUE TITLE
File b' ' does not exist error occurs for my own trained model

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/DeepSpeech#1518]
python3 DeepSpeech.py --model ../ownaudio-model/output_graph.pbmm --alphabet ../ownaudio-model/alphabet.txt --lm ../ownaudio-model/lm.binary --trie ../ownaudio-model/trie --audio ../audio_folder/audio/createdaudio1.wav

/home/dell/Videos/another_one/DeepSpeech/util/audio.py:17: DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.
  category=DeepSpeechDeprecationWarning)
Traceback (most recent call last):
  File "DeepSpeech.py", line 1870, in <module>
    tf.app.run()
  File "/home/dell/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1827, in main
    train()
  File "DeepSpeech.py", line 1467, in train
    next_index=lambda i: COORD.get_next_index('train'))
  File "/home/dell/Videos/another_one/DeepSpeech/util/feeding.py", line 90, in __init__
    file = pandas.read_csv(csv, encoding='utf-8', na_filter=False)
  File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b' ' does not exist

i don't know what is happened? can you fix this issue sir?

**Comment by lissyx** [comment]
@MuruganR96 I don't know what you are doing: mixing `DeepSpeech.py` arguments with those from the native client, but it's not going to work for sure.

**Comment by MuruganR96** [comment]
sir, can you explain where i am refferd?

**Comment by lissyx** [comment]
@MuruganR96 You are using the command line arguments documented for the native client code. It's unclear what you want to do, and you don't explain what you are trying to achieve with that command line, so there's nothing we can do so far. Also, as this is obviously not a bug with the codebase, can you please request any further help on discourse? https://discourse.mozilla.org/c/deep-speech

**Comment by MuruganR96** [comment]
NO SIR It is a bug. i explain what i did.

i create a my own audio files and create a csv files like audio_file_dev.csv, audio_file_test.csv, audio_file_train.csv

used alphabet.txt is similar and then create a vocabular.txt for my audio sentence. 

then create a lm.arpa and lm.binary file , trie file also.

finally run on model,

 python3 -u DeepSpeech.py   --train_files /home/dell/Videos/ownaudio-model/audio_folder/audio_file_train.csv   --dev_files /home/dell/Videos/ownaudio-model/audio_folder/audio_file_dev.csv   --test_files /home/dell/Videos/ownaudio-model/audio_folder/audio_file_test.csv   --train_batch_size 1   --dev_batch_size 1   --test_batch_size 1   --n_hidden 375   --epoch 250   --validation_step 1   --early_stop True   --earlystop_nsteps 6   --estop_mean_thresh 0.1   --estop_std_thresh 0.1   --dropout_rate 0   --learning_rate 0.000010   --report_count 100   --use_seq_length False   --export_dir /home/dell/Videos/ownaudio-model   --checkpoint_dir /home/dell/Videos/audio_folder/ownaudio-model  --alphabet_config_path /home/dell/Videos/ownaudio-model/alphabet.txt   --lm_binary_path /home/dell/Videos/ownaudio-model/lm.binary

it is finally trained and created a output_model.pb.

i just run on below  command similar to deepspeech readme,md instruction,

python3 DeepSpeech.py --model ../ownaudio-model/output_graph.pbmm --alphabet ../ownaudio-model/alphabet.txt --lm ../ownaudio-model/lm.binary --trie ../ownaudio-model/trie --audio ../audio_folder/audio/createdaudio1.wav

it was shown in this below error,


/home/dell/Videos/another_one/DeepSpeech/util/audio.py:17: DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.
category=DeepSpeechDeprecationWarning)
Traceback (most recent call last):
File "DeepSpeech.py", line 1870, in 
tf.app.run()
File "/home/dell/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
_sys.exit(main(argv))
File "DeepSpeech.py", line 1827, in main
train()
File "DeepSpeech.py", line 1467, in train
next_index=lambda i: COORD.get_next_index('train'))
File "/home/dell/Videos/another_one/DeepSpeech/util/feeding.py", line 90, in init
file = pandas.read_csv(csv, encoding='utf-8', na_filter=False)
File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
return _read(filepath_or_buffer, kwds)
File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in init
self._make_engine(self.engine)
File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
self._engine = CParserWrapper(self.f, **self.options)
File "/home/dell/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in init
self._reader = parsers.TextReader(src, **kwds)
File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.cinit
File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b' ' does not exist

sir pls fix this issue.thank you so much for your reply sir. thank you so much for the quick reply

**Comment by lissyx** [comment]
Please read the documentation, your second command line makes no sense. Use the native client code  if you want to run inference, or check `--help` if you want to use `DeepSpeech.py`.

**Comment by MuruganR96** [comment]
:) Sir ,I am  running ----------------->python3 DeepSpeech.py --help 

it display arguments, below

(deepspeech_s2t) dell@dell-OptiPlex-5050:~/Videos/another_one/DeepSpeech$ python3 DeepSpeech.py --helpfull
/home/dell/Videos/another_one/DeepSpeech/util/audio.py:17: DeepSpeechDeprecationWarning: DeepSpeech Python bindings could not be imported, resorting to slower code to compute audio features. Refer to README.md for instructions on how to install (or build) the DeepSpeech Python bindings.
  category=DeepSpeechDeprecationWarning)

       USAGE: DeepSpeech.py [flags]
flags:

DeepSpeech.py:
  --alphabet_config_path: path to the configuration file specifying the alphabet used by the network. See the comment in data/alphabet.txt for a description of the format.
    (default: 'data/alphabet.txt')
  --b1_stddev: standard deviation to use when initialising b1
    (a number)
  --b2_stddev: standard deviation to use when initialising b2
    (a number)
  --b3_stddev: standard deviation to use when initialising b3
    (a number)
  --b5_stddev: standard deviation to use when initialising b5
    (a number)
  --b6_stddev: standard deviation to use when initialising b6
    (a number)
  --beam_width: beam width used in the CTC decoder when building candidate transcriptions
    (default: '1024')
    (an integer)
  --beta1: beta 1 parameter of Adam optimizer
    (default: '0.9')
    (a number)
  --beta2: beta 2 parameter of Adam optimizer
    (default: '0.999')
    (a number)
  --checkpoint_dir: directory in which checkpoints are stored - defaults to directory "deepspeech/checkpoints" within user's data home specified by the XDG Base Directory Specification
    (default: '')
  --checkpoint_secs: checkpoint saving interval in seconds
    (default: '600')
    (an integer)
  --coord_host: coordination server host
    (default: 'localhost')
  --coord_port: coordination server port
    (default: '2500')
    (an integer)
  --coord_retries: number of tries of workers connecting to training coordinator before failing
    (default: '100')
    (an integer)
  --decoder_library_path: path to the libctc_decoder_with_kenlm.so library containing the decoder implementation.
    (default: 'native_client/libctc_decoder_with_kenlm.so')
  --default_stddev: default standard deviation to use when initialising weights and biases
    (default: '0.046875')
    (a number)
  --dev_batch_size: number of elements in a validation batch
    (default: '1')
    (an integer)
  --dev_files: comma separated list of files specifying the dataset used for validation. multiple files will get merged
    (default: '')
  --display_step: number of epochs we cycle through before displaying detailed progress - 0 means no progress display
    (default: '0')
    (an integer)
  --dropout_rate: dropout rate for feedforward layers
    (default: '0.05')
    (a number)
  --dropout_rate2: dropout rate for layer 2 - defaults to dropout_rate
    (default: '-1.0')
    (a number)
  --dropout_rate3: dropout rate for layer 3 - defaults to dropout_rate
    (default: '-1.0')
    (a number)
  --dropout_rate4: dropout rate for layer 4 - defaults to 0.0
    (default: '0.0')
    (a number)
  --dropout_rate5: dropout rate for layer 5 - defaults to 0.0
    (default: '0.0')
    (a number)
  --dropout_rate6: dropout rate for layer 6 - defaults to dropout_rate
    (default: '-1.0')
    (a number)
  --[no]early_stop: enable early stopping mechanism over validation dataset. Make sure that dev FLAG is enabled for this to work
    (default: 'true')
  --earlystop_nsteps: number of steps to consider for early stopping. Loss is not stored in the checkpoint so when checkpoint is revived it starts the loss calculation from start at that point
    (default: '4')
    (an integer)
  --epoch: target epoch to train - if negative, the absolute number of additional epochs will be trained
    (default: '75')
    (an integer)
  --epsilon: epsilon parameter of Adam optimizer
    (default: '1e-08')
    (a number)
  --estop_mean_thresh: mean threshold for loss to determine the condition if early stopping is required
    (default: '0.5')
    (a number)
  --estop_std_thresh: standard deviation threshold for loss to determine the condition if early stopping is required
    (default: '0.5')
    (a number)
  --export_dir: directory in which exported models are stored - if omitted, the model won't get exported
    (default: '')
  --export_version: version number of the exported model
    (default: '1')
    (an integer)
  --[no]fulltrace: if full trace debug info should be generated during training
    (default: 'false')
  --h1_stddev: standard deviation to use when initialising h1
    (a number)
  --h2_stddev: standard deviation to use when initialising h2
    (a number)
  --h3_stddev: standard deviation to use when initialising h3
    (a number)
  --h5_stddev: standard deviation to use when initialising h5
    (a number)
  --h6_stddev: standard deviation to use when initialising h6
    (a number)
  --initialize_from_frozen_model: path to frozen model to initialize from. This behaves like a checkpoint, loading the weights from the frozen model and starting training with those weights. The optimizer
    parameters aren't restored, so remember to adjust the learning rate.
    (default: '')
  --iters_per_worker: number of train or inference iterations per worker before results are sent back to coordinator
    (default: '1')
    (an integer)
  --job_name: job name - one of localhost (default), worker, ps
    (default: 'localhost')
  --learning_rate: learning rate of Adam optimizer
    (default: '0.001')
    (a number)
  --limit_dev: maximum number of elements to use from validation set- 0 means no limit
    (default: '0')
    (an integer)
  --limit_test: maximum number of elements to use from test set- 0 means no limit
    (default: '0')
    (an integer)
  --limit_train: maximum number of elements to use from train set - 0 means no limit
    (default: '0')
    (an integer)
  --lm_binary_path: path to the language model binary file created with KenLM
    (default: 'data/lm/lm.binary')
  --lm_trie_path: path to the language model trie file created with native_client/generate_trie
    (default: 'data/lm/trie')
  --lm_weight: the alpha hyperparameter of the CTC decoder. Language Model weight.
    (default: '1.75')
    (a number)
  --log_level: log level for console logs - 0: INFO, 1: WARN, 2: ERROR, 3: FATAL
    (default: '1')
    (an integer)
  --[no]log_placement: whether to log device placement of the operators to the console
    (default: 'false')
  --[no]log_traffic: log cluster transaction and traffic information during debug logging
    (default: 'false')
  --max_to_keep: number of checkpoint files to keep - default value is 5
    (default: '5')
    (an integer)
  --n_hidden: layer width to use when initialising layers
    (default: '2048')
    (an integer)
  --one_shot_infer: one-shot inference mode: specify a wav file and the script will load the checkpoint and perform inference on it. Disables training, testing and exporting.
    (default: '')
  --ps_hosts: parameter servers - comma separated list of hostname:port pairs
    (default: '')
  --random_seed: default random seed that is used to initialize variables
    (default: '4567')
    (an integer)
  --relu_clip: ReLU clipping value for non-recurrant layers
    (default: '20.0')
    (a number)
  --[no]remove_export: whether to remove old exported models
    (default: 'false')
  --replicas: total number of replicas - if negative, its absolute value is multiplied by the number of workers
    (default: '-1')
    (an integer)
  --replicas_to_agg: number of replicas to aggregate - if negative, its absolute value is multiplied by the number of workers
    (default: '-1')
    (an integer)
  --report_count: number of phrases with lowest WER (best matching) to print out during a WER report
    (default: '10')
    (an integer)
  --summary_dir: target directory for TensorBoard summaries - defaults to directory "deepspeech/summaries" within user's data home specified by the XDG Base Directory Specification
    (default: '')
  --summary_secs: interval in seconds for saving TensorBoard summaries - if 0, no summaries will be written
    (default: '0')
    (an integer)
  --task_index: index of task within the job - worker with index 0 will be the chief
    (default: '0')
    (an integer)
  --[no]test: whether to test the network
    (default: 'true')
  --test_batch_size: number of elements in a test batch
    (default: '1')
    (an integer)
  --test_files: comma separated list of files specifying the dataset used for testing. multiple files will get merged
    (default: '')
  --[no]train: whether to train the network
    (default: 'true')
  --train_batch_size: number of elements in a training batch
    (default: '1')
    (an integer)
  --train_files: comma separated list of files specifying the dataset used for training. multiple files will get merged
    (default: '')
  --[no]use_seq_length: have sequence_length in the exported graph (will make tfcompile unhappy)
    (default: 'true')
  --[no]use_warpctc: whether to use GPU bound Warp-CTC
    (default: 'false')
  --valid_word_count_weight: valid word insertion weight. This is used to lessen the word insertion penalty when the inserted word is part of the vocabulary.
    (default: '1.0')
    (a number)
  --validation_step: number of epochs we cycle through before validating the model - a detailed progress report is dependent on "--display_step" - 0 means no validation steps
    (default: '0')
    (an integer)
  --wer_log_pattern: pattern for machine readable global logging of WER progress; has to contain %%s, %%s and %%f for the set name, the date and the float respectively; example: "GLOBAL LOG:
    logwer('12ade231', %%s, %%s, %%f)" would result in some entry like "GLOBAL LOG: logwer('12ade231', 'train', '2017-05-18T03:09:48-0700', 0.05)"; if omitted (default), there will be no logging
    (default: '')
  --word_count_weight: the beta hyperparameter of the CTC decoder. Word insertion weight (penalty).
    (default: '1.0')
    (a number)
  --worker_hosts: workers - comma separated list of hostname:port pairs
    (default: '')

tensorflow.python.platform.app:
  -h,--[no]help: show this help
    (default: 'false')
  --[no]helpfull: show full help
    (default: 'false')
  --[no]helpshort: show this help
    (default: 'false')

absl.flags:
  --flagfile: Insert flag definitions from the given file into the command line.
    (default: '')
  --undefok: comma-separated list of flag names that it is okay to specify on the command line even if the program does not define a flag with that name.  IMPORTANT: flags in this list that have arguments
    MUST use the --flag=value format.
    (default: '')


SIR NO ANY ARGUMENTS depends on native_client sir. what can i do sir? can you help me sir? 

thanks for quick reply sir :)

**Comment by lissyx** [comment]
@MuruganR96 https://github.com/mozilla/DeepSpeech/blob/master/README.md#using-the-model https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md

**Comment by MuruganR96** [comment]
thank you so much sir. i will try to configure native_client for your given link. and i update my status sir. 

thank you for your wonderful reply sir. :)

**Comment by MuruganR96** [comment]
Sir I can't build a native_client for DeepSpeech-0.2.0-alpha.9. because i followed this link to 
 (https://github.com/mozilla/DeepSpeech/blob/master/native_client/README.md) build a native_client.

but bazel not build correctly for CPU Ubuntu-16.04.

sir give your native_client file for DeepSpeech-0.2.0-alpha.9. i will integrate in that our deepspeech model and then i will try to run.

thank you sir

**Comment by lissyx** [comment]
@MuruganR96 Why do you absolutely want to build it when we have documented prebuilt binaries ?

**Comment by MuruganR96** [comment]
sir, https://github.com/mozilla/DeepSpeech/issues/1518#issuecomment-418675056  in this suggestion i was followed to run the native client code, i want to run inference for my output_model.pb , lm.binary files but the bazel not bulid completely sir.


![issue111](https://user-images.githubusercontent.com/35978784/45147161-f0c4fe00-b1e1-11e8-82fa-f11ee2c0cc49.png)


sir please can you explain me. i am very confused.( README.md for native_client also)

**Comment by lissyx** [comment]
@MuruganR96 Please avoid pictures for debugging, it's not usable.

**Comment by lissyx** [comment]
@MuruganR96 Why do you absolutely want to rebuild this codebase when we have prebuilt binaries ready for you ?

https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.v0.2.0-alpha.9/cpu

We also document downloading them using `util/taskcluster.py`.

**Comment by lissyx** [comment]
@MuruganR96 I'm sorry, but you are not reading what I'm explaining since the begining. You keep doing the same thing, over and over, when I explain you. And you keep posting screenshots when I already told you not to, because it's more than inconvenient for debugging and it's not searchable for others as well.

**You are not using the correct tool. Use the native client binaries, not `DeepSpeech.py` for inference.**

So:
 - please read the documentation,
 - please reach for help on discourse and,

I'm happy to help, but if you don't read or tell us what you don't understand in the documentation, then we are all loosing our time and we cannot improve the project.

**Comment by MuruganR96** [comment]
@lissyx excuse me sir. and will read the documentation fully sir. and do my best sir. thank so much sir.:)

**Comment by MuruganR96** [comment]
sir thank you so much.it is working fine now. https://discourse.mozilla.org/t/inference-model-trained-with-deepspeech-py/28663/3
followed this hint sir.

deepspeech --model  /home/dell/Pictures/ownaudio-model/output_graph.pb --alphabet  /home/dell/Pictures/ownaudio-model/alphabet.txt --lm  /home/dell/Pictures/ownaudio-model/lm.binary --trie  /home/dell/Pictures/ownaudio-model/trie  --audio /home/dell/Pictures/audio_folder/audio/creditaudio1.wav
Loading model from file /home/dell/Pictures/ownaudio-model/output_graph.pb
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-06 16:59:50.435691: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.00857s.
Loading language model from files /home/dell/Pictures/ownaudio-model/lm.binary /home/dell/Pictures/ownaudio-model/trie
Loaded language model in 0.000846s.
Warning: original sample rate (44100) is different than 16kHz. Resampling might produce erratic speech recognition.
Running inference.
2018-09-06 16:59:50.667509: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.667543: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.676323: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.676382: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.682173: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.682204: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.687235: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.687275: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.692119: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.692150: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.696901: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.696932: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.701944: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.701987: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.712830: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.712865: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.718474: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.718509: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.723975: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.724023: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.729482: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.729515: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.735410: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.735455: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.745439: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.745470: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.750463: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.750493: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
2018-09-06 16:59:50.754211: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:844] BlockLSTMOp is inefficient when both batch_size and input_size are odd. You are using: batch_size=1, input_size=375
2018-09-06 16:59:50.754242: W tensorflow/contrib/rnn/kernels/lstm_ops.cc:849] BlockLSTMOp is inefficient when both batch_size and cell_size are odd. You are using: batch_size=1, cell_size=375
what that that that that that that get total
Inference took 0.531s for 12.672s audio file.
soulful  thank you sir.:)

**Comment by MuruganR96** [comment]
sir how to fine tuning language model to get good validation loss.

**Comment by lissyx** [comment]
@MuruganR96 I'm genuinely happy to see you have been able to figure this out, but really, please look on previous threads on Discourse, there's already people doing exactly that, and you can ask there if you really need. The Github issues are really only for bugs / features requests, not discussions.

**Comment by MuruganR96** [comment]
Sir sorry for the inconvenience. I trained my own audio files with epoch = 250, LR =0.000025, audio files =50, validation loss=14.97233
Test of Epoch 250 - WER: 0.114379, loss: 14.972339630126953, mean edit distance: 0.024213
and i testing my new recorded audio with similar content. it is not working. 

Loading model from file /home/dell/Pictures/ownaudio-model/output_graph.pb
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-alpha.9-0-gd59cdc3
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-07 12:05:51.100430: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loaded model in 0.00606s.
Loading language model from files /home/dell/Pictures/ownaudio-model/lm.binary /home/dell/Pictures/ownaudio-model/trie
Loaded language model in 0.000868s.
Running inference.
a more card (expected output: what is my created card status)
Inference took 0.289s for 2.769s audio file.

just don't feel bad sir. i am a beginner for this concept. so help me sir.
thank you sir :)

**Comment by lissyx** [comment]
@MuruganR96 There is no bug here. Please take this kind of discussion on Discourse.

**Comment by MuruganR96** [comment]
thank you sir.
