### ISSUE TITLE
will you please tell the arguements

### ISSUE THREAD

**Issue by akshat9425** [mozilla/DeepSpeech#1593]
i am running client.py file and using latest updated model of mozilla

here is my command: python client.py --model /home/user/new_mozilla/speech/models_2 --alphabet /home/user/new_mozilla/speech/models_2/alphabet.txt --lm /home/user/new_mozilla/speech/models_2/lm.binary --trie /home/user/new_mozilla/speech/models_2/trie --audio /home/user/new_mozilla/speech/gaurav.wav --version

it provides me version i did no changes to client.py 

please tell me where i am doing wrong in command or please send me a demo command

**Comment by b-ak** [comment]
You can't use the version argument if you want to run inference. Run the same thing without the version.

**Comment by akshat9425** [comment]
i got this output after following your instructions
TensorFlow: v1.6.0-18-g5021473
DeepSpeech: v0.2.0-0-g009f9b6
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2018-09-26 17:25:47.550359: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Error: Could not infer context window size from model file. Make sure input_node is a 3D tensor with the last dimension of size MFCC_FEATURES * ((2 * context window) + 1). If you changed the number of features in the input, adjust the MFCC_FEATURES constant in native_client/deepspeech.cc
Traceback (most recent call last):
  File "client.py", line 111, in <module>
    main()
  File "client.py", line 81, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/user/new_mozilla/speech/DeepSpeech-0.2.0 (2)/native_client/python/mypython/local/lib/python2.7/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 3

**Comment by akshat9425** [comment]
sorry to disturb and thank alot for help it ran after changing first argument to .pbmm file thanks again
