### ISSUE TITLE
Cannot inference with a single audio file

### ISSUE THREAD

**Issue by hao-olli-ai** [mozilla/DeepSpeech#1612]
Hi all,

I got a problem with the function "do_single_file_inference" after running the program as follow:

1. Training: I trained with 1000 epoches and the result was:
"I Test of Epoch 1000 - WER: 0.003585, loss: 0.11275059029160085, mean edit distance: 0.001187"

2. Using inferencing function:
I changed the mode of program from train and test to one_shot_infer as follow:
tf.app.flags.DEFINE_boolean ('train',            False,        'whether to train the network')
tf.app.flags.DEFINE_boolean ('test',             False,        'whether to test the network')
tf.app.flags.DEFINE_string  ('one_shot_infer',     
 './vivos/train/waves/VIVOSDEV01/VIVOSDEV01_R002.wav',       'one-shot ...')
then I run DeepSpeech again

3. Error:
Traceback (most recent call last):
  File "DeepSpeech.py", line 1977, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1969, in main
    do_single_file_inference(FLAGS.one_shot_infer)
  File "DeepSpeech.py", line 1913, in do_single_file_inference
    inputs['input_lengths']: [len(chunk)],
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1086, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 16, 26) for Tensor 'input_node:0', which has shape '(1, 16, 19, 26)'

I run the program in Ubuntu 16.04, tensorflow-gpu 1.11, GTX 1080 Ti

The file I use for inferencing is one of my training files. When training, there is no problem but it is an error in inferencing. I do not know what happen. Help me, please!

**Comment by lissyx** [comment]
I do repoduce that :'(
