### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by sagar2226** [mozilla/DeepSpeech#1665]
```
./bin/run-ldc93s1.sh
+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/Abhay/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/Abhay/.local/share/deepspeech/ldc93s1
/home/Abhay/.conda/envs/deepspeech-env/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


Traceback (most recent call last):
  File "DeepSpeech.py", line 1861, in <module>
    tf.app.run()
  File "/home/Abhay/.conda/envs/deepspeech-env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1813, in main
    initialize_globals()
  File "DeepSpeech.py", line 334, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/Abhay/.conda/envs/deepspeech-env/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/Abhay/.conda/envs/deepspeech-env/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: native_client/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl11string_viewE
```

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/wiki#i-get-an-error-about-native_clientlibctc_decoder_with_kenlmso-undefined-symbol-during-training

**Comment by lissyx** [comment]
@sagar2226 Next time, please follow the issue template, document your setup, and use proper code formatting.
