### ISSUE TITLE
"KeyError: u't'" using docker container

### ISSUE THREAD

**Issue by mouradski** [mozilla/DeepSpeech#1695]
`docker run -v /f/data:/data deepspeech python ./DeepSpeech.py --checkpoint_dir /data/checkpoint --epoch -3  --checkpoint_secs 2000  --train_files /data/training3/librivox-train-clean-360.csv --dev_files /data/training3/librivox-dev-clean.csv,/data/training3/librivox-dev-other.csv --test_files /data/training3/librivox-test-clean.csv,/data/training3/librivox-test-other.csv  --learning_rate 0.0001`

i got this error : 

```
brivox-dev-clean.csv,/data/training3/librivox-dev-other.csv --test_files /data/training3/librivox-test-clean.csv,/data/training3/librivox-test-other.csv  --learning_rate 0.0001
Traceback (most recent call last):
  File "./DeepSpeech.py", line 2028, in <module>
('Preprocessing', ['/data/training3/librivox-train-clean-360.csv'])
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 1984, in main
    train()
  File "./DeepSpeech.py", line 1481, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/DeepSpeech/util/preprocess.py", line 68, in preprocess
    out_data = pmap(step_fn, source_data.iterrows())
  File "/DeepSpeech/util/preprocess.py", line 13, in pmap
    results = pool.map(fun, iterable)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: u't'
```
i'm using the same dataset with cpu to training my server and all works fine

Docker on windows 10
GPU : GTX1080ti

Thanx for your work :)

**Comment by mouradski** [comment]
Ah maybe :) can i pull an image from somewhere to try ?

I do not have linux on hand to try with my GTX

**Comment by mouradski** [comment]
fixed, i built image in Unix env and run it on windows, all is ok :)

**Comment by lissyx** [comment]
Thanks for checking :)
