### ISSUE TITLE
ldc93s1 not downloading

### ISSUE THREAD

**Issue by xaviiee** [mozilla/DeepSpeech#1752]
Hi, I just cloned the repo and try to run bin/run-ldc93s1.sh in order to understand how to build my own model, but then I ran into a series of python2/3 incompatibilities. My shell interprets the python command included in the run-ldc83s1 script as being python2, so I changed the shell to force python3, but it still outputs this error:

```$ bash bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/xlage/.local/share/deepspeech/ldc93s1
+ python3 -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 75 --checkpoint_dir /home/xlage/.local/share/deepspeech/ldc93s1
Preprocessing ['data/ldc93s1/ldc93s1.csv']
Traceback (most recent call last):
  File "DeepSpeech.py", line 941, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 893, in main
    train()
  File "DeepSpeech.py", line 388, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/home/xlage/tmp/DeepSpeech/util/preprocess.py", line 69, in preprocess
    out_data = pmap(step_fn, source_data.iterrows())
  File "/home/xlage/tmp/DeepSpeech/util/preprocess.py", line 13, in pmap
    results = pool.map(fun, iterable)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/xlage/tmp/DeepSpeech/util/preprocess.py", line 21, in process_single_file
    features = audiofile_to_input_vector(file.wav_filename, numcep, numcontext)
  File "/home/xlage/tmp/DeepSpeech/util/audio.py", line 15, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/usr/lib/python3/dist-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/usr/lib/python3/dist-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format b''... not understood.
```

Could someone tell me what I did wrong or if there is an error in the script somewhere?

**Comment by reuben** [comment]
That does not look like a Python 2/3 issue, more like your ldc93s1 data is corrupted or missing. Check if data/ldc93s1/ldc93s1.wav is a proper audio file. Try removing data/ldc93s1 and running the script again.

**Comment by xaviiee** [comment]
You're right, the wav data is missing. I deleted the directory and re-ran the script, here is the result:

```$ bash bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ echo 'Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.'
Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.
+ python3 -u bin/import_ldc93s1.py ./data/ldc93s1
No path "./data/ldc93s1" - creating ...
No archive "./data/ldc93s1/LDC93S1.wav" - downloading...
Traceback (most recent call last):
  File "bin/import_ldc93s1.py", line 28, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_ldc93s1.py", line 18, in _download_and_preprocess_data
    local_file = maybe_download(LDC93S1_BASE + ".wav", data_dir, LDC93S1_BASE_URL + LDC93S1_BASE + ".wav")
  File "/home/xlage/tmp/DeepSpeech/bin/../util/downloader.py", line 22, in maybe_download
    bar = progressbar.ProgressBar(max_value=total_size, widgets=SIMPLE_BAR)
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by kdavis-mozilla** [comment]
It looks like you didn't install the requirements a indicated [here](https://github.com/mozilla/deepspeech#installing-prerequisites-for-training).

**Comment by kdavis-mozilla** [comment]
Are you running with python 3 or python 2? You installed requirements.txt using pip3.

**Comment by xaviiee** [comment]
That's the mistake, I installed everything with python 3 and the script is running python 2. I will check soon but that should be it. I was under the impression that the whole project was using python 3 so that's why.

**Comment by xaviiee** [comment]
The tutorial on the main page [https://github.com/mozilla/DeepSpeech#installing-prerequisites-for-training] specifies pip3, so I used pip3. But then you suggested that I should use python2 so I installed the same requirements.txt with pip2. However I'm still not better off as shown below, so what should I do?

```
$ bash bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ echo 'Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.'
Downloading and preprocessing LDC93S1 example data, saving in ./data/ldc93s1.
+ python3 -u bin/import_ldc93s1.py ./data/ldc93s1
Found archive "./data/ldc93s1/LDC93S1.wav" - not downloading.
No archive "./data/ldc93s1/LDC93S1.txt" - downloading...
Traceback (most recent call last):
  File "bin/import_ldc93s1.py", line 28, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_ldc93s1.py", line 19, in _download_and_preprocess_data
    trans_file = maybe_download(LDC93S1_BASE + ".txt", data_dir, LDC93S1_BASE_URL + LDC93S1_BASE + ".txt")
  File "/home/xlage/tmp/DeepSpeech/bin/../util/downloader.py", line 22, in maybe_download
    bar = progressbar.ProgressBar(max_value=total_size, widgets=SIMPLE_BAR)
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by kdavis-mozilla** [comment]
> But then you suggested that I should use python2

I didn't. I only asked which version of python you were running with. 

Could you provide the output of 
```bash
python --version
```

**Comment by lissyx** [comment]
> `$ bash bin/run-ldc93s1.sh `

Just a side node, the shebang specifies `sh`, not `bash`

**Comment by lissyx** [comment]
Also @xaviiee you are not using a virtual environment, as we document. Who knows what kind of interactions you might be triggering then?

**Comment by xaviiee** [comment]
@kdavis-mozilla Hmm you're right you did suggested it, my bad.

`Python 2.7.15rc1` is the result of python --version.

@lissyx the result is the same with sh or bash, and I'll try within a virtual environment again and post the results. I tried once but probably I did a mistake somewhere.

**Comment by xaviiee** [comment]
@lissyx You have the issue, there is an other package called progressbar and it seems that there is a conflict between progressbar and progressbar2. Now within a virtual environment and without this conflict it's working perfectly fine. I'm used to install everything system wide but that was not the best idea. Sorry for this mistake and thanks a lot for your patient help!
