### ISSUE TITLE
import_cv error while creating common voice dataset

### ISSUE THREAD

**Issue by abhijeet3922** [mozilla/DeepSpeech#1754]
OS Platform and Distribution (Linux Ubuntu 16.04):
I comfortably ran and created data-set from bin/import_ted.py

while running >> bin/import_cv.py ./cv/ from DeepSpeech directory, I am getting an error while importing cv-valid-train.csv.

No CSV file "/home/abhijeet/Desktop/dl_projects/DeepSpeech/cv/cv-valid-train.csv" - importing "/home/abhijeet/Desktop/dl_projects/DeepSpeech/cv/cv_corpus_v1/cv-valid-train.csv"...
Importing mp3 files...
Progress |##################################                                                                                    |  29% completedTraceback (most recent call last):
  File "bin/import_cv.py", line 124, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_cv.py", line 39, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "bin/import_cv.py", line 54, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
  File "bin/import_cv.py", line 97, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/home/abhijeet/anaconda3/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
  File "/home/abhijeet/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv.py", line 80, in one_sample
    frames = int(subprocess.check_output(['soxi', '-s', wav_filename], stderr=subprocess.STDOUT))
  File "/home/abhijeet/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/abhijeet/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['soxi', '-s', '/home/abhijeet/Desktop/dl_projects/DeepSpeech/cv/cv_corpus_v1/cv-valid-train/sample-057655.wav']' returned non-zero exit status 1.

Then I tried running this
>> soxi -s cv/cv_corpus_v1/cv-valid-train/sample-057655.wav
soxi FAIL formats: can't open input file `cv/cv_corpus_v1/cv-valid-train/sample-057655.wav': WAVE: RIFF header not found

Shall I remove this file and keep removing such files as they don't have headers? What am I missing here ?

**Comment by lissyx** [comment]
> Shall I remove this file and keep removing such files as they don't have headers? What am I missing here ?

I guess that should be how to deal with, **and** filing an issue against Common Voice project: this needs to be fixed upstream. Maybe the importer should be more tolerant and not die on those but report them as broken files?

**Comment by tilmankamp** [comment]
@abhijeet3922 Is the corresponding mp3 file (`cv/cv_corpus_v1/cv-valid-train/sample-057655.mp3`) existing?

**Comment by abhijeet3922** [comment]
@tilmankamp hey, there were around 12-15 such .mp3 files for which this error was there in cv-valid-train. All the .mp3 were successfully converted to .wav but their headers were not found.

Thanks.

**Comment by tilmankamp** [comment]
@abhijeet3922 This is interesting. Could you run `ffprobe` on one of those wav files and share the output?

**Comment by lissyx** [comment]
@abhijeet3922 Care to share status ?

**Comment by lissyx** [comment]
Closing for lack of activity and nothing actionable. New Common Voice releases should be imported with `import_cv2.py` anyway.
