### ISSUE TITLE
ModuleNotFoundError: No module named '_impl' on using DeepSpeech 

### ISSUE THREAD

**Issue by santhoshkurnapally** [mozilla/DeepSpeech#1839]
* Cloned the DeepSpeech Repository
* Downloaded Pre-trained model
* Created virtual environment
* Activated Environment
* Installed DeepSpeech Python Bindings using following command
- $ pip3 install deepspeech
* Tried to call the sample binary using "deepspeech"  on command line 
* Encountered "ModuleNotFoundError: No module named '_impl'" error.
* Please help
* error occured
-------------------------------------------------------------------------------------------------------------------
```
(virtualenvironment) [santhosh_3.6@ip DeepSpeech]$ deepspeech
Traceback (most recent call last):
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/__init__.py", line 4, in <module>
    from deepspeech.impl import AudioToInputVector as audioToInputVector
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_impl'
(virtualenvironment) [santhosh_3.6@ip DeepSpeech]$
```
------------------------------------------------------------------------------------------------------------------

**Comment by lissyx** [comment]
>     * Cloned the DeepSpeech Repository
> 
>     * Downloaded Pre-trained model
> 
>     * Created virtual environment
> 
>     * Activated Environment
> 
>     * Installed DeepSpeech Python Bindings using following command
> 
> 
>     * $ pip3 install deepspeech
> 
> 
>     * Tried to call the sample binary using "deepspeech"  on command line
> 
>     * Encountered "ModuleNotFoundError: No module named '_impl'" error.
> 
>     * Please help
> 
>     * error occured
> 
> 
> (virtualenvironment) [santhosh_3.6@ip DeepSpeech]$ deepspeech
> Traceback (most recent call last):
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
> return importlib.import_module(mname)
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/importlib/**init**.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 994, in _gcd_import
> File "", line 971, in _find_and_load
> File "", line 955, in _find_and_load_unlocked
> File "", line 658, in _load_unlocked
> File "", line 571, in module_from_spec
> File "", line 922, in create_module
> File "", line 219, in _call_with_frames_removed
> ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/bin/deepspeech", line 7, in
> from deepspeech.client import main
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/**init**.py", line 4, in
> from deepspeech.impl import AudioToInputVector as audioToInputVector
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 17, in
> _impl = swig_import_helper()
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/site-packages/deepspeech/impl.py", line 16, in swig_import_helper
> return importlib.import_module('_impl')
> File "/home/santhosh_3.6/DeepSpeech/$/home/santhosh_3.6/virtualenvironment/lib/python3.6/importlib/**init**.py", line 126, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named '_impl'
> (virtualenvironment) [santhosh_3.6@ip DeepSpeech]$

Looks like some old system. Can you describe more your setup ?

**Comment by lissyx** [comment]
@santhoshkurnapally Please ?
