### ISSUE TITLE
Error about def ctc_label_dense_to_sparse(labels, label_lengths, batch_size) in Util.text

### ISSUE THREAD

**Issue by 040840308** [mozilla/DeepSpeech#1855]
Hi, everyone

     I tried to run DeepSpeech on tensorflow 1.12.0 with python3.5.  I want to extract the CTC logits from a a target phrase using the ctc_label_dense_to_sparse function.
    However, I encountered an error as follows:
     Traceback (most recent call last):
  File "make_checkpoint.py", line 259, in <module>
    target = ctc_label_dense_to_sparse(target_phrase, target_phrase_lengths, 1)
  File "DeepSpeech/util/text.py", line 191, in ctc_label_dense_to_sparse
    dense_mask = tf.scan(range_less_than, label_lengths, initializer=init, parallel_iterations=1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 684, in scan
    maximum_iterations=n)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3274, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2994, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2966, in _BuildLoop
    next_vars.append(_AddNextAndBackEdge(m, v))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 667, in _AddNextAndBackEdge
    _EnforceShapeInvariant(m, v)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 611, in _EnforceShapeInvariant
    (input_t.name, input_t.shape, n_shape))
ValueError: Input tensor 'ExpandDims:0' enters the loop with shape (1, 42), but has shape (1, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

     Did someone encounter similar error? I will appreciate any advice.
     Thanks

**Comment by reuben** [comment]
It looks like you're misunderstanding the purpose of that function. It's used on the input side to convert a dense batch created by a `tf.PaddingFIFOQueue` into a `tf.SparseTensor`. On the output side, you can just fetch the logits directly and extract the sequences with the known sequence lengths, no need to convert them into a sparse tensor.

**Comment by 040840308** [comment]
OK, I indeed don't know how to use this. I just referred  to a code from the github [https://github.com/carlini/audio_adversarial_examples/blob/master/attack.py](url) (lines 132).  The code originally worked on tensorflow 1.8.0. I want to run it on tensorflow 1.12.0. However, I encountered the errors above.

Do you know how to solve this? @

**Comment by reuben** [comment]
You should probably ask the author of that code :)

Our use of `ctc_label_dense_to_sparse` is still working fine on 1.12.0.

**Comment by reuben** [comment]
We recently removed that function in favor of `tf.contrib.layers.dense_to_sparse`. f3613da82ae7c7439d2674460a0f671e9848fb22
