### ISSUE TITLE
float: zero division error while doing Transfer Learning on custom data...

### ISSUE THREAD

**Issue by ashupednekar** [mozilla/DeepSpeech#1869]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: NO
- **TensorFlow version (use command below)**: 1.12
- **Python version**:  Python 3.6.5
- **Bazel version (if compiling from source)**: NO
- **GCC/Compiler version (if compiling from source)**: NO
- **CUDA/cuDNN version**: CUDA 9.0
- **GPU model and memory**: Nvidia Tesla K80 - 12 GB RAM
- **Exact command to reproduce**:

```{python}
python -u DeepSpeech.py \
  --train_files /home/ubuntu/ashu/bbuddy-training/train/train.csv \
  --dev_files /home/ubuntu/ashu/bbuddy-training/dev/dev.csv \
  --test_files /home/ubuntu/ashu/bbuddy-training/test/test.csv \
  --train_batch_size 64 \
  --dev_batch_size 64 \
  --test_batch_size 64 \
  --n_hidden 2048 \
  --epoch -3 \
  --validation_step 1 \
  --learning_rate 0.00001\
  --report_count 100 \
  --use_seq_length False \
  --export_dir /home/ubuntu/ashu/bbuddy-training/results/model_export/ \
  --checkpoint_dir /home/ubuntu/ashu/bbuddy-training/results/deepspeech-0.4.1-checkpoint  \
  --decoder_library_path /home/ubuntu/ashu/bbuddy-training/libdeepspeech.so  \
  --alphabet_config_path /home/ubuntu/ashu/bbuddy-training/alphaMoz.txt \
  --lm_binary_path /home/ubuntu/ashu/DeepSpeech/data/lm/lm.binary \
  --lm_trie_path /home/ubuntu/ashu/DeepSpeech/data/lm/trie\
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

I'm trying to do transfer learning over custom data. I'm using deepspeech/data/lm language binary and generating trie using the native_client 0.5 alpha generate_trie to generate the trie.
The training occurs successfully, but <strong> the decoding step is skipped, as you can see in the logs, </strong>, which is what I think causes the zero division error.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

```
Preprocessing done
I STARTING Optimization
I Training epoch 112698...
I Training of Epoch 112698 - loss: 18.857928                                                                                                                                                 
100% (2 of 2) |########################################################################################################################################| Elapsed Time: 0:00:05 Time:  0:00:05
I Validating epoch 112698...
I Validation of Epoch 112698 - loss: 42.214298                                                                                                                                               
100% (1 of 1) |########################################################################################################################################| Elapsed Time: 0:00:04 Time:  0:00:04
I Training epoch 112699...
I Training of Epoch 112699 - loss: 18.706853                                                                                                                                                 
100% (2 of 2) |########################################################################################################################################| Elapsed Time: 0:00:05 Time:  0:00:05
I Validating epoch 112699...
I Validation of Epoch 112699 - loss: 41.838558                                                                                                                                               
100% (1 of 1) |########################################################################################################################################| Elapsed Time: 0:00:04 Time:  0:00:04
I Training epoch 112700...
I Training of Epoch 112700 - loss: 18.856285                                                                                                                                                 
100% (2 of 2) |########################################################################################################################################| Elapsed Time: 0:00:05 Time:  0:00:05
I Validating epoch 112700...
I Validation of Epoch 112700 - loss: 43.966053                                                                                                                                               
I FINISHED Optimization - training time: 0:00:28
100% (1 of 1) |########################################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
Preprocessing ['/home/ubuntu/ashu/bbuddy-training/test/test.csv']
Preprocessing done
Computing acoustic model predictions...
- |#                                                                                                                                                                | 0 Elapsed Time: 0:00:00
Decoding predictions...
- |#                                                                                                                                                                | 0 Elapsed Time: 0:00:00
Traceback (most recent call last):
  File "DeepSpeech.py", line 941, in <module>
    tf.app.run(main)
  File "/home/ubuntu/.virtualenvs/training/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 897, in main
    test()
  File "DeepSpeech.py", line 658, in test
    evaluate.evaluate(test_data, graph)
  File "/home/ubuntu/ashu/DeepSpeech/evaluate.py", line 189, in evaluate
    wer, cer, samples = calculate_report(ground_truths, predictions, distances, losses)
  File "/home/ubuntu/ashu/DeepSpeech/evaluate.py", line 70, in calculate_report
    samples_wer, samples_cer = wer_cer_batch(labels, decodings)
  File "/home/ubuntu/ashu/DeepSpeech/util/text.py", line 91, in wer_cer_batch
    return total_wer / total_word_length, total_cer / total_char_length
ZeroDivisionError: float division by zero
```

![screenshot from 2019-02-08 12-01-29](https://user-images.githubusercontent.com/25405037/52463138-cebe1600-2b9b-11e9-97a8-2d024bb97a3b.png)

**Comment by kdavis-mozilla** [comment]
@ashupednekar Could you post a link to the `test.csv` file?

**Comment by ashupednekar** [comment]
Sure.. This  is just a sample data,... so the file's small enough to be pasted here.
```
wav_filename,wav_filesize,transcript
available benefits of smart account_en-GB_Giorgio.wav,65742,available benefits of smart account
need info on available benefits of ISIC Student account_en-GB-WLS_Joanna.wav,103758,need info on available benefits of isic student account
can you talk about profit rate of banoon Childrens account_en-US_Karl.wav,119886,can you talk about profit rate of banoon childrens account
show me profit rate of banoon children account_en-GB-WLS_Seoyeon.wav,101454,show me profit rate of banoon children account
free debit isic student account_en-IN_Kimberly.wav,62286,free debit isic student account
benefits isic student account_en-GB-WLS_Zhiyu.wav,81870,benefits isic student account
what are the account products of your bank_en-GB-WLS_Vitoria.wav,104910,what are the account products of your bank
how can i change my savings account to a jointaccount_en-US_Matthew.wav,89934,how can i change my savings account to a jointaccount
i am looking for benefits of isic student account_en-GB_Ivy.wav,89934,i am looking for benefits of isic student account
tell me about profit rate of short term investment account_en-AU_Aditi.wav,117582,tell me about profit rate of short term investment account
```

**Comment by reuben** [comment]
The error means the length of the transcripts in your test data add up to zero, which doesn't make much sense given the test data you shared. Try printing the value of `originals` and `results` in `wer_cer_batch` to understand what's going on.

**Comment by lissyx** [comment]
>   --decoder_library_path /home/ubuntu/ashu/bbuddy-training/libdeepspeech.so  \

This make no sense, `--decoder-library-path` is not being used anymore, instead you need to install the `ds_ctcdecoder` python module.

**Comment by AmeerHamzaRiaz** [comment]
I'm also facing the same issue. This is my test csv.



wav_filename | wav_filesize | transcript
-- | -- | --
/home/fyp128/account/cropped/1553229903792_9_Female_18-25_Sindhi.wav | 96078 | mere account me kitna balance hai
/home/fyp128/account/cropped/1553230310067_2_Female_18-25_Sindhi.wav | 99918 | mere account me kitna balance hai

**Comment by lissyx** [comment]
> I'm also facing the same issue. This is my test csv.

Can you ensure your alphabet properly covers your dataset ?

**Comment by lissyx** [comment]
Lack of reply, nothing we can do.
