### ISSUE TITLE
OSE Error with common voice importer

### ISSUE THREAD

**Issue by mi4467** [mozilla/DeepSpeech#1885]
When I try and run the common voice importer while in the DeepSpeech folder, i.e this command: 

`bin/import_cv.py path/to/target/directory`

I get the following:

`Found archive "/home/mustafafirfan/DeepSpeech/path/to/target/directory/cv_corpus_v1.tar.gz" - not do
wnloading.
Found directory "/home/mustafafirfan/DeepSpeech/path/to/target/directory/cv_corpus_v1" - not extract
ing it from archive.
No CSV file "/home/mustafafirfan/DeepSpeech/path/to/target/directory/cv-valid-test.csv" - importing 
"/home/mustafafirfan/DeepSpeech/path/to/target/directory/cv_corpus_v1/cv-valid-test.csv"...
Importing mp3 files...
Traceback (most recent call last):
  File "bin/import_cv.py", line 124, in <module>
    _download_and_preprocess_data(sys.argv[1])
  File "bin/import_cv.py", line 39, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "bin/import_cv.py", line 54, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1
]))
  File "bin/import_cv.py", line 97, in _maybe_convert_set
    for i, _ in enumerate(pool.imap_unordered(one_sample, samples), start=1):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "bin/import_cv.py", line 79, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "bin/import_cv.py", line 121, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/home/mustafafirfan/tmp/deepspeech-venv/lib/python3.5/site-packages/sox/transform.py", line 
412, in build
    file_info.validate_input_file(input_filepath)
  File "/home/mustafafirfan/tmp/deepspeech-venv/lib/python3.5/site-packages/sox/file_info.py", line 
215, in validate_input_file
    "input_filepath {} does not exist.".format(input_filepath)
OSError: input_filepath /home/mustafafirfan/DeepSpeech/path/to/target/directory/cv_corpus_v1/cv-vali
d-test/sample-000001.mp3 does not exist.`

I'm confused as to what could be happening.

**Comment by kdavis-mozilla** [comment]
`path/to/target/directory` is meant to be a placeholder for the directory you want to target. It is not meant to be used as the actual target directory. You need to create and use your own target directory.

**Comment by lissyx** [comment]
Closing for lack of activity, as it seems to be a non-issue.
