### ISSUE TITLE
Can't upload deepspeech-gpu-0.5.0a4.tgz to npm

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1970]
`npm publish` triggers some code that tries to `toString()` the `tgz` file, and it hits limitations in the NodeJS buffer: https://github.com/npm/npm-registry-client/blob/14efa6848ca1e7278de0eb12a1430cdb85bddf02/lib/publish.js#L103

https://tools.taskcluster.net/groups/brZLYYp-QwC2djoDw_a1Gg/tasks/VCU-kUTOQt-1Rd4LZsg5Ag/runs/2/logs/public%2Flogs%2Flive_backing.log#L113

```
npm verb stack Error: toString failed
npm verb stack     at Buffer.toString (buffer.js:456:11)
npm verb stack     at CachingRegistryClient.putFirst (/app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:97:23)
npm verb stack     at /app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:54:14
npm verb stack     at ConcatStream.<anonymous> (/app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/index.js:36:43)
npm verb stack     at emitNone (events.js:72:20)
npm verb stack     at ConcatStream.emit (events.js:166:7)
npm verb stack     at finishMaybe (/app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
npm verb stack     at endWritable (/app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
npm verb stack     at ConcatStream.Writable.end (/app/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
npm verb stack     at ReadStream.onend (_stream_readable.js:498:10)
npm verb cwd /app
npm ERR! Linux 4.4.0-1038-aws
npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "publish" "--verbose" "/tmp/work/PWAf_XusTySO-13W6Ev_-Q/deepspeech-gpu-0.5.0-alpha.4.tgz" "--tag" "prerelease"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.12

npm ERR! toString failed
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

Currently, the `deepspeech-gpu-0.5.0a4.tgz` is 316MB.

We might:
 - split `deepspeech-gpu` into several subpackages: linux, windows
 - try to use `upx` (need some patching, this might be dangerous), we can get the `tgz` to 217MB
 - hand-upload, looking how it is done:
   - https://stackoverflow.com/questions/43543459/publishing-large-npm-packages
   - https://github.com/npm/npm-registry-client/blob/14efa6848ca1e7278de0eb12a1430cdb85bddf02/lib/publish.js#L60-L137

**Comment by lissyx** [comment]
We could also reduce the number of CUDA compute compatibilities we provide. I could measure that going from a 508MB `libdeepspeech.so` with the current list to 192MB by limiting to compute 3.5. Then, we can also use selective registration in tensorflow. With CUDA deps and runtime builtin (I need to get proper registration of the kernels), I'm around 138MB `libdeepspeech.so` for a compute 3.5 coverage.

**Comment by lissyx** [comment]
For now we will just stick to CUDA compute compatibility 3.5, all the testing I could perform reveal it works with no noticeable perf regression

**Comment by lissyx** [comment]
So, resulting `deepspeech-gpu-0.5.0-alpha.4.tgz` is 75MB, will give us some more room
