### ISSUE TITLE
Get IndexError while training a german model

### ISSUE THREAD

**Issue by sebastianwanka** [mozilla/DeepSpeech#1978]
Hello, i am trying to train a german model with google colab and the german common voice dataset. After downloading and extracting the Common Voice dataset i used the `import_cv2.py` script for transforming the .tsv files to the .csv files and converting .mp3 files to .wav files. Afterwards i moved all the files to GDrive to use the google colab notebook with gpu runtime. When i run `!python ./DeepSpeech.py --train_files ../corpus/clips/train.csv --dev_files ../corpus/clips/dev.csv --test_files ../corpus/clips/test.csv --epoch 1` (for testing purposes I have set `--epoch 1`) i get the following error: 

```
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Preprocessing ['../corpus/clips/train.csv']
Preprocessing done
Preprocessing ['../corpus/clips/dev.csv']
Preprocessing done
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py:696: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
W Parameter --validation_step needs to be >0 for early stopping to work
I STARTING Optimization
I Training epoch 0...
I Training of Epoch 0 - loss: 152.766590
I FINISHED Optimization - training time: 0:36:54
100% (2627 of 2627) |#####################| Elapsed Time: 0:36:52 Time:  0:36:52
Preprocessing ['../corpus/clips/test.csv']
Preprocessing done
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Computing acoustic model predictions...
100% (2267 of 2267) |#####################| Elapsed Time: 0:08:30 Time:  0:08:30
Decoding predictions...
 67% (1540 of 2267) |##############       | Elapsed Time: 0:22:32 ETA:   0:09:21Traceback (most recent call last):
  File "./DeepSpeech.py", line 934, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 890, in main
    test()
  File "./DeepSpeech.py", line 656, in test
    evaluate.evaluate(test_data, graph)
  File "/content/gdrive/My Drive/deepspeech/DeepSpeech/evaluate.py", line 150, in evaluate
    ground_truths.extend(Config.alphabet.decode(l) for l in batch['transcript'])
  File "/content/gdrive/My Drive/deepspeech/DeepSpeech/evaluate.py", line 150, in <genexpr>
    ground_truths.extend(Config.alphabet.decode(l) for l in batch['transcript'])
  File "/content/gdrive/My Drive/deepspeech/DeepSpeech/util/text.py", line 41, in decode
    res += self.string_from_label(label)
  File "/content/gdrive/My Drive/deepspeech/DeepSpeech/util/text.py", line 27, in string_from_label
    return self._label_to_str[label]
IndexError: list index out of range
```
The 1540 entry in the test.csv looks quite normal. 

Any idea whats the problem here?

**Comment by reuben** [comment]
Looks like the test data has a character that is not in your alphabet.txt file. Take a look at `util/check_characters.py` and check if your alphabet file has all the characters needed.

**Comment by sebastianwanka** [comment]
After generating the alphabet.txt with `util/check_characters.py` it worked. Thank you very much!
