### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by ashupednekar** [mozilla/DeepSpeech#1990]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04 LTS
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip 
- **TensorFlow version (use command below)**: 1.12
- **Python version**: 3.6.7
- **Bazel version (if compiling from source)**: NO
- **GCC/Compiler version (if compiling from source)**: NO
- **CUDA/cuDNN version**: 9.0 / 7.4
- **GPU model and memory**: Tesla K80 | 12 GB
- **Exact command to reproduce**: 
```
python -u DeepSpeech.py \
  --train_files /home/ubuntu/fri/train/train.csv \
  --dev_files /home/ubuntu/fri/dev/dev.csv \
  --test_files /home/ubuntu/test/test.csv \
  --train_batch_size 80 \
  --dev_batch_size 80 \
  --test_batch_size 40 \
  --n_hidden 375 \
  --epoch 33 \
  --validation_step 1 \
  --early_stop True \
  --earlystop_nsteps 6 \
  --estop_mean_thresh 0.1 \
  --estop_std_thresh 0.1 \
  --dropout_rate 0.22 \
  --learning_rate 0.00095 \
  --report_count 100 \
  --use_seq_length False \
  --export_dir /home/ubuntu/fri/results/model_export/ \
  --checkpoint_dir /home/ubuntu/fri/checkout/ \
  --decoder_library_path /home/ubuntu/fri/DeepSpeech/libdeepspeech.so \
  --alphabet_config_path /home/ubuntu/fri/DeepSpeech/data/alphabet.txt \
  --lm_binary_path /home/ubuntu/fri/DeepSpeech/data/lm/lm.binary \
  --lm_trie_path /home/ubuntu/fri/DeepSpeech/data/lm/trie \
  "$@"
```

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

Please describe the problem clearly. Be sure to convey here why it's a bug or a feature request.

Include any logs or source code that would be helpful to diagnose the problem. For larger logs, link to a Gist, not a screenshot. If including tracebacks, please include the full traceback. Try to provide a reproducible test case.

I used the source code from DeepSpeech-0.5.0-alpha.1 release. 
My dataset is  a custom dataset I created with 5-6 minute audio each, derived from coursera videos. 
As for the language model, and checkpoints, I get them from Deepspeech releases. I want to continue training from the checkpoints. PLEASE HELP

**Comment by ashupednekar** [comment]
Here's my stack trace: - 
```
(friday) ubuntu@ip-172-31-27-16:~/fri/DeepSpeech$ sh run.sh 
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py --train_files /home/ubuntu/fri/train/train.csv --dev_files /home/ubuntu/fri/dev/dev.csv --test_files /home/ubuntu/test/test.csv --train_batch_size 80 --dev_batch_size 80 --test_batch_size 40 --n_hidden 375 --epoch 33 --validation_step 1 --early_stop True --earlystop_nsteps 6 --estop_mean_thresh 0.1 --estop_std_thresh 0.1 --dropout_rate 0.22 --learning_rate 0.00095 --report_count 100 --use_seq_length False --export_dir /home/ubuntu/fri/results/model_export/ --checkpoint_dir /home/ubuntu/fri/checkout/ --decoder_library_path /home/ubuntu/fri/DeepSpeech/libdeepspeech.so --alphabet_config_path /home/ubuntu/fri/DeepSpeech/data/alphabet.txt --lm_binary_path /home/ubuntu/fri/DeepSpeech/data/lm/lm.binary --lm_trie_path /home/ubuntu/fri/DeepSpeech/data/lm/trie
Preprocessing ['/home/ubuntu/fri/train/train.csv']
Traceback (most recent call last):
  File "DeepSpeech.py", line 941, in <module>
    tf.app.run(main)
  File "/home/ubuntu/.virtualenvs/friday/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 893, in main
    train()
  File "DeepSpeech.py", line 388, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/home/ubuntu/fri/DeepSpeech/util/preprocess.py", line 69, in preprocess
    out_data = pmap(step_fn, source_data.iterrows())
  File "/home/ubuntu/fri/DeepSpeech/util/preprocess.py", line 13, in pmap
    results = pool.map(fun, iterable)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/fri/DeepSpeech/util/preprocess.py", line 21, in process_single_file
    features = audiofile_to_input_vector(file.wav_filename, numcep, numcontext)
  File "/home/ubuntu/fri/DeepSpeech/util/audio.py", line 18, in audiofile_to_input_vector
    features = mfcc(audio, samplerate=fs, numcep=numcep, winlen=0.032, winstep=0.02, winfunc=np.hamming)
  File "/home/ubuntu/.virtualenvs/friday/lib/python3.6/site-packages/python_speech_features/base.py", line 28, in mfcc
    feat,energy = fbank(signal,samplerate,winlen,winstep,nfilt,nfft,lowfreq,highfreq,preemph,winfunc)
  File "/home/ubuntu/.virtualenvs/friday/lib/python3.6/site-packages/python_speech_features/base.py", line 54, in fbank
    signal = sigproc.preemphasis(signal,preemph)
  File "/home/ubuntu/.virtualenvs/friday/lib/python3.6/site-packages/python_speech_features/sigproc.py", line 118, in preemphasis
    return numpy.append(signal[0],signal[1:]-coeff*signal[:-1])
IndexError: index 0 is out of bounds for axis 0 with size 0

```

**Comment by reuben** [comment]
Looks like your training set has an empty file, or a proper WAV file but with zero samples.

-- reuben

**Comment by Sushantmkarande** [comment]
i have this error too. did you find solution..

**Comment by lissyx** [comment]
@ashupednekar @Sushantmkarande As suggested above, you need to investigate broken data in your dataset.

**Comment by Sushantmkarande** [comment]
my problem was that I was missing ' character in alphabet.txt

**Comment by lissyx** [comment]
> my problem was that I was missing ' character in alphabet.txt

Thanks for confirming it's not an issue in our codebase then. The error is a bit unsual for this kind of mistake, though. I'm closing this :)
