### ISSUE TITLE
Impossible to export from a checkpoint without additional training?

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#2050]
Looking at the code of DeepSpeech.py, it seems like it should be possible to specify only `--checkpoint_dir` and `--export_dir` in order to convert the existing 0.4.1 pre-trained model to the new model format for 0.5, without doing any additional training.

However, I get the following error:

```
Exporting the model...
2019-04-13 19:33:20.834054: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key layer_1/bias not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key layer_1/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1276, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key layer_1/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at DeepSpeech.py:704) ]]

Caused by op 'save/RestoreV2', defined at:
  File "DeepSpeech.py", line 863, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 855, in main
    export()
  File "DeepSpeech.py", line 704, in export
    saver = tf.train.Saver(mapping)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key layer_1/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at DeepSpeech.py:704) ]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1591, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 863, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 855, in main
    export()
  File "DeepSpeech.py", line 751, in export
    frozen_graph = do_graph_freeze(output_node_names=output_names, variables_blacklist='previous_state_c,previous_state_h')
  File "DeepSpeech.py", line 746, in do_graph_freeze
    initializer_nodes='')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/tools/freeze_graph.py", line 151, in freeze_graph_with_def_protos
    saver.restore(sess, input_checkpoint)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 1292, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key layer_1/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at DeepSpeech.py:704) ]]

Caused by op 'save/RestoreV2', defined at:
  File "DeepSpeech.py", line 863, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 855, in main
    export()
  File "DeepSpeech.py", line 704, in export
    saver = tf.train.Saver(mapping)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 513, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key layer_1/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at DeepSpeech.py:704) ]]
```

The contents of the `mapping` variable used for the saver in `export()` is as follows:

```
layer_1/bias <tf.Variable 'layer_1/bias:0' shape=(2048,) dtype=float32_ref>
layer_1/weights <tf.Variable 'layer_1/weights:0' shape=(494, 2048) dtype=float32_ref>
layer_2/bias <tf.Variable 'layer_2/bias:0' shape=(2048,) dtype=float32_ref>
layer_2/weights <tf.Variable 'layer_2/weights:0' shape=(2048, 2048) dtype=float32_ref>
layer_3/bias <tf.Variable 'layer_3/bias:0' shape=(2048,) dtype=float32_ref>
layer_3/weights <tf.Variable 'layer_3/weights:0' shape=(2048, 2048) dtype=float32_ref>
lstm_fused_cell/kernel <tf.Variable 'lstm_fused_cell/kernel:0' shape=(4096, 8192) dtype=float32_ref>
lstm_fused_cell/bias <tf.Variable 'lstm_fused_cell/bias:0' shape=(8192,) dtype=float32_ref>
layer_5/bias <tf.Variable 'layer_5/bias:0' shape=(2048,) dtype=float32_ref>
layer_5/weights <tf.Variable 'layer_5/weights:0' shape=(2048, 2048) dtype=float32_ref>
layer_6/bias <tf.Variable 'layer_6/bias:0' shape=(29,) dtype=float32_ref>
layer_6/weights <tf.Variable 'layer_6/weights:0' shape=(2048, 29) dtype=float32_ref>

```

And here's what I get when I pass the checkpoint through Tensorflow's inspect_checkpoint tool:

```
b1 (DT_FLOAT) [2048]
b1/Adam (DT_FLOAT) [2048]
b1/Adam_1 (DT_FLOAT) [2048]
b2 (DT_FLOAT) [2048]
b2/Adam (DT_FLOAT) [2048]
b2/Adam_1 (DT_FLOAT) [2048]
b3 (DT_FLOAT) [2048]
b3/Adam (DT_FLOAT) [2048]
b3/Adam_1 (DT_FLOAT) [2048]
b5 (DT_FLOAT) [2048]
b5/Adam (DT_FLOAT) [2048]
b5/Adam_1 (DT_FLOAT) [2048]
b6 (DT_FLOAT) [29]
b6/Adam (DT_FLOAT) [29]
b6/Adam_1 (DT_FLOAT) [29]
beta1_power (DT_FLOAT) []
beta2_power (DT_FLOAT) []
global_step (DT_INT32) []
h1 (DT_FLOAT) [494,2048]
h1/Adam (DT_FLOAT) [494,2048]
h1/Adam_1 (DT_FLOAT) [494,2048]
h2 (DT_FLOAT) [2048,2048]
h2/Adam (DT_FLOAT) [2048,2048]
h2/Adam_1 (DT_FLOAT) [2048,2048]
h3 (DT_FLOAT) [2048,2048]
h3/Adam (DT_FLOAT) [2048,2048]
h3/Adam_1 (DT_FLOAT) [2048,2048]
h5 (DT_FLOAT) [2048,2048]
h5/Adam (DT_FLOAT) [2048,2048]
h5/Adam_1 (DT_FLOAT) [2048,2048]
h6 (DT_FLOAT) [2048,29]
h6/Adam (DT_FLOAT) [2048,29]
h6/Adam_1 (DT_FLOAT) [2048,29]
lstm_fused_cell/bias (DT_FLOAT) [8192]
lstm_fused_cell/bias/Adam (DT_FLOAT) [8192]
lstm_fused_cell/bias/Adam_1 (DT_FLOAT) [8192]
lstm_fused_cell/kernel (DT_FLOAT) [4096,8192]
lstm_fused_cell/kernel/Adam (DT_FLOAT) [4096,8192]
lstm_fused_cell/kernel/Adam_1 (DT_FLOAT) [4096,8192]
```

It therefore seems that the `layer_1/bias` variable was not embedded in the 0.4.1 checkpoint. 

I have also noticed that the data returned from the `create_inference_graph()` call at the top of `export()` is empty and am not sure if this is intended or not, as it occurs before the checkpoint is loaded.

```
input Tensor("input_node:0", shape=(1, 16, 19, 26), dtype=float32)
input_lengths Tensor("input_lengths:0", shape=(1,), dtype=int32)
input_samples Tensor("input_samples:0", shape=(512,), dtype=float32)

outputs Tensor("logits:0", shape=(16, 1, 29), dtype=float32)
initialize_state name: "initialize_state"
op: "NoOp"
input: "^Assign"
input: "^Assign_1"
device: "/device:CPU:0"

mfccs Tensor("mfccs:0", shape=(1, 26), dtype=float32)
```

`create_inference_graph()` calls `create_model()` which appears to setup some of the layer information, which would explain why it can't find that info if the inputs/outputs variables are empty.

So it seems to me that while it is possible to completely skip the `train()` and `test()` steps, DeepSpeech is setup to assume those steps have already taken place, in which case it would appear it is impossible to convert the model format without supplying additional training data.

(I am using the latest version of the code on master, by the way.)

**Comment by lissyx** [comment]
Can you try with - - notrain - - notest? It usually worked pretty well

**Comment by dabinat** [comment]
Nope, still the same error. I noticed in the commit history that the train/test options were recently removed and training / testing is now controlled by whether or not the user has specified the --train_files or --test_files arguments.

**Comment by reuben** [comment]
`--notrain`, `--nodev` and `--notest` were removed in favor of just checking if `{train,dev,test}_files` were specified. You're misunderstanding the problem here, it's not that it's failing because it's trying to train first. The training and export graph are independent, the export graph is built from scratch every time, regardless if you trained or not during the run. The problem here is that some of the variables were renamed between 0.4.1 and master, so it's trying to load the variables from checkpoint and not finding them there. Specifying a custom mapping to the Saver object to map the old names to the new ones should let you export.

**Comment by reuben** [comment]
Take a look at the existing mapping logic we have to load LSTMFusedCell variables into a normal LSTMCell.

**Comment by we-b-fox** [comment]
I had a similar problem - my model was created with an four-months old version of deepspeech, re-exporting with recent version failed due to name changes of some variables. Specifically, changes from bx and hx to layer_x/bias and layer_x/weights.

Making some changes on DeepSpeech.py, function dense(...), running it for re-exporting on that old checkpoint just solved the issue for me. Below is my code, maybe it helps you.

```
def dense(name, x, units, dropout_rate=None, relu=True):
    #BEGIN change
    #with tf.variable_scope(name):
    new_name_1 = 'bias'
    new_name_2 = 'weights'
    try:
        var = int(name[-1])  #Checking whether the scope 'name' is of form layer_<int>
        new_name_1 = 'b' + str(var)
        new_name_2 = 'h' + str(var)
    except:
        new_name_1 = 'bias'
        new_name_2 = 'weights'
    bias = variable_on_cpu(new_name_1, [units], tf.zeros_initializer())
    weights = variable_on_cpu(new_name_2, [x.shape[-1], units], tf.contrib.layers.xavier_initializer())
    #END change

    output = tf.nn.bias_add(tf.matmul(x, weights), bias)

    if relu:
        output = tf.minimum(tf.nn.relu(output), FLAGS.relu_clip)

    if dropout_rate is not None:
        output = tf.nn.dropout(output, rate=dropout_rate)

    return output
```

**Comment by reuben** [comment]
Responded in the Discourse thread: https://discourse.mozilla.org/t/upgrading-pre-trained-model-to-version-1/38220/3?u=reuben
