### ISSUE TITLE
ImportError: No module named '_impl'

### ISSUE THREAD

**Issue by egeres** [mozilla/DeepSpeech#2094]
- **OS Platform and Distribution**: Windows10
- **TensorFlow installed from**: upstream TensorFlow
- **TensorFlow version**: 1.10.0
- **Python version**: 3.5
- **CUDA/cuDNN version**: V9.0.176 / 7.1
- **GPU model and memory**: NVIDIA GeForce GTX 980M
- **Exact command to reproduce**: 
```
deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio my_audio.wav
```
After executing the command, I get this error :
```
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\deepspeech\impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "c:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python35\Scripts\deepspeech.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\deepspeech\__init__.py", line 14, in <module>
    from deepspeech.impl import PrintVersions as printVersions
  File "c:\python35\lib\site-packages\deepspeech\impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "c:\python35\lib\site-packages\deepspeech\impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "c:\python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
```

The solutions in these issues doesn't seem to work for my device (https://github.com/mozilla/DeepSpeech/issues/1666, https://github.com/mozilla/DeepSpeech/issues/1655) as I have reinstalled CUDA v9.0 with cuDNN

**Comment by lissyx** [comment]
> * **TensorFlow installed from**: upstream TensorFlow
> 
> * **TensorFlow version**: 1.10.0
> 
> * **Python version**: 3.5
> 
> * **CUDA/cuDNN version**: V9.0.176 / 7.1

That's inconsistent. Can you describe your installation steps ? Only versions of Python bindings on Windows are TensorFlow r1.13 based, so you need CUDA 10.0

**Comment by lissyx** [comment]
It looks like #2002 removed that information, I've added it back: https://github.com/mozilla/DeepSpeech/blob/c1816d6dfc80b8f9ab13cbb94e4e79dce3cf17f5/README.md#cuda-dependency

Please ensure you have proper CUDA and CUDNN versions. I'm closing this, feel free to reopen if it's not working properly after you made sure you use CUDA 10.0 and CUDNN 7.5.
