### ISSUE TITLE
Generate binary deepspeech | python bindings for v0.5 of deepspeech

### ISSUE THREAD

**Issue by illi88** [mozilla/DeepSpeech#2099]
I trained my model with the last release of deepspeech v0.5 which does not contain the python package, whereas the stable version of deepspeech 0.4 that is installed by pip contains the python package, how can I generate the deepspeech binary for use in the training version
I need this for streaming deepspeech with websocket
--------------------------------
 python server.py --model ../model/output_graph.pbmm --alphabet ../model/alphabets.txt --lm ../model/lm.binary --trie ../model_scenario/darija_lm/trie 
Initializing model...
2019-05-06 AM 11:12:23.370: __main__: INFO: <module>(): ARGS.model: ../model/output_graph.pbmm
2019-05-06 AM 11:12:23.370: __main__: INFO: <module>(): ARGS.alphabet: ../model/alphabets.txt
TensorFlow: v1.12.0-10-ge232881
DeepSpeech: v0.4.1-0-g0e40db6
2019-05-06 11:12:23.378355: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Not found: Op type not registered 'AudioSpectrogram' in binary running. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "server.py", line 60, in <module>
    model = deepspeech.Model(ARGS.model, N_FEATURES, N_CONTEXT, ARGS.alphabet, BEAM_WIDTH)
  File "/home/user/.local/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5

**Comment by lissyx** [comment]
@illi88 You can install them: https://pypi.org/project/deepspeech/0.5.0a7/

**Comment by illi88** [comment]
@lissyx thank you for your quick answer, it's worked
