### ISSUE TITLE
Python deepspeech bindings still looking for CUDA 9 when dependencies are CUDA 10

### ISSUE THREAD

**Issue by akhilvasvani** [mozilla/DeepSpeech#2104]
Hi, sorry to ask a silly question, but I think I have a similar problem to someone from before, but they never explained how they got an answer. I'm getting the 'can't find libcusolver.so.90' error. I have CUDA 10 installed , not CUDA 9, in accordance with the dependencies: https://github.com/mozilla/DeepSpeech#cuda-dependency . I installed the python bindings via 'pip3 install deepspeech-gpu'.

```$ deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio sample-audio/me.wav 

Traceback (most recent call last):
  File "/home/avas/.local/lib/python3.6/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libcusolver.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avas/.local/bin/deepspeech", line 7, in <module>
    from deepspeech.client import main
  File "/home/avas/.local/lib/python3.6/site-packages/deepspeech/__init__.py", line 4, in <module>
    from deepspeech.impl import AudioToInputVector as audioToInputVector
  File "/home/avas/.local/lib/python3.6/site-packages/deepspeech/impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "/home/avas/.local/lib/python3.6/site-packages/deepspeech/impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_impl' ```

My system: ubuntu 18.04, cuda 10, cudnn 7.4.1, tensorflow-gpu 1.13.1, deepspeech 0.4.1 on a GTX 1080. The libcusolver.so.9.0 file doesn't exist on my system, do I need to have cuda 9 installed alongside cuda 10 in some way? Or some library pointer from cuda9 requirements to the cuda10? 

``` $ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h" ```

``` $ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130 ```

Thanks in advance!

**Comment by kdavis-mozilla** [comment]
The call...
```bash
pip3 install deepspeech-gpu
```
installs Deep Speech 0.4.1.

The [0.4.1 documentation](https://github.com/mozilla/DeepSpeech/tree/v0.4.1#cuda-dependency), not the [master documentation](https://github.com/mozilla/deepspeech#cuda-dependency), indicates the following CUDA dependency
> Currently with TensorFlow r1.12 it depends on CUDA 9.0 and CuDNN v7.2.

**Comment by akhilvasvani** [comment]
Thank you for the quick response. Oh that makes sense, I read the master documentation and not the 0.4.1 documentation. How would be able to download the latest deepspeech-gpu for TensorFlow r.1.13, CUDA 10.0, and CuDNN v7.4.1?

Note: my GTX Ti 1080 will not let me use CUDA 9.0.  

Would the call be ``` pip3 install deepspeech-gpu-0.4.2```? Or should I clone the latest deepspeech repo, train the model locally, and then run it so I can use CUDA 10.0 and CuDNN 7.4.1? 

I apologize if my questions are stupid. I am new to running models on the GPU and implementing CUDA

**Comment by lissyx** [comment]
> How would be able to download the latest deepspeech-gpu for TensorFlow r.1.13, CUDA 10.0, and CuDNN v7.4.1?

Just `pip install --upgrade deepspeech-gpu==0.5.0a7`

But we don't yet have checkpoints nor official models for 0.5.0.

**Comment by akhilvasvani** [comment]
Ok, thank you. I'll check back in when you have the checkpoints and official models for 0.5.0
