### ISSUE TITLE
Error when training Common Voice - TypeError()

### ISSUE THREAD

**Issue by Thiago-Meyer** [mozilla/DeepSpeech#2110]
Have I written custom code (as opposed to running examples on an unmodified clone of the repository): No
    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7 Linux
    TensorFlow installed from (our builds, or upstream TensorFlow): from Pip
    TensorFlow version (use command below): tensorflow-gpu-13.01
    Python version: 3.6
    CUDA/cuDNN version: CUDA 10
    GPU model and memory: 2x NVIDIA Tesla V100 12Gb

So, I was going to start training in my computer, but when I ran the "./DeepSpeech.py" I recieved this msg:

```
> Traceback (most recent call last):
>   File "./DeepSpeech.py", line 829, in <module>
>     tf.app.run(main)
>   File "/home/robofeiathome/anaconda3/envs/dspeech/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "./DeepSpeech.py", line 813, in main
>     train()
>   File "./DeepSpeech.py", line 510, in train
>     train_loss, _ = run_set('train', epoch, train_init_op)
>   File "./DeepSpeech.py", line 473, in run_set
>     pbar = create_progressbar(prefix=prefix, widgets=widgets, suffix=suffix).start()
>   File "/home/robofeiathome/temp_download/DeepSpeech/util/logging.py", line 42, in create_progressbar
>     return progressbar.ProgressBar(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'prefix'
```

What is going on? I already tried to train once, it was going fine, but had to cancel. Now this error shows up when I try to train the model.

**Comment by Thiago-Meyer** [comment]
So, I had to uninstall progressbar, it looks like a random bug... now it's working like always.
