### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0]

### ISSUE THREAD

**Issue by AASHISHAG** [mozilla/DeepSpeech#2159]
DeepSpeech: Master (cloned today)
OS: Ubuntu 16.04.6 LTS
TensorFlow version: b'v1.13.1-0-g6612da8951' 1.13.1
GPU:  Quadro RTX 6000 * 3 (24GB each)

I have 3 sets of German speech data defined as per DeepSpeech format including Common-Voice in csv's. I have merged all these and now trying to create a random split of test, dev and train using below code. The code just random picks rows and splits into test and dev (15%)  each and train (70%). Attached is the sample train set generated. 
[train_50.zip](https://github.com/mozilla/DeepSpeech/files/3269964/train_50.zip)

```
file = pd.read_csv('all_tuda+voxforge+mozilla.csv')
random_subset = file.sample(frac=0.001)
train, validate, test = np.split(random_subset.sample(frac=1), [int(.7*len(random_subset)), int(.85*len(random_subset))])
print(int(random_subset.shape[0]))
train.to_csv('train_10_tuda+voxforge+mozilla.csv', encoding='utf-8', index=False)
validate.to_csv('validate_10_tuda+voxforge+mozilla.csv', encoding='utf-8', index=False)
test.to_csv('/test_10_tuda+voxforge+mozilla.csv', encoding='utf-8', index=False)
```

When I further run the DeepSpeech, I get the below error. 

```
(env) agarwal:~/DeepSpeech$ ./DeepSpeech.py --train_files ../german-speech-corpus/data_tuda+voxforge+mozilla/train_70.csv --dev_files ../german-speech-corpus/data_tuda+voxforge+mozilla/validate_15.csv --test_files ../german-speech-corpus/data_tuda+voxforge+mozilla/test_15.csv --alphabet_config_path ../deepspeech-german/data/alphabet.txt --lm_trie_path ../dataset-german/trie --lm_binary_path ../dataset-german/lm.binary --test_batch_size 48 --train_batch_size 48 --dev_batch_size 48 --epochs 2 --learning_rate 0.0001 --dropout_rate 0.30 --export_dir ../models
WARNING:tensorflow:From /home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/data/ops/dataset_ops.py:429: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.

WARNING:tensorflow:From /home/LTLab.lan/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/data/ops/iterator_ops.py:358: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/LTLab.lan/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/contrib/rnn/python/ops/lstm_ops.py:696: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /home/LTLab.lan/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I Restored variables from most recent checkpoint at /home/agarwal/.local/share/deepspeech/checkpoints/train-6063, step 6063
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:10 | Steps: 5 | Loss: 7.782564                                                                                               Traceback (most recent call last):
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/LTLab.lan/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0]
         [[{{node SerializeSparse}}]]
         [[{{node tower_1/IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./DeepSpeech.py", line 829, in <module>
    tf.app.run(main)
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./DeepSpeech.py", line 813, in main
    train()
  File "./DeepSpeech.py", line 510, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "./DeepSpeech.py", line 483, in run_set
    feed_dict=feed_dict)
  File "/home/LTLab.lan/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/agarwal/python-environments/env/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0]
         [[{{node SerializeSparse}}]]
         [[node tower_1/IteratorGetNext (defined at ./DeepSpeech.py:183) ]]
```

Also, when I create splits using above code on just one sample of data, then training works fine without any interruption. I understand the three datasets (Tuda-De, Vorforge, Common-Voice) are of different nature. Can we just create random splits on these datasets? or it has to be in sequenrial order? Like first only Tuda-de samples, the Voxforge and then Common Voice? I suspect so because the training with single dataset has no error but only when I combine them it shows issue.

I have verified that none of the file are corrupted and all the file paths are correct. Any advice?

**Comment by reuben** [comment]
Seems like some of the data is broken. Double check that you're actually using the files you're generating, as in the snippet you posted here you generate files ending in `_10.csv` but then in the training run log you pass files ending in `_70.csv` and `_15.csv`. You're also genearting the test CSV in a completely different folder. Make sure none of the splits are empty, and that all the audio files are valid WAVs and have duration > 0.

**Comment by AASHISHAG** [comment]
@reuben : Sorry for the confusion. The code had wrong file name mentioned. But I have verified none of the file is broken and splits are not empty. 

But since the splits are from 3 different datasets, the WAV's are not same size. They vary randomly. But the individual datasets are works well. It's just that they are now in random sequence with different lengths. Please have a look the generated sample. 
[train_50.zip](https://github.com/mozilla/DeepSpeech/files/3269969/train_50.zip) and advice.

**Comment by AASHISHAG** [comment]
Closing the issue, since it was more related to the way (i.e. code) I splitted the data. I worked it out later with shell scripts. If anyone later finds a correct way to split the data using Python, please advice.
