### ISSUE TITLE
commonvoice import script appears to rely on a dependency which is not installed by the installation process

### ISSUE THREAD

**Issue by ftyers** [mozilla/DeepSpeech#2188]
I'm trying to set up DeepSpeech to work with the Tatar data from common voice. I managed to install/compile the code following the instructions, but when I try and use the python script to import data from CommonVoice I get an import error with  `libcublas.so.9.0`.

```
ftyers@mwanafunzi:~/source/DeepSpeech$ bin/import_cv2.py --filter_alphabet data/alphabet_tt.txt data/
Traceback (most recent call last):
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/import_cv2.py", line 30, in <module>
    from util.feeding import secs_to_hours
  File "/home/ftyers/source/DeepSpeech/bin/../util/feeding.py", line 10, in <module>
    import tensorflow as tf
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ftyers/tmp/deepspeech-venv/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by reuben** [comment]
This looks like you installed `tensorflow-gpu` in a system that doesn't have CUDA installed. The error being about CUDA 9 also indicates it's an older version of TF. Try uninstalling `tensorflow-gpu` and installing `tensorflow`.

**Comment by ftyers** [comment]
I have CUDA and there is a GPU. 

```
ftyers@mwanafunzi:~$ find /usr | grep -i libcub
/usr/share/man/man7/libcublas.so.7
/usr/share/man/man7/libcublas.7
/usr/local/cuda-10.0/doc/man/man7/libcublas.so.7
/usr/local/cuda-10.0/doc/man/man7/libcublas.7
/usr/local/cuda-10.0/lib64/libcublas.so.10.0.130
/usr/local/cuda-10.0/lib64/stubs/libcublas.so
/usr/local/cuda-10.0/lib64/libcublas.so.10.0
/usr/local/cuda-10.0/lib64/libcublas.so
/usr/local/cuda-10.0/lib64/libcublas_static.a
```

**Comment by ftyers** [comment]
Solved the problem, I had `pip3 install 'tensorflow-gpu==1.6.0'` not `pip3 install 'tensorflow-gpu==1.13.1'`. I need to update my documentation :) Thanks!

**Comment by reuben** [comment]
:)
