### ISSUE TITLE
Training stopped after this error "tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0]"

### ISSUE THREAD

**Issue by testdeepv** [mozilla/DeepSpeech#2237]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: mozilla builds
- **TensorFlow version (use command below)**: 1.13
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: 0.19.2
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.0
- **GPU model and memory**: Tesla P100

Training stopped after this error in validation steps : 

File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0]
         [[{{node SerializeSparse}}]]
         [[{{node tower_0/IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 830, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 814, in main
    train()
  File "DeepSpeech.py", line 521, in train
    set_loss, steps = run_set('dev', epoch, init_op, dataset=csv)
  File "DeepSpeech.py", line 484, in run_set
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input indices should be a matrix but received shape [0

Any suggestions to debug ?

**Comment by lissyx** [comment]
@testdeepv it's usually a probem in your dataset

**Comment by testdeepv** [comment]
the error appeares in the validation steps on dev.csv, does this mean that the problem is with dev.csv ??
How can I debug this ? I checked all wav file, they are all not empty.

**Comment by lissyx** [comment]
@testdeepv yes it's likely a bogus wav or transcription in `dev.csv`. I can't give you a better advice than running a binary search on `dev.csv` to identify which records is problematic. We already got some reports with some wav file choking within tensorflow's codebase. We have not been able to find why.

**Comment by testdeepv** [comment]
Thank you for these details :) Can you please explain how can I run a binary search on a csv file ?

**Comment by lissyx** [comment]
I'm going to close this, since it's obivously a data-issue. Feel free to re-open if you happen to identify an issue code-wise.
