### ISSUE TITLE
multi gpu

### ISSUE THREAD

**Issue by sonfiree** [mozilla/DeepSpeech#2314]
How to enable multi gpu?
I have two RTX 2070s and only one of them works. More precisely, I can not start, out of memory.

 

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ununtu 18.04
- TensorFlow version (use command below): tensorflow v1.14.0
- Python version: python 3.6.8 
- CUDA/cuDNN version: CUDA 10.0
- GPU 2xRTX 2070

 
![Screenshot_106](https://user-images.githubusercontent.com/26105224/63492178-57662900-c4d2-11e9-98bc-67d403eeb0fc.png)

**Comment by kdavis-mozilla** [comment]
It should just work. Also, the screen shot you presented doesn't say anything about an out of memory error.

PS: Please do not include screen shots.

**Comment by sonfiree** [comment]
Incorrectly asked question.
How to limit memory consumption? `Batch_size` does not work correctly

**Comment by sonfiree** [comment]
```

Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                                                                                Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node tower_0/conv1d}}]]
         [[tower_1/gradients/tower_1/BiasAdd_4_grad/BiasAddGrad/_117]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node tower_0/conv1d}}]]
0 successful operations.
1 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./DeepSpeech.py", line 894, in <module>
    tfv1.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./DeepSpeech.py", line 878, in main
    train()
  File "./DeepSpeech.py", line 599, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "./DeepSpeech.py", line 567, in run_set
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node tower_0/conv1d (defined at ./DeepSpeech.py:57) ]]
         [[tower_1/gradients/tower_1/BiasAdd_4_grad/BiasAddGrad/_117]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node tower_0/conv1d (defined at ./DeepSpeech.py:57) ]]
0 successful operations.
1 derived errors ignored.

Original stack trace for 'tower_0/conv1d':
  File "./DeepSpeech.py", line 894, in <module>
    tfv1.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./DeepSpeech.py", line 878, in main
    train()
  File "./DeepSpeech.py", line 447, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "./DeepSpeech.py", line 298, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "./DeepSpeech.py", line 225, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse, rnn_impl=rnn_impl)
  File "./DeepSpeech.py", line 153, in create_model
    batch_x = create_overlapping_windows(batch_x)
  File "./DeepSpeech.py", line 57, in create_overlapping_windows
    batch_x = tf.nn.conv1d(batch_x, eye_filter, stride=1, padding='SAME')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 1624, in conv1d
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

```

**Comment by kdavis-mozilla** [comment]
Could you explicitly indicate what command line you ran?

**Comment by sonfiree** [comment]
> Could you explicitly indicate what command line you ran?

`./DeepSpeech.py --alphabet_config_path /home/rt/data/alphabet.txt --train_files /home/rt/data/clips/train.csv --dev_files /home/rt/data/clips/dev.csv --test_files /home/rt/data/clips/test.csv --train_batch_size 2 --dev_batch_size 2 --test_batch_size 2
`

**Comment by sonfiree** [comment]
I usually limit it like that

```
gpu_options = tf.GPUOptions (per_process_gpu_memory_fraction = 0.8)
sess = tf.Session (config = tf.ConfigProto (gpu_options = gpu_options))
```

**Comment by kdavis-mozilla** [comment]
This is unrelated to batch size and unrelated to multi gpu.

What version of TF and cuDNN do you have installed?

**Comment by sonfiree** [comment]
```
TF 1.14.0
Cuda compilation tools, release 10.0, V10.0.130

```

**Comment by sonfiree** [comment]
Im used docker TF `tensorflow/tensorflow:latest-gpu-py3-jupyter`

**Comment by lissyx** [comment]
> tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
>   (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

That error is documented: https://github.com/mozilla/DeepSpeech/blob/master/README.md#recommendations

**Comment by sonfiree** [comment]
> > tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
> > (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> 
> That error is documented: https://github.com/mozilla/DeepSpeech/blob/master/README.md#recommendations

And where to change it in the code? I do not understand you

**Comment by lissyx** [comment]
> And where to change it in the code? I do not understand you

You need to set that in the environment of your process.

**Comment by lissyx** [comment]
With Docker, it's likely `-e ...=...`

**Comment by sonfiree** [comment]
> With Docker, it's likely `-e ...=...`

`-e TF_FORCE_GPU_ALLOW_GROWTH=true`
It`s work. Thx
