### ISSUE TITLE
Failed to call ThenRnnBackward with model config

### ISSUE THREAD

**Issue by vcjob** [mozilla/DeepSpeech#2326]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**:only flags and Deepspeech.py a bit.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Linux Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**:1.14 gpu
- **Python version**: 3.6.8
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:10.0
- **GPU model and memory**:rtx2080ti
- **Exact command to reproduce**:

Hello everyone!
I tryed to augment my data (it was originally around 250 hours os speech, I made it 3 times bigger by adding randomly noise, changing tempo, pitch.
So what I end up with is the error (logs are below) saying _Failed to call ThenRnnBackward with model config_. It happens as far as I noticed right at the end of the 1st epoch (or somewhere near). It didn't happen before I augmenter the data. Batch size is 32, n_hidden = 2048. One epoch takes more than an hour. The logs I recorded with standart linux _script_. Btw, I tryed to start training with test dataset (which is significantly smaller: 2k vs 384k wavs), and no such error occured. 
Is it something with one of the files? How to determen with wich one than?

_(deepspeech2) root@neuro:/opt/deepspeech2/DeepSpeech#python3 DeepSpeech.py
W0827 18:13:28.653597 140030271993664 deprecation_wrapper.py:119] From /opt/deepspeech2/DeepSpeech/util/config.py:60: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0827 18:14:28.624799 140030271993664 deprecation.py:323] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

W0827 18:14:28.671362 140030271993664 deprecation.py:323] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0827 18:14:28.671538 140030271993664 deprecation.py:323] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0827 18:14:28.671698 140030271993664 deprecation.py:323] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0827 18:14:47.911377 140030271993664 deprecation.py:506] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:342: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0827 18:14:47.911542 140030271993664 deprecation.py:506] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0827 18:14:47.911677 140030271993664 deprecation.py:506] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py:345: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0827 18:14:48.146306 140030271993664 deprecation.py:323] From DeepSpeech.py:231: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0827 18:14:48.421419 140030271993664 deprecation.py:323] From /opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py:193: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
I Initializing variables...
I STARTING Optimization
^M                                                                                                                                                                                           ^M^MEpoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                                   ^M                                                          $
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size]: [1, 2048, 2048, 1, 1753, 32]
         [[{{node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3}}]]
         [[tower_0/gradients/tower_0/BiasAdd_2_grad/BiasAddGrad/_77]]
  (1) Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size]: [1, 2048, 2048, 1, 1753, 32]
         [[{{node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 898, in <module>
    tfv1.app.run(main)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/deepspeech2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/deepspeech2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/deepspeech2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 882, in main
    train()
  File "DeepSpeech.py", line 599, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech.py", line 567, in run_set
    feed_dict=feed_dict)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size]: [1, 2048, 2048, 1, 1753, 32]
         [[node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3 (defined at DeepSpeech.py:307) ]]
         [[tower_0/gradients/tower_0/BiasAdd_2_grad/BiasAddGrad/_77]]
  (1) Internal: Failed to call ThenRnnBackward with model config: [rnn_mode, rnn_input_mode, rnn_direction_mode]: 2, 0, 0 , [num_layers, input_size, num_units, dir_count, max_seq_length, batch_size]: [1, 2048, 2048, 1, 1753, 32]
         [[node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3 (defined at DeepSpeech.py:307) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3:
 tower_0/Reshape_2 (defined at DeepSpeech.py:172)
 tower_0/cudnn_lstm/zeros (defined at /tmp/tmpsktd4qey.py:71)
 tower_0/IteratorGetNext (defined at DeepSpeech.py:217)
 tower_0/cudnn_lstm/CudnnRNNV3 (defined at /tmp/tmpsktd4qey.py:112)
 tower_0/IteratorGetNext (defined at DeepSpeech.py:217)
 tower_0/cudnn_lstm/CudnnRNNV3 (defined at /tmp/tmpsktd4qey.py:112)
 cudnn_lstm/opaque_kernel/read (defined at DeepSpeech.py:115)

Input Source operations connected to node tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3:
 tower_0/Reshape_2 (defined at DeepSpeech.py:172)
 tower_0/cudnn_lstm/zeros (defined at /tmp/tmpsktd4qey.py:71)
 tower_0/IteratorGetNext (defined at DeepSpeech.py:217)
 tower_0/cudnn_lstm/CudnnRNNV3 (defined at /tmp/tmpsktd4qey.py:112)
 cudnn_lstm/opaque_kernel/read (defined at DeepSpeech.py:115)

Original stack trace for 'tower_0/gradients/tower_0/cudnn_lstm/CudnnRNNV3_grad/CudnnRNNBackpropV3':
  File "DeepSpeech.py", line 898, in <module>
    tfv1.app.run(main)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/deepspeech2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/opt/deepspeech2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 882, in main
    train()
  File "DeepSpeech.py", line 447, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "DeepSpeech.py", line 307, in get_tower_results
    gradients = optimizer.compute_gradients(avg_loss)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 403, in _MaybeCompile
    return grad_fn()  # Exit early
 File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 403, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/cudnn_rnn_grad.py", line 103, in _cudnn_rnn_backwardv3
    direction=op.get_attr("direction")) + (None,)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 741, in cudnn_rnn_backprop_v3
    time_major=time_major, name=name)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

tower_0...which was originally created as op 'tower_0/cudnn_lstm/CudnnRNNV3', defined at:
  File "DeepSpeech.py", line 898, in <module>
    tfv1.app.run(main)
[elided 4 identical lines from previous traceback]
  File "DeepSpeech.py", line 447, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "DeepSpeech.py", line 298, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "DeepSpeech.py", line 225, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse, rnn_impl=rnn_impl)
  File "DeepSpeech.py", line 176, in create_model
    output, output_state = rnn_impl(layer_3, seq_length, previous_state, reuse)
  File "DeepSpeech.py", line 115, in rnn_impl_cudnn_rnn
    sequence_lengths=seq_length)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/tmpsktd4qey.py", line 112, in tf__call
    outputs, (output_h, output_c) = ag__.converted_call('_forward', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, h, c, self.kernel, sequence_lengths, time_major, training), None)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "/opt/deepspeech2/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/layers/cudnn_rnn.py", line 518, in _forward
    seed=self._seed)_

**Comment by reuben** [comment]
You're running out of GPU memory. Probably your augmentation process introduced longer audio files (hence why the problem happens at the end of the epoch, we sort samples by length). Either remove samples that are too long from your dataset or reduce your batch size.
