### ISSUE TITLE
Cannot install deepspeech version 0.5.1

### ISSUE THREAD

**Issue by HowieYang0** [mozilla/DeepSpeech#2336]
====== system information ========
- no custom code:
- raspbian (raspberry pi 4):
- TensorFlow installed with Deepspeech (when installed with deepspeech.0.6.0-alpha):
- TensorFlow version (v1.14.0):
- python version 3.7.3: 
- CUDA/cuDNN version = unknown:
- GPU model and memory: Broadcom VideoCore VI
- exact command: 
`$pip3 install -verbose deepspeech==0.5.1 > pip3_log.txt
`

I downloaded the deepspeech.0.5.1 pre-trained model so I was looking for the matching binary version. However, when I use: pip3 install deepspeech, I got deepspeech version 0.6.0-alpha5 (successfully). How am I be able to install the earlier 0.5.1 version? Or, if a pre-trained 0.6.0 model is available, it will be okay for my situation. 
Thanks!

Error messages:
`Could not find a version that satisfies the requirement deepspeech==0.5.1 (from version 0.6.0a5)`
`pip._internal.exceptions.DistributionNotFound: No matching distribution found for deepspeech==0.5.1
`

Here it is the log:
[pip3_log.txt](https://github.com/mozilla/DeepSpeech/files/3567398/pip3_log.txt)

highlight of the error log:
Removed build tracker '/tmp/pip-req-tracker-ta5wzmkg'
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req

pip._internal.exceptions.DistributionNotFound: No matching distribution found for deepspeech==0.5.1

**Comment by reuben** [comment]
I don't think v0.5.1 had support for the RPi4. You can get a version of the v0.5.1 model re-exported to be compatible with the v0.6.0 alphas at https://github.com/reuben/DeepSpeech/releases/v0.6.0-alpha.4

**Comment by lissyx** [comment]
Yeah, the issue is that I have not yet made Python 3.7 packages, see #2272
