### ISSUE TITLE
deepspeech latest release (v0.6.0-alpha.5), still not compatible with CUDA-10.1 version.

### ISSUE THREAD

**Issue by jageshmaharjan** [mozilla/DeepSpeech#2342]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:
- **TensorFlow version (use command below)**: 1.14.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 7.4.0
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: GTX 1060 (6gb)
- **Exact command to reproduce**: `deepspeech --version`

So, i updated the CUDA version 10.1, also I updated the deepspeech release version to v0.6.0-alpha.5.

In general, it's not compatible. Here's the exact to replicate the error.

```
Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib/libcudart.so.10.0: version `libcudart.so.10.0' not found (required by /home/jugs/anaconda3/envs/myenv/lib/python3.6/site-packages/deepspeech/lib/libdeepspeech.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugs/anaconda3/envs/myenv/bin/deepspeech", line 6, in <module>
    from deepspeech.client import main
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/site-packages/deepspeech/__init__.py", line 14, in <module>
    from deepspeech.impl import PrintVersions as printVersions
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/site-packages/deepspeech/impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/site-packages/deepspeech/impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "/home/jugs/anaconda3/envs/myenv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_impl'
```

[Discourse link](https://discourse.mozilla.org/t/deepspeech-latest-release-v0-6-0-alpha-5-still-not-compatible-with-cuda-10-1-version/44639)

**Comment by lissyx** [comment]
That's expected, and documented. Upstream supports 10.0, and se document that.

**Comment by jageshmaharjan** [comment]
Yea, saw that. Thanks.

**Comment by lissyx** [comment]
> Yea, saw that. Thanks.

I think that 10.1 has some incompatibilities wrt eigen's use by tensorflow, so I'm not sure you can even build it by yourself, but you can try?

**Comment by jageshmaharjan** [comment]
Since, `libdeepspeech.so` depends on these `libcudart.so.10.0, libcublas.so.10, libcusolver.so.10.0` libraries from cuda, will check those cuda lib in previous version, and try to build.

**Comment by lissyx** [comment]
> Since, `libdeepspeech.so` depends on these `libcudart.so.10.0, libcublas.so.10, libcusolver.so.10.0` libraries from cuda, will check those cuda lib in previous version, and try to build.

Those are the CUDA 10.0 dependencies, so if you setup CUDA 10.0, it should work. Also, try to avoid anaconda.

**Comment by jageshmaharjan** [comment]
Yea, those are CUDA 10.0 libraries, for CUDA 10.1 (in my case), it is `libcudart.so.10.1, libcublas.so.10.1, libcusolver.so.10.1`.
Ok, I'll try without conda environment, because most of the lib is a system lib, that doesn't exist in conda env.
