### ISSUE TITLE
 Session failed to close after 30 seconds. Continuing after this point may leave your program in an undefined state.

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [mozilla/DeepSpeech#2376]
```
I Restored variables from most recent checkpoint at ./deepspeech-0.5.1-checkpoint/train-566724, step 566725
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 1:00:02 | Steps: 4552 | Loss: 8.355338                                                                                       W0922 14:29:08.304780 139890854811392 deprecation.py:323] From /usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
Epoch 0 |   Training | Elapsed Time: 21:12:11 | Steps: 49794 | Loss: 6.444828                                                                                     E0923 10:42:02.035050 139890854811392 session.py:1622] Session failed to close after 30 seconds. Continuing after this point may leave your program in an undefined state.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16410,2048] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node tower_0/dropout_3/GreaterEqual}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Mean/_73]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16410,2048] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node tower_0/dropout_3/GreaterEqual}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech_testing.py", line 853, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech_testing.py", line 837, in main
    train()
  File "DeepSpeech_testing.py", line 527, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "DeepSpeech_testing.py", line 494, in run_set
    feed_dict=feed_dict)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[16410,2048] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node tower_0/dropout_3/GreaterEqual (defined at DeepSpeech_testing.py:76) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Mean/_73]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[16410,2048] and type bool on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node tower_0/dropout_3/GreaterEqual (defined at DeepSpeech_testing.py:76) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node tower_0/dropout_3/GreaterEqual:
 dropout_5 (defined at DeepSpeech_testing.py:396)

Input Source operations connected to node tower_0/dropout_3/GreaterEqual:
 dropout_5 (defined at DeepSpeech_testing.py:396)

Original stack trace for 'tower_0/dropout_3/GreaterEqual':
  File "DeepSpeech_testing.py", line 853, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech_testing.py", line 837, in main
    train()
  File "DeepSpeech_testing.py", line 411, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "DeepSpeech_testing.py", line 261, in get_tower_results
    avg_loss,non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "DeepSpeech_testing.py", line 187, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse)
  File "DeepSpeech_testing.py", line 152, in create_model
    layers['layer_5'] = layer_5 = dense('layer_5', output, Config.n_hidden_5, dropout_rate=dropout[5])
  File "DeepSpeech_testing.py", line 76, in dense
    output = tf.nn.dropout(output, rate=dropout_rate)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 4170, in dropout
    return dropout_v2(x, rate, noise_shape=noise_shape, seed=seed, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 4254, in dropout_v2
    keep_mask = random_tensor >= rate
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 4271, in greater_equal
    "GreaterEqual", x=x, y=y, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by NarasimmanSaravana1994** [comment]
While during custom training I'm getting above mentioned error. Please any once explain what is the error and how to solve that. After that error, the training is automatically starting from first.

**Comment by lissyx** [comment]
@NarasimmanSaravana1994 You're getting `OOM`, this means you are exhausting your GPU memory. Without more context that your delebarately removed from the issue template, we cannot help you. Issues are for bugs, please ues Discourse for support.

**Comment by reuben** [comment]
Your system is running out of memory during training, from the looks of it at the end of the first epoch. We sort input samples by size, so the largest samples will be processed at the end of epochs. You should probably look if there are any unusually large samples and remove them, or if there aren't any, reduce your batch size.

-- reuben

**Comment by NarasimmanSaravana1994** [comment]
@lissyx @reuben  Thanks
