### ISSUE TITLE
ModuleNotFoundError: No module named '_impl'

### ISSUE THREAD

**Issue by Technerder** [mozilla/DeepSpeech#2412]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Raspbian Buster (Raspberry pi 4 b+ 4GB)
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: Included
- **TensorFlow version (use command below)**: N/A
- **Python version**: 3.7.3
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav

You can obtain the TensorFlow version with

```bash
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```

I ran the following commands in the README and was faced with this error:
```error
(deepspeech-venv) pi@raspberrypi:~ $ deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/impl.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: numpy.core.multiarray failed to import

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/bin/deepspeech", line 6, in <module>
    from deepspeech.client import main
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 17, in <module>
    from deepspeech.impl import PrintVersions as printVersions
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/impl.py", line 17, in <module>
    _impl = swig_import_helper()
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/impl.py", line 16, in swig_import_helper
    return importlib.import_module('_impl')
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_impl'
```

Command:
```commands
# Create and activate a virtualenv
virtualenv -p python3 $HOME/tmp/deepspeech-venv/
source $HOME/tmp/deepspeech-venv/bin/activate

# Install DeepSpeech
pip3 install deepspeech

# Download pre-trained English model and extract
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/deepspeech-0.5.1-models.tar.gz
tar xvf deepspeech-0.5.1-models.tar.gz

# Download example audio files
curl -LO https://github.com/mozilla/DeepSpeech/releases/download/v0.5.1/audio-0.5.1.tar.gz
tar xvf audio-0.5.1.tar.gz

# Transcribe an audio file
deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
```

**Comment by lissyx** [comment]
We have support for RPi4 since #2272, so you can't use `v0.5.1`, you have to use latest 0.6 alpha: `pip3 install deepspeech==0.6.0a8`: https://pypi.org/project/deepspeech/0.6.0a8/

**Comment by Technerder** [comment]
After installing 0.6.0a8 I am met with this issue:
```error
(deepspeech-venv) pi@raspberrypi:~ $ deepspeech --model deepspeech-0.5.1-models/output_graph.pbmm --alphabet deepspeech-0.5.1-models/alphabet.txt --lm deepspeech-0.5.1-models/lm.binary --trie deepspeech-0.5.1-models/trie --audio audio/2830-3980-0043.wav
Loading model from file deepspeech-0.5.1-models/output_graph.pbmm
TensorFlow: v1.14.0-16-g3b4ce37
DeepSpeech: v0.6.0-alpha.8-0-gf0e9541
ERROR: Model provided has model identifier '▒x;', should be 'TFL3'

Error at reading model file deepspeech-0.5.1-models/output_graph.pbmm
Traceback (most recent call last):
  File "/home/pi/tmp/deepspeech-venv/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, args.alphabet, BEAM_WIDTH)
  File "/home/pi/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 39, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 12288
```

**Comment by Technerder** [comment]
Requesting to have this issue re-opened @lissyx

**Comment by lissyx** [comment]
This is not a bug. Support should be done on discourse. Please read the documentation and the error : you cannot use 0.5.1 model with 0.6 binaries.
