### ISSUE TITLE
No such file or directory: 'sox'

### ISSUE THREAD

**Issue by maxima120** [mozilla/DeepSpeech#2436]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: 1.14
- **Python version**: 3.5
- **Exact command to reproduce**:
```
deepspeech --model models/output_graph.pbmm --alphabet models/alphabet.txt --lm models/lm.binary --trie models/trie --audio 30m.wav 
Loading model from file models/output_graph.pbmm
TensorFlow: v1.13.1-10-g3e0cc53
DeepSpeech: v0.5.1-0-g4b29b78
2019-10-14 17:07:07.047317: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-10-14 17:07:07.059136: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2019-10-14 17:07:07.059217: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2019-10-14 17:07:07.059228: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2019-10-14 17:07:07.059400: E tensorflow/core/framework/op_kernel.cc:1325] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
Loaded model in 0.103s.
Loading language model from files models/lm.binary models/trie
Loaded language model in 24.5s.
Warning: original sample rate (48000) is different than 16kHz. Resampling might produce erratic speech recognition.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/client.py", line 46, in convert_samplerate
    output = subprocess.check_output(shlex.split(sox_cmd), stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'sox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/deepspeech", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/client.py", line 103, in main
    fs, audio = convert_samplerate(args.audio)
  File "/usr/local/lib/python3.5/dist-packages/deepspeech/client.py", line 50, in convert_samplerate
    raise OSError(e.errno, 'SoX not found, use 16kHz files or install it: {}'.format(e.strerror))
FileNotFoundError: [Errno 2] SoX not found, use 16kHz files or install it: No such file or directory: 'sox'
```

this worked on a short file. But when I fed it 30 min wav it gave me the error above. Also - why would it try to resample?

Any suggestions?

**Comment by lissyx** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'sox'

As documented, you need to install the `sox` binary.



> Also - why would it try to resample?

The error is already stating: you are feeding 48kHz to a 16kHz model.
