### ISSUE TITLE
TypeError: CreateModel() missing required argument 'aAlphabetConfigPath' (pos 4)

### ISSUE THREAD

**Issue by devbas** [mozilla/DeepSpeech#2450]
- **Have I written custom code**: No
- **OS Platform and Distribution**: Mac OS 10.14.5
- **TensorFlow installed from**: pip
- **TensorFlow version**: 2.0.0
- **Python version**: 3.7.4
- **Bazel version**: N/A
- **GCC/Compiler version**: N/A
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

1) Run ```python3 audioTranscript_gui.py``` to start the vad_transcriber example GUI
2) Select a .wav file + model/alphabet/etc directory
3) Hit start
4) See the error show up in the logs

I am experiencing the same error within my personal code project as well. 

*Raw logs*
```audioTranscript_gui.py - initUI@169 root:DEBUG  Multithreading with maximum 8 threads
audioTranscript_gui.py - wav_activate@185 root:DEBUG  Enable wav transcription widgets
audioTranscript_gui.py - browse_on_click@196 root:DEBUG  Browse button clicked
objc[6870]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff97adf3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x129e5ef50). One of the two will be used. Which one is undefined.
audioTranscript_gui.py - browse_on_click@203 root:DEBUG  /Users/personal/Development/graph/transcript.wav
audioTranscript_gui.py - models_on_click@207 root:DEBUG  Models Browse Button clicked
audioTranscript_gui.py - models_on_click@211 root:DEBUG  /Users/personal/Development/graph/deepspeech-0.5.1-models
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x7fb01c067470), parent's thread is QThread(0x7fb019e05d00), current thread is QThread(0x7fb01d060060)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
wavTranscriber.py - resolve_models@68 root:DEBUG  Found Model: /Users/personal/Development/graph/deepspeech-0.5.1-models/output_graph.pb
wavTranscriber.py - resolve_models@71 root:DEBUG  Found Alphabet: /Users/personal/Development/graph/deepspeech-0.5.1-models/alphabet.txt
wavTranscriber.py - resolve_models@75 root:DEBUG  Found Language Model: /Users/personal/Development/graph/deepspeech-0.5.1-models/lm.binary
wavTranscriber.py - resolve_models@76 root:DEBUG  Found Trie: /Users/personal/Development/graph/deepspeech-0.5.1-models/trie
Traceback (most recent call last):
  File "audioTranscript_gui.py", line 243, in modelResult
    self.model = wavTranscriber.load_model(output_graph, alphabet, lm, trie)
  File "/Users/personal/Downloads/DeepSpeech-master/examples/vad_transcriber/wavTranscriber.py", line 24, in load_model
    ds = Model(models, alphabet, BEAM_WIDTH)
  File "/usr/local/lib/python3.7/site-packages/deepspeech/__init__.py", line 21, in __init__
    status, impl = deepspeech.impl.CreateModel(*args, **kwargs)
TypeError: CreateModel() missing required argument 'aAlphabetConfigPath' (pos 4)
[1]    6870 abort      python3 audioTranscript_gui.py
```

**Comment by lissyx** [comment]
@devbas Can you please document what version you are using ?

**Comment by lissyx** [comment]
@devbas Can you update us ?

**Comment by devbas** [comment]
Hi @lissyx, 

Sorry, testing took a while. Turned out I had the wrong deepspeech version hence this issue can be closed. Everything is working fine now.

**Comment by lissyx** [comment]
Thanks for the confirmation of the analysis :)
