### ISSUE TITLE
Error while training Common language Data

### ISSUE THREAD

**Issue by saravananselvamohan** [mozilla/DeepSpeech#2531]
----->>>By running **bin/import_cv2.py --filter_alphabet path/to/some/alphabet.txt /path/to/extracted/language/archive I got my respected .tsv files**
---->>>While running the command I am getting the error below
**./DeepSpeech.py --train_files ../data/CV/en/clips/train.csv --dev_files ../data/CV/en/clips/dev.csv --test_files ../data/CV/en/clips/test.csv**

**I am using Python 3**

Traceback (most recent call last):
  File "DeepSpeech.py", line 962, in <module>
    absl.app.run(main)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 935, in main
    train()
  File "DeepSpeech.py", line 435, in train
    train_phase=True)
  File "/root/DeepSpeech/util/feeding.py", line 98, in create_dataset
    df = read_csvs(csvs)
  File "/root/DeepSpeech/util/feeding.py", line 24, in read_csvs
    file = pandas.read_csv(csv, encoding='utf-8', na_filter=False)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/root/tmp/deepspeech-train-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 2059, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 881, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 896, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 950, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 937, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2132, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 12, saw 3

**Comment by lissyx** [comment]
@saravananselvamohan Posting the same error everywhere is not going to get your more attention, but it is irritating.

**Comment by saravananselvamohan** [comment]
> @saravananselvamohan Posting the same error everywhere is not going to get your more attention, but it is irritating

I just posted in both Mozilla Community and Github Issue Page bcoz I strucked and I don't know how to proceed forward. Suggestions from you made me to clear that error. Further if it has irrirtated, accept my sorry for that

**Comment by lissyx** [comment]
Well, we could help and use knowledge when people have issues with discourse. But if you just cross post and don't even care to mention that you have an issue with discourse we can't fix it and improve your experience
