### ISSUE TITLE
Cuda Configuration Error

### ISSUE THREAD

**Issue by bsshruthi22** [mozilla/DeepSpeech#2547]
While compiling native client,we got the below error.
cuda version: we installed cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64.deb,
but it shows as 10.2

```
 bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
ERROR: Skipping '//native_client:libdeepspeech.so': error loading package 'native_client': in /home/iiit_admin/.cache/bazel/_bazel_iiit_admin/4639ede5fd02934db9e17905c63c0e45/external/org_tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 1506
		_create_local_cuda_repository(repository_ctx)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 859, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 773, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s%s" % (bas...], ...)))
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, in find_lib
		auto_configure_fail(("None of the libraries match th...)))
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 341, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: None of the libraries match their SONAME: /usr/local/cuda-10.2/lib64/libcublas.so.10.2, /usr/local/cuda-10.2/lib64/stubs/libcublas.so.10.2
ERROR: error loading package 'native_client': in /home/iiit_admin/.cache/bazel/_bazel_iiit_admin/4639ede5fd02934db9e17905c63c0e45/external/org_tensorflow/tensorflow/tensorflow.bzl: Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 1506
		_create_local_cuda_repository(repository_ctx)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266, in _create_local_cuda_repository
		_find_libs(repository_ctx, cuda_config)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 859, in _find_libs
		_find_cuda_lib("cublas", repository_ctx, cpu_value, c..., ...)
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 773, in _find_cuda_lib
		find_lib(repository_ctx, [("%s/%s%s" % (bas...], ...)))
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 747, in find_lib
		auto_configure_fail(("None of the libraries match th...)))
	File "/home/iiit_admin/DeepSpeech-master/tensorflow/third_party/gpus/cuda_configure.bzl", line 341, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: None of the libraries match their SONAME: /usr/local/cuda-10.2/lib64/libcublas.so.10.2, /usr/local/cuda-10.2/lib64/stubs/libcublas.so.10.2
INFO: Elapsed time: 0.285s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: native_client
    Fetching @local_config_cuda; fetching

```
Please help us

**Comment by lissyx** [comment]
> cuda version: we installed cuda-repo-ubuntu1804-10-0-local-10.0.130-410.48_1.0-1_amd64.deb,
> but it shows as 10.2

Well, I'm sorry but you already diagnosed your issue, and this is obviously not a bug. Please use discourse for support.

Also, you don't share every repro step, so we cannot help you anyway.
