### ISSUE TITLE
Error installing ctcdecoder wheel for DS 0.4.1 in Docker environment

### ISSUE THREAD

**Issue by cli0** [mozilla/DeepSpeech#2716]
I am writing a Dockerfile that provides a custom nvidia/cuda environment to run DeepSpeech on. The installation steps I follow on the dockerfile are exactly the same I do on a real machine however I get a persistent error when I try to install the ctcdecoder for 0.4.1

```
Step 50/51 : RUN pip3 install DeepSpeech/native_client/ctcdecode/dist/*.whl --verbose
 ---> Running in 4f16896b38d4
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-es4tghj9
Created temporary directory: /tmp/pip-req-tracker-73r0045j
Initialized build tracking at /tmp/pip-req-tracker-73r0045j
Created build tracker: /tmp/pip-req-tracker-73r0045j
Entered build tracker: /tmp/pip-req-tracker-73r0045j
Created temporary directory: /tmp/pip-install-6kwgbvwl
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-73r0045j'
ERROR: ds_ctcdecoder-0.4.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 301, in run
    wheel_cache
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 252, in populate_requirement_set
    requirement_set.add_requirement(req_to_add)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_set.py", line 112, in add_requirement
    wheel.filename
pip._internal.exceptions.InstallationError: ds_ctcdecoder-0.4.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
The command '/bin/sh -c pip3 install DeepSpeech/native_client/ctcdecode/dist/*.whl --verbose' returned a non-zero code: 1
```

Overall parameters of the env:

OS: Ubuntu 18.04
Python3: 3.6.9
Bazel: 0.15.0
DeepSpeech: 0.4.1
Tensorflow-gpu: 1.12.0

The Dockerfile is the following:

```
FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y \
 build-essential \
 software-properties-common \
 curl \
 apt-utils \
 python \
 python-dev \
 python-pip \
 python3 \
 python3-dev \
 python3-pip \
 swig \
 unzip \
 sox \
 libsox-dev \
 python-pyaudio \
 git \
 wget \
 silversearcher-ag \
 ranger \
 ffmpeg \
 python3-levenshtein \
 python-numpy \
 libcurl3-dev  \
 ca-certificates \
 libsox-fmt-mp3 \
 htop \
 nano \
 cmake \
 zlib1g-dev \
 libbz2-dev \
 liblzma-dev \
 locales \
 pkg-config \
 libsox-dev \
 freeglut3-dev \
 libx11-dev \
 libxmu-dev \
 libxi-dev \
 libglu1-mesa \
 libglu1-mesa-dev \
 dpkg \
 gcc-6 \
 g++-6 \
 rxvt-unicode \ 
 module-init-tools

RUN DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration -y

WORKDIR /home/setup/

RUN wget https://github.com/bazelbuild/bazel/releases/download/0.15.0/bazel-0.15.0-installer-linux-x86_64.sh
RUN chmod +x bazel-0.15.0-installer-linux-x86_64.sh
RUN ./bazel-0.15.0-installer-linux-x86_64.sh
RUN rm bazel-0.15.0-installer-linux-x86_64.sh

# Install Python specific packages

RUN pip3 install --upgrade setuptools pip wheel

RUN pip3 install absl-py==0.9.0 \
astor==0.8.1 \
attrdict==2.0.1 \
audioread==2.1.8 \
cffi==1.13.2 \
cycler==0.10.0 \
Cython==0.29.14 \
decorator==4.4.1 \
deepspeech==0.4.1 \
gast==0.3.3 \
grpcio==1.26.0 \
h5py==2.10.0 \
joblib==0.14.1 \
Keras-Applications==1.0.8 \
Keras-Preprocessing==1.1.0 \
kiwisolver==1.1.0 \
librosa==0.7.2 \
llvmlite==0.31.0 \
Markdown==3.1.1 \
numba==0.47.0 \
numexpr==2.7.1 \
numpy==1.18.1 \
pandas \
progressbar==2.5 \
protobuf==3.11.2 \
pycparser==2.19 \
pydub==0.23.1 \
pyparsing==2.4.6 \
python-dateutil==2.8.1 \
python-Levenshtein==0.12.0 \
python-speech-features==0.6 \
pytz==2019.3 \
resampy==0.2.2 \
scikit-learn==0.22.1 \
scipy==1.4.1 \
six==1.14.0 \
SoundFile==0.10.3.post1 \
tensorboard==1.12 \
tensorflow-gpu==1.12.0 \
Werkzeug==0.16.0

## Install Nvidia Driver

ENV TERM xterm

RUN export TERM=xterm

RUN add-apt-repository ppa:graphics-drivers/ppa
RUN apt-get update
RUN apt-get install nvidia-384 nvidia-384-dev -y

RUN wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
RUN dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
RUN apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
RUN apt-get update
RUN apt-get install cuda -y

## Install cudnn

#cudnn requires login to get,so i externally stored this on the cloud
RUN wget https://www.dropbox.com/s/o0ffjf1j0bftrq9/cudnn-9.2-linux-x64-v7.2.1.38.tgz?dl=1 -O cudnn-9.2-linux-x64-v7.2.1.38.tgz
RUN tar -xzvf cudnn-9.2-linux-x64-v7.2.1.38.tgz
RUN cp -P cuda/include/cudnn.h /usr/local/cuda-9.0/include
RUN cp -P cuda/lib64/libcudnn* /usr/local/cuda-9.0/lib64/
RUN chmod a+r /usr/local/cuda-9.0/lib64/libcudnn*

RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.0/lib64/
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/
RUN export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}$ 
RUN export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

WORKDIR /home/workspace/

RUN git clone https://github.com/mozilla/DeepSpeech.git
RUN cd DeepSpeech && git checkout tags/v0.4.1

# Install TF and DeepSpeech

ENV TF_NEED_IGNITE=0

ENV TF_NEED_CUDA=1 \
 GCC_HOST_COMPILER_PATH=/usr/bin/gcc-6 \
# TF_CUDA_VERSION=9.0 \
# CUDA_TOOLKIT_PATH=/usr/local/cuda \
# TF_CUDNN_VERSION=7.2 \
# CUDNN_INSTALL_PATH=/usr/local/cuda \
 TF_CUDA_COMPUTE_CAPABILITIES=3.5 \
# CC_OPT_FLAGS="--copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --copt=-mfpmath=both --config=cuda" \
 PYTHON_BIN_PATH="/usr/bin/python" \
 USE_DEFAULT_PYTHON_LIB_PATH=1 \
 TF_NCCL_VERSION=1.3

RUN git clone https://github.com/mozilla/tensorflow.git
RUN cd tensorflow && git checkout r1.12 && ln -s ../DeepSpeech/native_client ./
RUN cd tensorflow && ./configure 
RUN cd tensorflow && bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie --config=cuda
RUN cd DeepSpeech/native_client && make deepspeech

RUN cd DeepSpeech/native_client/ctcdecode && make bindings NUM_PROCESSES=8
RUN cp tensorflow/bazel-bin/native_client/generate_trie DeepSpeech/native_client/
RUN cp tensorflow/bazel-bin/native_client/libdeepspeech.so DeepSpeech/native_client/
RUN pip3 install DeepSpeech/native_client/ctcdecode/dist/*.whl --verbose

ENTRYPOINT /bin/bash
```

**Comment by lissyx** [comment]
>  The installation steps I follow on the dockerfile are exactly the same I do on a real machine however I get a persistent error when I try to install the ctcdecoder for 0.4.1

This is not a bug. 0.4.1 is an old release, unsupported anymore and `ds_ctcdecoder` package is not installable anymore from prebuilts. 

Since you already rebuild things that are still available (why do you rebuild all of them ?) you should just rebuild the ctc decoder package.

**Comment by lissyx** [comment]
> RUN pip3 install DeepSpeech/native_client/ctcdecode/dist/*.whl --verbose
> [...]
> ERROR: ds_ctcdecoder-0.4.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.
> Exception information:

You build for Python 2.7 and install into Python 3.6, this can't work. Please use matching versions.

**Comment by lissyx** [comment]
> I am writing a Dockerfile that provides a custom nvidia/cuda environment to run DeepSpeech on

We already have a `Dockerfile` in the repo, why re-invent the wheel ? What is missing ?
