### ISSUE TITLE
Not found: deepspeech-0.6.1-models/output_graph.pbmm; No such file or directory

### ISSUE THREAD

**Issue by Young1993** [mozilla/DeepSpeech#2730]
Just run deepspeech --model deepspeech-0.6.1-models/output_graph.pbmm --lm deepspeech-0.6.1-models/lm.binary --trie deepspeech-0.6.1-models/trie --audio 8900297.mp3

the error just like this:
Loading model from file deepspeech-0.6.1-models/output_graph.pbmm
TensorFlow: v1.14.0-21-ge77504ac6b
DeepSpeech: v0.6.1-0-g3df20fe
Not found: deepspeech-0.6.1-models/output_graph.pbmm; No such file or directory
Traceback (most recent call last):
  File "/Users/xxx/tmp/deepspeech-venv/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/client.py", line 113, in main
    ds = Model(args.model, args.beam_width)
  File "/Users/xxx/tmp/deepspeech-venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 42, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 12288

**Comment by Young1993** [comment]
found the model uninstall
