### ISSUE TITLE
not able to install ctcdecoder

### ISSUE THREAD

**Issue by vigneshmj1997** [mozilla/DeepSpeech#2747]
on installing ctcdecoder iam getting error some thing like this 
```
ERROR: Command errored out with exit status 1:
     command: /home/local/vignesh/miniconda3/envs/ctc/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-67e35wiz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-67e35wiz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-67e35wiz/pip-egg-info
         cwd: /tmp/pip-req-build-67e35wiz/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-67e35wiz/setup.py", line 43, in <module>
        project_version = read('../../VERSION').strip()
      File "/tmp/pip-req-build-67e35wiz/setup.py", line 41, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-67e35wiz/../../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lissyx** [comment]
This looks weird. Can you explain what you do? How do you install it?

**Comment by lissyx** [comment]
@vigneshmj1997 Please document your installation steps that triggers this.

**Comment by vigneshmj1997** [comment]
pip install .

**Comment by lissyx** [comment]
> pip install .

That's not what we document. Please follow the documentation and `pip install $(python util/taskcluster.py --decoder)`.

**Comment by lissyx** [comment]
Please reach for support on Discourse, this is not a DeepSpeech bug.
