### ISSUE TITLE
How to test a trained model?

### ISSUE THREAD

**Issue by Juanvulcano** [mozilla/DeepSpeech#2799]
- **Have I written custom code **: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: tensorflow-gpu
- **TensorFlow version (use command below)**: v1.15.0-rc3-22-g590d6ee 1.15.0
- **Python version**: 3.6
- **CUDA/cuDNN version**: 10
- **GPU model and memory**: T4 NVIDIA

Hi,

I have an output_graph.pb after running the training. I want to be able to see the report with WER for each epoch. Similar to this issue: https://github.com/mozilla/DeepSpeech/issues/1343 
I tried using the util/evaluation.py but I am probably doing it wrong.

With evaluation.py:
`ubuntu@ip-172-31-30-60:~/OwnLanguage/DeepSpeech$ sudo python3 evaluate.py --test_files Spanska/clips/test.csv
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2020-02-27 14:11:50.281547: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-02-27 14:11:50.319361: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2020-02-27 14:11:50.319839: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4d8eff0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-02-27 14:11:50.319868: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-02-27 14:11:50.323449: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-02-27 14:11:50.443050: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-27 14:11:50.444331: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4e0e2a0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-02-27 14:11:50.444374: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-02-27 14:11:50.444676: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-27 14:11:50.445669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:1e.0
2020-02-27 14:11:50.445833: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.445927: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.445993: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.446065: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.446168: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.446245: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2020-02-27 14:11:50.451537: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-27 14:11:50.451665: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-02-27 14:11:50.451809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-27 14:11:50.451864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-27 14:11:50.451917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
Traceback (most recent call last):
  File "evaluate.py", line 156, in <module>
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "evaluate.py", line 147, in main
    samples = evaluate(FLAGS.test_files.split(','), create_model)
  File "evaluate.py", line 49, in evaluate
    FLAGS.scorer_path, Config.alphabet)
  File "/usr/local/lib/python3.6/dist-packages/ds_ctcdecoder/__init__.py", line 36, in __init__
    raise ValueError('Scorer initialization failed with error code {}'.format(err))
ValueError: Scorer initialization failed with error code 1`

What model is evaluation.py trying to use here? Is it the last one I trained?

So to print the WER of my trained model I was trying to find something like this:
```
  python3 DeepSpeech.py --train_batch_size 32 --n_hidden 1024 --dev_batch_size 32 --test_batch_size 32 --dropout_rate 0.1 --test_files Spanska/clips/test.csv--checkpoint_dir DtTranslator --audio_sample_rate 8000  --export_dir Spanska2
/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "DeepSpeech.py", line 900, in <module>
    absl.app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "DeepSpeech.py", line 877, in main
    test()
  File "DeepSpeech.py", line 635, in test
    samples = evaluate(FLAGS.test_files.split(','), create_model)
  File "/home/ubuntu/OwnLanguage/DeepSpeech/evaluate.py", line 49, in evaluate
    FLAGS.scorer_path, Config.alphabet)
  File "/usr/local/lib/python3.6/dist-packages/ds_ctcdecoder/__init__.py", line 36, in __init__
    raise ValueError('Scorer initialization failed with error code {}'.format(err))
ValueError: Scorer initialization failed with error code 1
```

It could also be that the NVIDIA T4 is not supported? or that I am missing a specific driver?

**Comment by lissyx** [comment]
>  Could not load dynamic library

Please properly setup CUDA.
