### ISSUE TITLE
Getting " positional arguments" error while training custom model

### ISSUE THREAD

**Issue by humayunzaee** [mozilla/DeepSpeech#2809]
We are getting the error  while executing the following command.

```
./DeepSpeech.py --utf8 --audio_sample_rate 8000  --export_dir ../output/ --checkpoint_
dir ../checkpoint/ --train_files ../DP-train.csv --dev_files ../DP-dev.csv --test_files ../DP-test.csv
 
version: r0.6.1
ERROR: 
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

W0305 00:43:01.836197 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
W0305 00:43:01.970148 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:348: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
W0305 00:43:01.977953 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:349: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
W0305 00:43:01.984816 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:351: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0305 00:43:02.325038 140565701723968 deprecation.py:506] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From ./DeepSpeech.py:236: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0305 00:43:02.958240 140565701723968 deprecation.py:323] From ./DeepSpeech.py:236: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0305 00:43:03.828574 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ../checkpoint/train-9
I0305 00:43:03.871741 140565701723968 saver.py:1280] Restoring parameters from ../checkpoint/train-9
I Restored variables from most recent checkpoint at ../checkpoint/train-9, step 9
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:02:18 | Steps: 1 | Loss: 356.852081
Epoch 0 | Validation | Elapsed Time: 0:00:04 | Steps: 1 | Loss: 350.557129 | Dataset: ../DP-dev.csv
I Saved new best validating model with loss 350.557129 to: ../checkpoint/best_dev-10
Epoch 1 |   Training | Elapsed Time: 0:02:17 | Steps: 1 | Loss: 351.085785
Epoch 1 | Validation | Elapsed Time: 0:00:04 | Steps: 1 | Loss: 359.561279 | Dataset: ../DP-dev.csv
Epoch 2 |   Training | Elapsed Time: 0:02:16 | Steps: 1 | Loss: 360.632324
Epoch 2 | Validation | Elapsed Time: 0:00:04 | Steps: 1 | Loss: 348.800934 | Dataset: ../DP-dev.csv
WARNING:tensorflow:From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
W0305 00:50:19.424391 140565701723968 deprecation.py:323] From /mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.
I Saved new best validating model with loss 348.800934 to: ../checkpoint/best_dev-12
I FINISHED optimization in 0:07:09.721991
Traceback (most recent call last):
  File "./DeepSpeech.py", line 974, in <module>
    absl.app.run(main)
  File "/mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/mnt/e/IBEX/SpecialProjects/deepspeech/dp_py36/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "./DeepSpeech.py", line 951, in main
    test()
  File "./DeepSpeech.py", line 684, in test
    samples = evaluate(FLAGS.test_files.split(','), create_model, try_loading)
  File "/mnt/e/IBEX/SpecialProjects/deepspeech/DeepSpeech/evaluate.py", line 48, in evaluate
    Config.alphabet)
TypeError: __init__() takes from 1 to 5 positional arguments but 6 were given
```

**Comment by lissyx** [comment]
Why `--utf8`?

**Comment by lissyx** [comment]
> version: r0.6.1

Are you sure about that ?

**Comment by lissyx** [comment]
>   File "/mnt/e/IBEX/SpecialProjects/deepspeech/DeepSpeech/evaluate.py", line 48, in evaluate
>     Config.alphabet)

@humayunzaee Could you share what commit is your `HEAD` and what version of `ds_ctcdecoder` is installed ?

**Comment by lissyx** [comment]
`pip list | grep ds_ctcdecoder`

**Comment by lissyx** [comment]
`v0.6.1` `Scorer.__init__()`: https://github.com/mozilla/DeepSpeech/blob/v0.6.1/native_client/ctcdecode/__init__.py#L19
`master` `Scorer.__init__()`: https://github.com/mozilla/DeepSpeech/blob/master/native_client/ctcdecode/__init__.py#L19

Number of argument does match your error: it's likely you are calling a post-0.6.1 `ds_ctcdecoder` using `v0.6.1` signature.

**Comment by humayunzaee** [comment]
--utf8? --because  by default its false  ,we want to use this mode ..is there something wrong ?
Could you share what commit is your HEAD and what version of ds_ctcdecoder is installed ?
git branch
  master
* r0.6.1

git rev-parse --short HEAD
3df20fee

**Comment by mysteryjeans** [comment]
> > version: r0.6.1
> 
> Are you sure about that ?

We just checkout this branch from v0.6.1

**Comment by lissyx** [comment]
> --utf8? --because by default its false ,we want to use this mode ..is there something wrong ?

Have you read what that flag does ?

> Could you share what commit is your HEAD and what version of ds_ctcdecoder is installed ?
> git branch
> master
> 
>     * r0.6.1
> 
> 
> git rev-parse --short HEAD
> [3df20fe](https://github.com/mozilla/DeepSpeech/commit/3df20fee52fda47d08e3726fd0da86dbb414e9d8)

You have not documented `ds_ctcdecoder` version.

**Comment by humayunzaee** [comment]
its 
pip list | grep ds-ctcdecoder
ds-ctcdecoder        0.7.0a2

**Comment by lissyx** [comment]
> Can we uninstall this version and install the 0.6.1 version of it independently

`pip uninstall ds_ctcdecoder` then follow the docs: `pip install $(python util/taskcluster.py --decoder)`
