### ISSUE TITLE
Fenerate Tflite model using existing checkpoints 

### ISSUE THREAD

**Issue by Angel3636** [mozilla/DeepSpeech#2858]
I am trying to generate the tflite model using existing chheckpoints, using following command:
python DeepSpeech.py --checkpoint_dir /temp/check_points/deepspeech-0.6.1-checkpoint --export_tflite  --export_dir /home/temp
My tensorflow version : 2.0.0

I am getting following error:

```
Traceback (most recent call last):
  File "DeepSpeech.py", line 30, in <module>
    from evaluate import evaluate
  File "/home/sagarjadhav/git/speech_to_text/DeepSpeech/evaluate.py", line 21, in <module>
    from util.feeding import create_dataset
  File "/home/sagarjadhav/git/speech_to_text/DeepSpeech/util/feeding.py", line 17, in <module>
    from util.spectrogram_augmentations import augment_freq_time_mask, augment_dropout, augment_pitch_and_tempo, augment_speed_up, augment_sparse_warp
  File "/home/sagarjadhav/git/speech_to_text/DeepSpeech/util/spectrogram_augmentations.py", line 3, in <module>
    from util.sparse_image_warp import sparse_image_warp
  File "/home/sagarjadhav/git/speech_to_text/DeepSpeech/util/sparse_image_warp.py", line 28, in <module>
    from tensorflow.contrib.image.python.ops import dense_image_warp
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 22, in <module>
    from tensorflow.contrib import bayesflow
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
    from tensorflow.contrib.bayesflow.python.ops import csiszar_divergence
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.csiszar_divergence_impl import *
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/bayesflow/python/ops/csiszar_divergence_impl.py", line 42, in <module>
    from tensorflow.contrib import framework as contrib_framework
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/framework/__init__.py", line 89, in <module>
    from tensorflow.contrib.framework.python.ops import *
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
    from tensorflow.contrib.framework.python.ops.checkpoint_ops import *
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 22, in <module>
    from tensorflow.contrib.framework.python.ops import gen_checkpoint_ops
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/gen_checkpoint_ops.py", line 248, in <module>
    _op_def_lib = _InitOpDefLibrary(b"\n\223\001\n\026GenerateVocabRemapping\022\022\n\016new_vocab_file\030\007\022\022\n\016old_vocab_file\030\007\032\r\n\tremapping\030\t\032\017\n\013num_present\030\003\"\031\n\020new_vocab_offset\022\003int(\001\"\026\n\rnum_new_vocab\022\003int(\001\n\335\001\n\022LoadAndRemapMatrix\022\r\n\tckpt_path\030\007\022\023\n\017old_tensor_name\030\007\022\021\n\rrow_remapping\030\t\022\021\n\rcol_remapping\030\t\022\027\n\023initializing_values\030\001\032\021\n\routput_matrix\030\001\"\021\n\010num_rows\022\003int(\001\"\023\n\010num_cols\022\003int(\0010\001\"&\n\022max_rows_in_memory\022\003int\032\013\030\377\377\377\377\377\377\377\377\377\001\210\001\001")
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/gen_checkpoint_ops.py", line 167, in _InitOpDefLibrary
    _op_def_registry.register_op_list(op_list)
  File "/home/sagarjadhav/anaconda3/envs/pytcharm/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_registry.py", line 38, in register_op_list
    % (op_def.name, _registered_ops[op_def.name], op_def))
ValueError: Registered op_def for GenerateVocabRemapping (name: "GenerateVocabRemapping"
input_arg {
  name: "new_vocab_file"
  type: DT_STRING
}
input_arg {
  name: "old_vocab_file"
  type: DT_STRING
}
output_arg {
  name: "remapping"
  type: DT_INT64
}
output_arg {
  name: "num_present"
  type: DT_INT32
}
attr {
  name: "new_vocab_offset"
  type: "int"
  has_minimum: true
}
attr {
  name: "num_new_vocab"
  type: "int"
  has_minimum: true
}
attr {
  name: "old_vocab_size"
  type: "int"
  default_value {
    i: -1
  }
  has_minimum: true
  minimum: -1
}
) not equal to op_def to register (name: "GenerateVocabRemapping"
input_arg {
  name: "new_vocab_file"
  type: DT_STRING
}
input_arg {
  name: "old_vocab_file"
  type: DT_STRING
}
output_arg {
  name: "remapping"
  type: DT_INT64
}
output_arg {
  name: "num_present"
  type: DT_INT32
}
attr {
  name: "new_vocab_offset"
  type: "int"
  has_minimum: true
}
attr {
  name: "num_new_vocab"
  type: "int"
  has_minimum: true
}
)
```

Can you please help me to resolve this issue, thank you in advance.

**Comment by lissyx** [comment]
> Can you please help me to resolve this issue, thank you in advance.

No. Next time, read carefully the issue template that you removed. Please use Discourse for support.



>  My tensorflow version : 2.0.0

You obviously have not read the documentation, since we require TensorFlow r1.15.
