### ISSUE TITLE
Running on Tensorflow 1.0.0

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#287]
```
$ ./bin/run-ldc93s1.sh 
+ export ds_importer=ldc93s1
+ export ds_train_batch_size=4
+ export ds_dev_batch_size=4
+ export ds_test_batch_size=4
+ export ds_epochs=2000
+ [ ! -f DeepSpeech.ipynb ]
+ jupyter-nbconvert --to script DeepSpeech.ipynb --stdout
+ python -u
[NbConvertApp] Converting notebook DeepSpeech.ipynb to script
WARNING:tensorflow:From util/text.py:147: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From util/text.py:148: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py:1185: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py:1185: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
WARNING:tensorflow:From util/text.py:164: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
WARNING:tensorflow:From util/text.py:130: unpack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.unstack().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:145: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:145: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:145: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From /home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell_impl.py:145: pack (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.stack().
WARNING:tensorflow:From <stdin>:292: concat (from tensorflow.python.ops.array_ops) is deprecated and will be removed after 2016-12-14.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to tf.concat_v2().
Traceback (most recent call last):
  File "<stdin>", line 1208, in <module>
  File "<stdin>", line 1116, in train
  File "<stdin>", line 895, in create_execution_context
  File "<stdin>", line 619, in get_tower_results
  File "<stdin>", line 441, in calculate_accuracy_and_loss
  File "/home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocal/local/lib/python2.7/site-packages/tensorflow/python/ops/ctc_ops.py", line 133, in ctc_loss
    raise TypeError("Expected labels (first argument) to be a SparseTensor")
TypeError: Expected labels (first argument) to be a SparseTensor
```

**Comment by kdavis-mozilla** [comment]
This seems like a bug in TensorFlow not an API change.

The documentation[[1](https://www.tensorflow.org/api_docs/python/nn/connectionist_temporal_classification__ctc_#ctc_loss)] states the **first argument** `inputs` is a normal Tensor. However it also states `labels` the **second argument** is a SparseTensor.

We pass `inputs`as a normal Tensor and `labels` as a SparseTensor. So there should be no problem.

**Comment by lissyx** [comment]
Ah ah, next time, use named arguments I guess :D https://github.com/tensorflow/tensorflow/commit/e72ad6333ee0204b7d2df93df1f7a85ec4b9ab10

**Comment by kdavis-mozilla** [comment]
Yeah, that's an annoying API change for no good reason.

**Comment by kdavis-mozilla** [comment]
I guess we should address this issue by simply using named arguments here.

**Comment by lissyx** [comment]
Got most of the issues figured out, we should just ensure about that tf.variable_scope() thing.

**Comment by lissyx** [comment]
FYI the PR for TensorFlow is at https://github.com/mozilla/tensorflow/pull/7 and it contains not only fixes, but also updates warpctc python code to remove deprecated use of tf.concat(), changes PIP package naming (hopefully would avoid new upstream to install over warpctc build). With that build I could run LDC93S1 sample with both CTC and WarpCTC, successfully.

**Comment by kentsommer** [comment]
Using #324 as well as [mozilla/tensorflow#7](https://github.com/mozilla/tensorflow/pull/7), I am able to run on LDC93S1 (tested only CTC, have not tested WarpCTC yet).

**Comment by lissyx** [comment]
On top of the changes for 0.12, we need to change back tf.concat_v2() to tf.concat()

**Comment by lissyx** [comment]
https://github.com/mozilla/DeepSpeech/pull/387

**Comment by lissyx** [comment]
Overfitting LDC93S1 without any problem.

**Comment by lissyx** [comment]
New PR: https://github.com/mozilla/DeepSpeech/pull/389

**Comment by lissyx** [comment]
This PR https://github.com/mozilla/tensorflow/pull/11 should be good enough now.

**Comment by lissyx** [comment]
PR mozilla/tensorflow#11 merged in https://github.com/mozilla/tensorflow/commit/616a8ea8626e318e98daa794197ec85a0bb8794a

**Comment by lissyx** [comment]
Automation has been switched to TF 1.0.0, relying on upstream official package (because of segfault when using ours. Debugging this is halted until further notice)
