### ISSUE TITLE
deepspeech.Model() fails: AttributeError: 'Model' object has no attribute '_impl'

### ISSUE THREAD

**Issue by Christian-Nja** [mozilla/DeepSpeech#3006]
- **Code from a wiki**
- **OS Platform and Distribution: Debian 10**
- **Python version 3.7.3**:

I'm trying to run speech to text from a test.wav file with deepspeech python API but it fails at model 
loading.

What i did:

1) installing python deepspeech in venv

`$ pip3 install deepspeech==0.7.1`

2) write a script to transcript an audio:

```
import deepspeech
import wave
import numpy as np

model_file = 'output_graph.pbmm'
beam_width = 500
model = deepspeech.Model(model_file, beam_width)

lm_file = 'lm.binary'
trie_file = 'trie'
lm_alpha = 0.75
lm_beta = 1.85
model.enableDecoderWithLM(lm_file, trie_file, lm_alpha, lm_beta)


audio_file = 'test.wav'
w = wave.open(audio_file, 'r')
rate = w.getframerate()
frames = w.getnframes()
buffer = w.readframes(frames)

print('File audio rate: %d\n', rate)
print('Model audio rate: %d\n', model.sampleRate())

data16 = np.frombuffer(buffer, dtype=np.int16)

text = model.stt(data16)
print(text)
```

It fails at deepspeech.Model *traceback*:

```
Exception ignored in: <function Model.__del__ at 0x7fa2d82c7ea0>
Traceback (most recent call last):
  File "/home/linux/tmp/deeps/lib/python3.7/site-packages/deepspeech/__init__.py", line 42, in __del__
    if self._impl:
AttributeError: 'Model' object has no attribute '_impl'
Traceback (most recent call last):
  File "deeps.py", line 7, in <module>
    model = deepspeech.Model(model_file, beam_width)
TypeError: __init__() takes 2 positional arguments but 3 were given

```

The same happens with: `$ pip3 install deepspeech==0.7.0`

**Comment by kdavis-mozilla** [comment]
0.7.0 and 0.7.1 no longer use lm.binary. See for example [client.py](https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/client.py) for usage of the new API.
