### ISSUE TITLE
run-ldc93s1 ValueError: Scorer initialization failed

### ISSUE THREAD

**Issue by lalimili6** [mozilla/DeepSpeech#3023]
- **OS Platform and Distribution**:  Linux Ubuntu 18.04)
- **TensorFlow installed from**: pip
- **TensorFlow version**: v1.15.0-92-g5d80e1e 1.15.2
- **Python version**: 3.6.9
- **GCC/Compiler version**: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04
- **CUDA/cuDNN version**: 10.2.89
- **GPU model and memory**: 1080Ti, 11178MiB, Driver Version: 440.33.01

**Problem**:
I get the error below when I want to test code:

test code:
```./bin/run-ldc93s1.sh```
output:
```+ [ ! -f DeepSpeech.py ]
+ [ ! -f data/ldc93s1/ldc93s1.csv ]
+ [ -d  ]
+ python -c from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))
+ checkpoint_dir=/home/sokhan/.local/share/deepspeech/ldc93s1
+ export CUDA_VISIBLE_DEVICES=0
+ python -u DeepSpeech.py --noshow_progressbar --train_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir /home/sokhan/.local/share/deepspeech/ldc93s1
Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/home/sokhan/Documents/DeepSpeech/training/deepspeech_training/train.py", line 941, in run_script
    absl.app.run(main)
  File "/home/sokhan/Documents/DeepSpeech/env/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/sokhan/Documents/DeepSpeech/env/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/sokhan/Documents/DeepSpeech/training/deepspeech_training/train.py", line 908, in main
    early_training_checks()
  File "/home/sokhan/Documents/DeepSpeech/training/deepspeech_training/train.py", line 893, in early_training_checks
    FLAGS.scorer_path, Config.alphabet)
  File "/home/sokhan/Documents/DeepSpeech/env/lib/python3.6/site-packages/ds_ctcdecoder/__init__.py", line 36, in __init__
    raise ValueError('Scorer initialization failed with error code {}'.format(err))
ValueError: Scorer initialization failed with error code 1
```

how can fix it? 
best regards

**Comment by reuben** [comment]
What's the output of `head data/lm/kenlm.scorer`?

**Comment by lalimili6** [comment]
```
version https://git-lfs.github.com/spec/v1
oid sha256:d0cf926ab9cab54a8a7d70003b931b2d62ebd9105ed392d1ec9c840029867799
size 953363776```

**Comment by lissyx** [comment]
> ```
> version https://git-lfs.github.com/spec/v1
> oid sha256:d0cf926ab9cab54a8a7d70003b931b2d62ebd9105ed392d1ec9c840029867799
> size 953363776```
> ```

Broken git lfs setup then

**Comment by reuben** [comment]
Make sure Git LFS is properly installed before cloning the repository, otherwise you end up with missing files. https://deepspeech.readthedocs.io/en/v0.7.1/TRAINING.html

**Comment by varad-more** [comment]
I'm facing similar issue and on executing *git-lfs pull*, I'm getting this error. 
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/mozilla/DeepSpeech.git/info/lfs'
```

**Comment by lissyx** [comment]
As said in the error, its over quota and we stopped using git-lfs. Browse github releases to get the files.
