### ISSUE TITLE
SoXI failed with exit code 1

### ISSUE THREAD

**Issue by SirZontax** [mozilla/DeepSpeech#3109]
Hello,

I tried to use the `import_cv2.py` for the common data set. When it starts with the last phase (`train.tsv`) always on `49%` it calls this error:

`
ultiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sox-1.4.0b0-py3.6.egg/sox/core.py", line 149, in soxi
    stderr=subprocess.PIPE
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['sox', '--i', '-c', '/home/zontax/Desktop/de/clips/common_voice_de_19411969.mp3']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "import_cv2.py", line 53, in one_sample
    _maybe_convert_wav(mp3_filename, wav_filename)
  File "import_cv2.py", line 163, in _maybe_convert_wav
    transformer.build(mp3_filename, wav_filename)
  File "/usr/local/lib/python3.6/dist-packages/sox-1.4.0b0-py3.6.egg/sox/transform.py", line 594, in build
    input_filepath, input_array, sample_rate_in
  File "/usr/local/lib/python3.6/dist-packages/sox-1.4.0b0-py3.6.egg/sox/transform.py", line 496, in _parse_inputs
    input_format['channels'] = file_info.channels(input_filepath)
  File "/usr/local/lib/python3.6/dist-packages/sox-1.4.0b0-py3.6.egg/sox/file_info.py", line 82, in channels
    output = soxi(input_filepath, 'c')
  File "/usr/local/lib/python3.6/dist-packages/sox-1.4.0b0-py3.6.egg/sox/core.py", line 153, in soxi
    raise SoxiError("SoXI failed with exit code {}".format(cpe.returncode))
sox.core.SoxiError: SoXI failed with exit code 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "import_cv2.py", line 223, in <module>
    main()
  File "import_cv2.py", line 220, in main
    params.space_after_every_character)
  File "import_cv2.py", line 37, in _preprocess_data
    set_samples = _maybe_convert_set(dataset, tsv_dir, audio_dir, filter_obj, space_after_every_character)
  File "import_cv2.py", line 116, in _maybe_convert_set
    for i, processed in enumerate(pool.imap_unordered(one_sample, samples_with_context), start=1):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
sox.core.SoxiError: SoXI failed with exit code 1
`

I'm running this on `Ubuntu 18.04`, `Python 3.6.9` and installed everything through the `setup.py`. The commands `sox` and `soxi`
work both fine (no errors so far). Tensorflow is installed through pip on git_version `v1.15.0-92-g5d80e1e` and version `1.15.2`

I hope someone knows how to fix this issue.

Thanks in advance!

**Comment by lissyx** [comment]
This is not a bug in our code, so please use Discourse for support. Please run sox manually on that file to share a more actionable error.

**Comment by terminator314** [comment]
i try `sudo apt-get install libsox-fmt-mp3` in terminal . it work
