### ISSUE TITLE
Train Deep Speech using GTX1650 Failed to get convolution algorithm. This is probably because cuDNN failed to initialize

### ISSUE THREAD

**Issue by alexivaner** [mozilla/DeepSpeech#3326]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04 GCC downgraded to v7
- **TensorFlow installed from (our builds, or upstream TensorFlow)**:  anaconda
- **TensorFlow version (use command below)**: 1.15
- **Python version**: 3.6.12
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: cuda 10.0/cudnn7.4.2
- **GPU model and memory**: GTX1650/4GB

Hi is it impossible to train this with low-end GPU like GTX1650? Because I always get some error like this:
```
python DeepSpeech.py --train_files ./data/CV/zh-TW/clips/train.csv --dev_files ./data/CV/zh-TW/clips/dev.csv --test_files ./data/CV/zh-TW/clips/test.csv  
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
I Initializing all variables.
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                                                          Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/conv1d}}]]
	 [[concat/concat/_99]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node tower_0/conv1d}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 977, in run_script
    absl.app.run(main)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 949, in main
    train()
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 606, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 571, in run_set
    feed_dict=feed_dict)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/conv1d (defined at /home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[concat/concat/_99]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node tower_0/conv1d (defined at /home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'tower_0/conv1d':
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 977, in run_script
    absl.app.run(main)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 949, in main
    train()
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 484, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 317, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 244, in calculate_mean_edit_distance_and_loss
    logits, _ = create_model(batch_x, batch_seq_len, dropout, reuse=reuse, rnn_impl=rnn_impl)
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 172, in create_model
    batch_x = create_overlapping_windows(batch_x)
  File "/home/ivan/Project/DeepSpeech/training/deepspeech_training/train.py", line 70, in create_overlapping_windows
    batch_x = tf.nn.conv1d(input=batch_x, filters=eye_filter, stride=1, padding='SAME')
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1681, in conv1d
    name=name)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/ivan/anaconda3/envs/DeepSpeech/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

I already tried using GPU_Growth set to true and make sure my CUDA and CUDNN compatible with tensorflow-gpu version by running this mnist example with gpu https://www.tensorflow.org/tutorials/keras/classification, it works really well.

Do we need minimum of GPU memory 8 GB to train DeepSpeech? Thank you,

**Comment by lissyx** [comment]
@alexivaner Please, can you avoid sharing errors as screenshots? It makes them not accessible and painful to read.

**Comment by lissyx** [comment]
> **CUDA/cuDNN version**: cuda 10.0/cudnn7.4.2

TensorFlow documentation specified CUDNN v7.6, not v7.4



> Do we need minimum of GPU memory 8 GB to train DeepSpeech? Thank you,

The more memory, the better, but we don't have hardware to test with 8GB or below so we don't know.

**Comment by lissyx** [comment]
> make sure my CUDA and CUDNN compatible with tensorflow-gpu version by running this mnist example with gpu https://www.tensorflow.org/tutorials/keras/classification, it works really well.

I don't know what you tested, but this error is textbook CUDNN / CUDA incompatible.

**Comment by alexivaner** [comment]
> @alexivaner Please, can you avoid sharing errors as screenshots? It makes them not accessible and painful to read.

Sorry, I already edited my error.

For the cuda and cudnn, I refer to this article:
https://www.tensorflow.org/install/source#linux
![image](https://user-images.githubusercontent.com/57290644/93473726-ee492300-f928-11ea-9996-061048273182.png)

Okay will try to upgrade the cudnn to 7.6

**Comment by lissyx** [comment]
Also, as this is not a bug in our codebase, please use Discourse as advised for reaching support.
