### ISSUE TITLE
Issue in running Transfer Learning v0.9.0

### ISSUE THREAD

**Issue by AASHISHAG** [mozilla/DeepSpeech#3413]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip install -e .
- **TensorFlow version (use command below)**: v1.15.3-68-gdf8c55c 1.15.4 
- **Python version**:  Python 3.6
- **GCC/Compiler version (if compiling from source)**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
- **CUDA/cuDNN version**: CUDA Version 10.0.130

Hello team,

I am trying to do transfer learning from English to German, using v0.9.0 and I am getting below error. Could you please advice me on it?

```
(deepspeech_v0.9.0) agarwal@LTLab.lan@wika:~/deepspeech_v0.9.0$ python DeepSpeech.py --train_files ../german-speech-corpus/voxforge/train.csv --dev_files ../german-speech-corpus/voxforge/dev.csv --test_files ../german-speech-corpus/voxforge/test.csv --alphabet_config_path ../dependencies_v0.9.0/alphabet.txt --scorer ../dependencies_v0.9.0/kenlm.scorer --test_batch_size 36 --train_batch_size 24 --dev_batch_size 36 --learning_rate 0.0001 --dropout_rate 0.25 --drop_source_layers 1 --save_checkpoint_dir checkpoints_english+german --load_checkpoint_dir checkpoints_english
W WARNING: You specified different values for --load_checkpoint_dir and --save_checkpoint_dir, but you are running training and testing in a single invocation. The testing step will respect --load_checkpoint_dir, and thus WILL NOT TEST THE CHECKPOINT CREATED BY THE TRAINING STEP. Train and test in two separate invocations, specifying the correct --load_checkpoint_dir in both cases, or use the same location for loading and saving.
I Loading best validating checkpoint from checkpoints_english/best_dev-1466475
I Loading variable from checkpoint: beta1_power
I Loading variable from checkpoint: beta2_power
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias/Adam
Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 976, in run_script
    absl.app.run(main)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 948, in main
    train()
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 527, in train
    load_or_init_graph_for_training(session)
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/util/checkpoints.py", line 137, in load_or_init_graph_for_training
    _load_or_init_impl(session, methods, allow_drop_layers=True)
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/util/checkpoints.py", line 98, in _load_or_init_impl
    return _load_checkpoint(session, ckpt_path, allow_drop_layers, allow_lr_init=allow_lr_init)
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/util/checkpoints.py", line 71, in _load_checkpoint
    v.load(ckpt.get_tensor(v.op.name), session=session)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias/Adam not found in checkpoint
```

**Comment by DanBmh** [comment]
Not sure what caused the issue, but you might be able to solve it by just reinitializing the missing Adam tensors.

Check out `training/deepspeech_training/util/checkpoints.py` and there the code below ` if FLAGS.load_cudnn:` in `def _load_checkpoint`. Maybe it's enough to add the `--load_cudnn` flag, but I'm not sure it does change some other things too.

**Comment by AASHISHAG** [comment]
@DanBmh : `--load_cudnn`  resolved the issue. Thank you.

@DeepSpeech: Is this the right approach?
