### ISSUE TITLE
Unble to export tflite model v0.9.0

### ISSUE THREAD

**Issue by AASHISHAG** [mozilla/DeepSpeech#3433]
- **Have I written custom code (as opposed to running examples on an unmodified clone of the repository)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (our builds, or upstream TensorFlow)**: pip install -e .
- **TensorFlow version (use command below)**: v1.15.3-68-gdf8c55c 1.15.4 
- **Python version**:  Python 3.6
- **GCC/Compiler version (if compiling from source)**: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
- **CUDA/cuDNN version**: CUDA Version 10.0.130

Hello Team,

I am trying to export a tflite model for v0.9.0, but getting the following error.

I have transfer learned this model from English to German, and able to export normal model, but not tflite.

```
(deepspeech_v0.9.0) agarwal@LTLab.lan@wika:/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0$ python DeepSpeech.py --alphabet_config_path ../dependencies_v0.9.0/alphabet.txt --checkpoint_dir checkpoints_english+german --export_tflite --export_dir v0.9.0
I Exporting the model...
I Loading best validating checkpoint from checkpoints_english+german/best_dev-2803341
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/bias
I Loading variable from checkpoint: cudnn_lstm/rnn/multi_rnn_cell/cell_0/cudnn_compatible_lstm_cell/kernel
I Loading variable from checkpoint: layer_1/bias
I Loading variable from checkpoint: layer_1/weights
I Loading variable from checkpoint: layer_2/bias
I Loading variable from checkpoint: layer_2/weights
I Loading variable from checkpoint: layer_3/bias
I Loading variable from checkpoint: layer_3/weights
I Loading variable from checkpoint: layer_5/bias
I Loading variable from checkpoint: layer_5/weights
I Loading variable from checkpoint: layer_6/bias
I Loading variable from checkpoint: layer_6/weights
Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 976, in run_script
    absl.app.run(main)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 956, in main
    export()
  File "/media/data/LTLab.lan/agarwal/deepspeech_v0.9.0/training/deepspeech_training/train.py", line 841, in export
    tflite_model = converter.convert()
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/tensorflow_core/lite/python/lite.py", line 983, in convert
    **converter_kwargs)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 449, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "/home/LTLab.lan/agarwal/miniconda3/envs/deepspeech_v0.9.0/lib/python3.6/site-packages/tensorflow_core/lite/python/convert.py", line 200, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-11-20 17:32:51.662478: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1296] Check failed: op->start_indices.size() == dim_count : Incorrect number of start indices supplied to StridedSlice op with output "cudnn_lstm/rnn/multi_rnn_cell/strided_slice". Op requires 3 start indices
Aborted (core dumped)
```

**Comment by lissyx** [comment]
> miniconda3

please avoid conda



> 2020-11-20 17:32:51.662478: F tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:1296] Check failed: op->start_indices.size() == dim_count : Incorrect number of start indices supplied to StridedSlice op with output "cudnn_lstm/rnn/multi_rnn_cell/strided_slice". Op requires 3 start indices

not something we repro

**Comment by AASHISHAG** [comment]
@lissyx : Thank you for the pointer. I created a new environment (pip), and the issue is resolved. Closing the ticket.
