### ISSUE TITLE
pip install deepspeech --user fails with traceback

### ISSUE THREAD

**Issue by chrys87** [mozilla/DeepSpeech#3475]
Hello, 

i currently try to install deepseech using pip and get the following traceback:

> 00:58 [chrys@blackbeast Projekte] :) $ pip install deepspeech
Defaulting to user installation because normal site-packages is not writeable
Collecting deepspeech
  Using cached deepspeech-0.9.3-cp39-cp39-manylinux1_x86_64.whl (9.2 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 331, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 236, in _check_skip_installed
    req_to_install.check_if_exists(self.use_user_site)
  File "/usr/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 437, in check_if_exists
    if not self.req.specifier.contains(existing_version, prereleases=True):
  File "/usr/lib/python3.9/site-packages/packaging/specifiers.py", line 790, in contains
    item = parse(item)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
00:58 [chrys@blackbeast Projekte] :( $ 

any idea what i could be done wrong? or is the package broken?

**Comment by lissyx** [comment]
> pip install deepspeech

works well here:
```
$ pip install deepspeech
Collecting deepspeech
  Downloading deepspeech-0.9.3-cp39-cp39-manylinux1_x86_64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 1.3 MB/s 
Requirement already satisfied: numpy>=1.19.4 in /usr/lib/python3/dist-packages (from deepspeech) (1.19.4)
Installing collected packages: deepspeech
Successfully installed deepspeech-0.9.3
```

the stack is weird and it seems more to be relaterd to pip itself, there's nothing deepspeech specific there.

But you don't care to share any of the required details we ask for in the github template, so we can't help you.

**Comment by chrys87** [comment]
You are right,
seems that pypi has some issues with DDoS currently see: https://status.python.org/
the issue was the missing tensorflow dependency:

19:23 [chrys@blackbeast fenrir] master :) $ pip search tensorflow
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/search.py", line 60, in run
    pypi_hits = self.search(query, options)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/search.py", line 80, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1116, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1456, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py", line 45, in request
    return self.parse_response(response.raw)
  File "/usr/lib/python3.9/xmlrpc/client.py", line 1348, in parse_response
    return u.close()
  File "/usr/lib/python3.9/xmlrpc/client.py", line 662, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">

sorry about the missing information, it was late here, maybe i should have been already stop working. so i didnt read the information and deleted it subconscious. Sorry for that.

I use most up to date ArchLinux, with 
python --version
Python 3.9.1

uname -a
Linux hostnamet 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux

but it seems not to be related here anyway, thanks for bringing me on the right trail.

**Comment by chrys87** [comment]
after install tensorflow using the packagemanger, it didnt fail to install anymore.
