### ISSUE TITLE
CXXABI_1.3.8 not found

### ISSUE THREAD

**Issue by xloem** [mozilla/DeepSpeech#3495]
I have a slightly older system.

```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
$ pip3 install deepspeech-gpu
```
...
```
$ deepspeech
Traceback (most recent call last):
  File "/home/user/.local/bin/deepspeech", line 5, in <module>
    from deepspeech.client import main
  File "/home/user/.local/lib/python3.8/site-packages/deepspeech/__init__.py", line 23, in <module>
    from deepspeech.impl import Version as version
  File "/home/user/.local/lib/python3.8/site-packages/deepspeech/impl.py", line 13, in <module>
    from . import _impl
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/user/.local/lib/python3.8/site-packages/deepspeech/lib/libdeepspeech.so)
```

**Comment by lissyx** [comment]
This is not a bug, please use DIscourse for seeking support. You need to rebuild for your system.

**Comment by xloem** [comment]
Sorry, thought this was a bug.  Didn't know CXX ABI version was so standardised.
