### ISSUE TITLE
Train Error

### ISSUE THREAD

**Issue by resatyigen** [mozilla/DeepSpeech#3516]
If you've found a bug, or have a feature request, then please create an issue with the following information:

- **Deep Speech Version : 0.9.3
- **OS Platform : Windows 10
- **TensorFlow version (use command below)**: 1.15.4
- **Python version**: 3.7.0
- **GPU model and memory**: GTX1060

Hello guys, i training model but show error.

C:\Users\muham\Desktop\DeepSpeech-0.9.3>python DeepSpeech.py --train_files C:/Users/muham/Desktop/Train Files/clips/train.csv --dev_files C:/Users/muham/Desktop/Train Files/clips/dev.csv --test_files C:/Users/muham/Desktop/Train Files/clips/test.csv --alphabet_config_path C:/Users/muham/Desktop/alphabet.txt
I Could not find best validating checkpoint.
I Could not find most recent checkpoint.
I Initializing all variables.
I STARTING Optimization
Epoch 0 |   Training | Elapsed Time: 0:00:00 | Steps: 0 | Loss: 0.000000                                                                                                                                                                    Traceback (most recent call last):
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node tower_0/IteratorGetNext}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 572, in run_set
    feed_dict=feed_dict)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[node tower_0/IteratorGetNext (defined at C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'tower_0/IteratorGetNext':
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 982, in run_script
    absl.app.run(main)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 954, in main
    train()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 484, in train
    gradients, loss, non_finite_files = get_tower_results(iterator, optimizer, dropout_rates)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 317, in get_tower_results
    avg_loss, non_finite_files = calculate_mean_edit_distance_and_loss(iterator, dropout_rates, reuse=i > 0)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 236, in calculate_mean_edit_distance_and_loss
    batch_filenames, (batch_x, batch_seq_len), batch_y = iterator.get_next()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 426, in get_next
    name=name)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2517, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 12, in <module>
    ds_train.run_script()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 982, in run_script
    absl.app.run(main)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 954, in main
    train()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 607, in train
    train_loss, _ = run_set('train', epoch, train_init_op)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\train.py", line 575, in run_set
    exception_box.raise_if_set()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\util\helpers.py", line 149, in raise_if_set
    raise exception  # pylint: disable = raising-bad-type
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\util\helpers.py", line 157, in do_iterate
    yield from iterable()
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\util\feeding.py", line 104, in generate_values
    samples = samples_from_sources(sources, buffering=buffering, labeled=True, reverse=reverse)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\util\sample_collections.py", line 622, in samples_from_sources
    return samples_from_source(sample_sources[0], buffering=buffering, labeled=labeled, reverse=reverse)
  File "C:\Users\muham\AppData\Local\Programs\Python\Python37\lib\site-packages\deepspeech_training-0.9.3-py3.7.egg\deepspeech_training\util\sample_collections.py", line 585, in samples_from_source
    raise ValueError('Unknown file type: "{}"'.format(ext))
ValueError: Unknown file type: ""

*************************************************************************************************************************

Help me Please.

**Comment by lissyx** [comment]
Please use Discourse for support. We don't support training on Windows.

**Comment by resatyigen** [comment]
> Please use Discourse for support. We don't support training on Windows.

Ok dude. I install virtual machine ubuntu and try again.
