### ISSUE TITLE
DeepSpeech Executable will not launch on Windows Server Standard 2019, but will launch on Windows 10

### ISSUE THREAD

**Issue by rwessel-nzd** [mozilla/DeepSpeech#3538]
We are an end user of software platform that has incorporate deepspeech into their product.  They say it works in their environment but it doesn't work in ours. 

Here is an excerpt of the Error Message in the Windows Event Viewer. 

Error #1:

Faulting application name: DeepSpeech.WPF.exe, version: 1.0.0.0, time stamp: 0xc2d09138
Faulting module name: libdeepspeech.so, version: 0.0.0.0, time stamp: 0x5ea31511
Exception code: 0xc000001d
Fault offset: 0x00000000000bba42
Faulting process id: 0x7d8
Faulting application start time: 0x01d690a1ae845df9
Faulting application path: C:\Users\Administrator\Documents\Deepspeech\DeepSpeech.WPF.exe
Faulting module path: C:\Users\Administrator\Documents\Deepspeech\libdeepspeech.so
Report Id: 845f6bd5-c4c1-4c9c-938b-098ae099d119
Faulting package full name: 
Faulting package-relative application ID: 
 
 
Error #2:
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program DeepSpeech.WPF because of this error.
 
Program: DeepSpeech.WPF
File: 
 
The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.
 
Additional Data
Error value: 00000000
Disk type: 0
 
 
Error #3:
Application: DeepSpeech.WPF.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at DeepSpeechClient.NativeImp.DS_CreateModel(System.String, IntPtr** ByRef)
   at DeepSpeechClient.DeepSpeech.CreateModel(System.String)
   at DeepSpeechWPF.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at DeepSpeechWPF.App.Main()
 

Any assistance or direction that can be provided for us to help the developer would be appreciated.  I can provide the ZIP File that they provided us but its 181MB. Let me know if you would like it. 

Thank You.

**Comment by rwessel-nzd** [comment]
Note: This is a VMWare Virtual Machine
![image](https://user-images.githubusercontent.com/79605987/109065186-3d099e80-76b9-11eb-87bc-6194afec3eae.png)

**Comment by lissyx** [comment]
Please follow template, and use discourse for support request. No screenshots.

**Comment by lissyx** [comment]
> We are an end user of software platform that has incorporate deepspeech into their product. They say it works in their environment but it doesn't work in ours.

I guess you need to complain to those people ? It's not like we know their code ...

**Comment by lissyx** [comment]
> Any assistance or direction that can be provided for us to help the developer would be appreciated.

The developer should be the one reaching to us, not end users: this is wasting everyone's time, giving us unactionable issues on code we don't own nor package, and lacking most of the useful informations.
