### ISSUE TITLE
There is an error while we invoke stt with chinese audio record

### ISSUE THREAD

**Issue by Oo121oO** [mozilla/DeepSpeech#3645]
Version is 0.9.3, in android system
tfmodel is deepspeech-0.9.3-models-zh-CN.tflite

Here is the stack:

05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0xe5
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]     string: '橎躌山卦帖称䇋辧室巍于录�录音'
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]     from java.lang.String org.deepspeech.libdeepspeech.implJNI.SpeechToText(long, short[], long)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x7487ffa0 self=0x558c2e8450
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   | sysTid=15776 nice=0 cgrp=default sched=0/0 handle=0x7f8150de80
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 12848574055 69485360 748 ) utm=1254 stm=30 core=1 HZ=100
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   | stack=0x7fd11e5000-0x7fd11e7000 stackSize=8MB
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   native: #00 pc 000039f4  /system/lib64/libbacktrace_libc++.so (Backtrace::Unwind(unsigned long, ucontext*)+28)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00000027  ???
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at org.deepspeech.libdeepspeech.implJNI.SpeechToText(Native method)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at org.deepspeech.libdeepspeech.impl.SpeechToText(impl.java:103)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at org.deepspeech.libdeepspeech.DeepSpeechModel.stt(DeepSpeechModel.java:119)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at org.deepspeech.DeepSpeechActivity.doInference(DeepSpeechActivity.java:112)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at org.deepspeech.DeepSpeechActivity.onClick_inference_handler(DeepSpeechActivity.java:176)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:384)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.view.View.performClick(View.java:4781)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.view.View$PerformClick.run(View.java:19907)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.os.Handler.handleCallback(Handler.java:739)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:159)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5671)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
05-13 16:40:56.933 15776-15776/org.deepspeech A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

**Comment by lissyx** [comment]
@Oo121oO The Mandarin model is released as experimental, and the android code you are running is really only meant for running CI, it has not been tested with Mandarin input.

**Comment by whenSunSet** [comment]
@lissyx 
When will the problem be fixed？

**Comment by lissyx** [comment]
> @lissyx
> When will the problem be fixed？

When someone can take a look at it? I'm not working anymore on DeepSpeech for a few weeks now.
