### ISSUE TITLE
There's no way to restore a checkpoint and do just testing

### ISSUE THREAD

**Issue by reuben** [mozilla/DeepSpeech#407]
If you try to set ds_epochs to exactly last_checkpoint+1 and set ds_restore_checkpoint to 1 something in the code that measures how long each epoch takes breaks. So you have to set ds_epochs to last_checkpoint+2 and do an epoch of training.

**Comment by reuben** [comment]
Resuming training from epoch 65
FINISHED Optimization   Overall time: 0:01:48   Training time:
Traceback (most recent call last):
  File "DeepSpeech.py", line 1133, in <module>
    last_train_wer, last_dev_wer, hibernation_path = train()
  File "DeepSpeech.py", line 1120, in train
    "  Training time:", format_duration(global_train_time)
  File "DeepSpeech.py", line 697, in format_duration
    m, s = divmod(duration.seconds, 60)
AttributeError: 'int' object has no attribute 'seconds'

**Comment by reuben** [comment]
It looks like when restoring we re-do the last training epoch unnecessarily, which is the root cause of this. (When restoring model.ckpt-49 we re-run training epoch 49.)

**Comment by reuben** [comment]
Fixed by #478.
