### ISSUE TITLE
Cannot read model error FormatLoadException

### ISSUE THREAD

**Issue by saurabhvyas** [mozilla/DeepSpeech#464]
Trying with fresh install 

```
(moz) saurabh@saurabh-Inspiron-5559:~/DeepSpeech$ ./bin/run-ldc93s1.sh
+ export ds_importer=ldc93s1
+ export ds_train_batch_size=1
+ export ds_dev_batch_size=1
+ export ds_test_batch_size=1
+ export ds_n_hidden=494
+ export ds_epochs=50
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py
Loading the LM will be faster if you build a binary file.
Reading /home/saurabh/DeepSpeech/data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
Traceback (most recent call last):
  File "DeepSpeech.py", line 21, in <module>
    from util.spell import correction
  File "/home/saurabh/DeepSpeech/util/spell.py", line 9, in <module>
    MODEL = kenlm.Model('./data/lm/lm.binary')
  File "kenlm.pyx", line 117, in kenlm.Model.__init__ (python/kenlm.cpp:2242)
IOError: Cannot read model './data/lm/lm.binary' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43)
(moz) saurabh@saurabh-Inspiron-5559:~/DeepSpeech$ 

```

**Comment by kdavis-mozilla** [comment]
You need to install git lfs. See [[1](https://github.com/mozilla/DeepSpeech/issues/456#issuecomment-288501285)]

**Comment by saurabhvyas** [comment]
I have it installed already

**Comment by saurabhvyas** [comment]
Oh I see ill reclone the repo , Thanks

**Comment by saurabhvyas** [comment]
I can confirm , I have installed git-lfs , and I have recloned the repo , and I get the same error

**Comment by kdavis-mozilla** [comment]
That's odd.

For others[[1](https://github.com/mozilla/DeepSpeech/issues/456#issuecomment-288501285)] doing the following:

- rm -fr DeepSpeech
- Installing git lfs[[2](https://git-lfs.github.com/)]
- git clone https://github.com/mozilla/DeepSpeech.git

solved this problem for them

**Comment by lissyx** [comment]
Make sure you did the `git lfs install` step as well. I got tricked myself.

**Comment by saurabhvyas** [comment]
@kdavis-mozilla  @lissyx Thanks , I was installing with package cloud ( the big blue button the git lfs page ) , I tried with ./install.sh method and It worked , Though it stopped at this line and I had to interrupt multiple times 
```
Downloading data/lm/lm.binary (79.99 MB)

```
But after couple of hit and trials and doing the following it worked
```
saurabh@saurabh-Inspiron-5559:~$ cd DeepSpeech
saurabh@saurabh-Inspiron-5559:~/DeepSpeech$ git checkout -f HEAD
Downloading data/lm/lm.binary (79.99 MB)
Checking out files: 100% (130/130), done.
Your branch is up-to-date with 'origin/master'.
```

**Comment by armandeg** [comment]
I did everything possible: But this is how i resolved the issue:
First Remove your Checked out DeepSpeech. - rm -fr DeepSpeech

```
rm -fr DeepSpeech
add-apt-repository -y ppa:git-core/ppa
apt-get update
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh.deb | bash
apt-get -y install git-lfs git
git clone https://github.com/mozilla/DeepSpeech.git
```
