### ISSUE TITLE
error running ./Deepspeech.py

### ISSUE THREAD

**Issue by nomadiccoder** [mozilla/DeepSpeech#480]
python -V
Python 3.5.2 :: Anaconda 4.1.1 (x86_64)
pip -V
pip 9.0.1 from /Users/{home}/anaconda3/lib/python3.5/site-packages (python 3.5)

when I execute ./Deepspeech.py , it fails with syntax error. See below

python -u DeepSpeech.py 
Traceback (most recent call last):
  File "DeepSpeech.py", line 19, in <module>
    from tensorflow.contrib.session_bundle import exporter
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 12, in <module>
    from . import base
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/base.py", line 287, in <module>
    import pandas as pd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 350, in <module>
    from dateutil import parser as _date_parser
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by kdavis-mozilla** [comment]
The [README.md](https://github.com/mozilla/DeepSpeech#training-a-model) indicates how to get started training,
```bash
DeepSpeech$ ./bin/run-ldc93s1.sh
```
One does not start the training as you did.

**Comment by nomadiccoder** [comment]
Thanks Davis,
   I did start with the script as suggested but got the same error . Hence , went back and executed ./Deepspeech.py -help. The script suggested by you has the same error

./bin/run-ldc93s1.sh 
+ export ds_importer=ldc93s1
+ ds_importer=ldc93s1
+ export ds_train_batch_size=1
+ ds_train_batch_size=1
+ export ds_dev_batch_size=1
+ ds_dev_batch_size=1
+ export ds_test_batch_size=1
+ ds_test_batch_size=1
+ export ds_n_hidden=494
+ ds_n_hidden=494
+ export ds_epochs=50
+ ds_epochs=50
+ '[' '!' -f DeepSpeech.py ']'
+ python -u DeepSpeech.py
Traceback (most recent call last):
  File "DeepSpeech.py", line 19, in <module>
    from tensorflow.contrib.session_bundle import exporter
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 12, in <module>
    from . import base
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/base.py", line 287, in <module>
    import pandas as pd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 350, in <module>
    from dateutil import parser as _date_parser
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by kdavis-mozilla** [comment]
@nomadiccoder Are you using the latest code from master? 

Your error log states
```bash
...
Traceback (most recent call last):
File "DeepSpeech.py", line 19, in
from tensorflow.contrib.session_bundle import exporter
...
```
While line 19 of DeepSpeech.py is
```
import time
```

**Comment by nomadiccoder** [comment]
oops sorry, I didn't pull the repo since yesterday. Apologies for the confusion but the error remains same.  Now its on line 26

./DeepSpeech.py 
Traceback (most recent call last):
  File "./DeepSpeech.py", line 26, in <module>
    from tensorflow.contrib.session_bundle import exporter
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 12, in <module>
    from . import base
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/base.py", line 287, in <module>
    import pandas as pd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 350, in <module>
    from dateutil import parser as _date_parser
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by kdavis-mozilla** [comment]
What happens if you train as suggested in the [README.md](https://github.com/mozilla/DeepSpeech#training-a-model)
```bash
DeepSpeech$ ./bin/run-ldc93s1.sh
```
Also what version of Tensorflow do you have installed. We require 1.0

**Comment by nomadiccoder** [comment]
It gives me the same error
./bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ python -u DeepSpeech.py --importer ldc93s1 --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50
Traceback (most recent call last):
  File "DeepSpeech.py", line 26, in <module>
    from tensorflow.contrib.session_bundle import exporter
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 29, in <module>
    from tensorflow.contrib import factorization
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/__init__.py", line 24, in <module>
    from tensorflow.contrib.factorization.python.ops.gmm import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/factorization/python/ops/gmm.py", line 32, in <module>
    from tensorflow.contrib.learn.python.learn import graph_actions
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/__init__.py", line 70, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 310, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 29, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 33, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 51, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/__init__.py", line 7, in <module>
    from .delayed import do, delayed, value
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/delayed.py", line 12, in <module>
    from . import base
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dask/base.py", line 287, in <module>
    import pandas as pd
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/pandas/compat/__init__.py", line 350, in <module>
    from dateutil import parser as _date_parser
  File "/Users/boredmgr/anaconda3/lib/python3.5/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

And the tensorflow version is 1.0.1

**>>> import tensorflow as tf
>>> tf.__version__
'1.0.1'**

**Comment by kdavis-mozilla** [comment]
As far as I can see it's not a problem with our code.

What happens if you simply have only the line
```python
from tensorflow.contrib.session_bundle import exporter
```
in an interactive python session?

**Comment by nomadiccoder** [comment]
nope doesn't work. Please help me debug this

**Comment by kdavis-mozilla** [comment]
I don't know if I'm the person to ask on this. It's a problem with your Tensorflow install.

I think you should maybe check on StackOverflow for Tensorflow problems[[1](http://stackoverflow.com/questions/tagged/tensorflow)] or look for Tensorflow + Anaconda problems[[2](http://stackoverflow.com/questions/tagged/tensorflow+anaconda)].
