### ISSUE TITLE
AttributeError: 'DataSet' object has no attribute '_example_queue'

### ISSUE THREAD

**Issue by baljeet** [mozilla/DeepSpeech#488]
This breaks when you try to run any binary for training. Both librivox and default demo script fails.

Traceback is:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1646, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1609, in main
    train()
  File "DeepSpeech.py", line 1379, in train
    switchable_data_set = SwitchableDataSet(data_sets)
  File "/home/ubuntu/DeepSpeech/util/data_set_helpers.py", line 47, in __init__
    self._queues = [s._example_queue for s in self._sets]
AttributeError: 'DataSet' object has no attribute '_example_queue'

just refer this.
https://github.com/mozilla/DeepSpeech/blob/master/util/importers/librivox.py#L36
there is actually no "_example_queue", "example_queue" is present.

Shall i raise a PR for the same?

**Comment by tilmankamp** [comment]
@baljeet 
This was already raised/fixed: https://github.com/mozilla/DeepSpeech/pull/485
