### ISSUE TITLE
Fail. Cant figure out why

### ISSUE THREAD

**Issue by davidyapdy** [mozilla/DeepSpeech#508]
I tried training the model locally but it throw me an error. I can't figure out the cause. I've also tried on FloydHub and it fail too. 

This is what I get

```
Traceback (most recent call last):
  File "kenlm.pyx", line 114, in kenlm.Model.__init__ (python/kenlm.cpp:2132)
RuntimeError: lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece &, std::vector<uint64_t> &) threw FormatLoadException.
first non-empty line was "version https://git-lfs.github.com/spec/v1" not \data\. Byte: 43

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1645, in <module>
    tf.app.run()
  File "/Users/davidyap/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1608, in main
    train()
  File "DeepSpeech.py", line 1513, in train
    job.wer, job.samples = calculate_report(report_results)
  File "DeepSpeech.py", line 708, in calculate_report
    corrected = correction(decoding)
  File "/Users/davidyap/DeepSpeech/util/spell.py", line 34, in correction
    layer = [(-log_probability(node + [cword]), node + [cword]) for cword in candidate_words(word) for priority, node in layer]
  File "/Users/davidyap/DeepSpeech/util/spell.py", line 34, in <listcomp>
    layer = [(-log_probability(node + [cword]), node + [cword]) for cword in candidate_words(word) for priority, node in layer]
  File "/Users/davidyap/DeepSpeech/util/spell.py", line 28, in log_probability
    return get_model().score(' '.join(sentence), bos = False, eos = False)
  File "/Users/davidyap/DeepSpeech/util/spell.py", line 15, in get_model
    MODEL = kenlm.Model('./data/lm/lm.binary')
  File "kenlm.pyx", line 117, in kenlm.Model.__init__ (python/kenlm.cpp:2242)
```

**Comment by kdavis-mozilla** [comment]
Could you move to the DeepSpeech directory and run the command:
```bash
davidyap$ ls -lh data/lm
```
then paste the output here.

**Comment by davidyapdy** [comment]
```
total 8
-rw-r--r--  1 davidyap  staff   133B Apr  6 21:24 lm.binary
```

**Comment by kdavis-mozilla** [comment]
It looks as if you didn't clone the repo using git lfs. Can you
- Remove the `DeepSpeech` directory
- Install [git lfs](https://git-lfs.github.com/)
- Clone DeepSpeech again
- Try running the code again

**Comment by davidyapdy** [comment]
Got the same output. I'll attempt to solve it and get back as soon as possible.
```
total 8
-rw-r--r--  1 davidyap  staff   133B Apr  7 22:53 lm.binary
```

**Comment by davidyapdy** [comment]
Nice. I manage to solve it. :) Thanks, I will do a simple write up to set this up with FloydHub.

**Comment by finbarrtimbers** [comment]
Hey @davidyapdy, did you ever do the write up? I'm interested in running DS2 on FloydHub!
