### ISSUE TITLE
Issue while running run-swb.sh 

### ISSUE THREAD

**Issue by ApexNDSU** [mozilla/DeepSpeech#519]
Hello,
I am new to Tensorflow and speech recognition. I was trying to run bin/run-swb.sh file and getting this InvalidArgumentError. I was able to successfully run ldc93s1.sh.  I am not able to figure out the root cause. Could anyone please help on this? I am running it on Tensorflow 1.0.1 and python 3.5
And also does #511 fix would help with this issue too?
Thanks in advance. 

+ '[' '!' -f DeepSpeech.py ']'
+ python3 -u DeepSpeech.py --importer LDC97S62 --train_batch_size 48 --dev_batch_size 32 --test_batch_size 32 --epoch 50 --learning_rate 0.0001 --validation_step 10 --display_step 10 --dropout_rate 0.30
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_transcriptions
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2048] rhs shape= [494]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@b5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](b5/Adam_1, save/RestoreV2_12/_13)]]
	 [[Node: save/RestoreV2_10/_66 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_204_save/RestoreV2_10", _device="/job:localhost/replica:0/task:0/cpu:0"](save/RestoreV2_10)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1644, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1607, in main
    train()
  File "DeepSpeech.py", line 1445, in train
    config=session_config) as session:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 315, in MonitoredTrainingSession
    return MonitoredSession(session_creator=session_creator, hooks=all_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 434, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 767, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 772, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 494, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 375, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 256, in prepare_session
    config=config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 188, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2048] rhs shape= [494]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@b5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](b5/Adam_1, save/RestoreV2_12/_13)]]
	 [[Node: save/RestoreV2_10/_66 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_204_save/RestoreV2_10", _device="/job:localhost/replica:0/task:0/cpu:0"](save/RestoreV2_10)]]

Caused by op 'save/Assign_12', defined at:
  File "DeepSpeech.py", line 1644, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1607, in main
    train()
  File "DeepSpeech.py", line 1445, in train
    config=session_config) as session:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 315, in MonitoredTrainingSession
    return MonitoredSession(session_creator=session_creator, hooks=all_hooks)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 434, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 767, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 772, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 494, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 366, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 180, in finalize
    lambda: training_saver.Saver(sharded=True, allow_empty=True,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 232, in get_or_default
    op = default_constructor()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 181, in <lambda>
    write_version=saver_pb2.SaverDef.V2))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1040, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1070, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 671, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 445, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2048] rhs shape= [494]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@b5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](b5/Adam_1, save/RestoreV2_12/_13)]]
	 [[Node: save/RestoreV2_10/_66 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_204_save/RestoreV2_10", _device="/job:localhost/replica:0/task:0/cpu:0"](save/RestoreV2_10)]]

**Comment by reuben** [comment]
This is the same problem as issue #511. You need to do `rm -r ~/.local/share/deepspeech` because LDC93S1 uses a model of a different shape, so restoring the weights fails.
