### ISSUE TITLE
ZeroDivisionError while running run-swb.sh

### ISSUE THREAD

**Issue by deepika537** [mozilla/DeepSpeech#521]
+ '[' '!' -f DeepSpeech.py ']'
+ python3 -u DeepSpeech.py --importer LDC97S62 --train_batch_size 48 --dev_batch_size 32 --test_batch_size 32 --epoch 50 --learning_rate 0.0001 --validation_step 10 --display_step 10 --dropout_rate 0.30
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_convert_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_wav
skipping maybe_split_transcriptions
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 79, in _populate_batch_queue
    for txt_file, wav_file in self._indices():
  File "/home/nyavanan/DeepSpeech/util/importers/LDC97S62.py", line 75, in _indices
    index = self._next_index(index) % len(self._files_list)
ZeroDivisionError: integer division or modulo by zero

**Comment by kdavis-mozilla** [comment]
Dumb question, but do you have the LDC97S62 data set?

**Comment by deepika537** [comment]
No. I do not have LDC97S62 data set. Where can I get the data set?

**Comment by kdavis-mozilla** [comment]
You have to purchase it[[1](https://catalog.ldc.upenn.edu/ldc97s62)]. It's maybe better to use the TED data set as it's free[[2](http://www-lium.univ-lemans.fr/en/content/ted-lium-corpus)].
