### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#544]
I am trying to implement the ds2-v2 branch. Made few necessary changes in the code but  facing one issue "InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'is_training' with dtype bool " which I am not able to debug. Any help will be really appreciated .

**Comment by pdcoded** [comment]
@reuben any help here ?

**Comment by kdavis-mozilla** [comment]
Do you mean you are trying to "run" or do you mean you are trying to "implement" the ds2-v2 branch?

I assume "run". If this is the case, can you post the traceback? It's not posted in your issue.

**Comment by reuben** [comment]
I can't help as I don't know what changes you made to the code. I haven't encountered that error.

**Comment by pdcoded** [comment]
I have done a pull request with minor edits to the code I had made.Pretty noob in version control so spare me. Here is the traceback of the error. Got the same error on both my mac and Ubuntu machine.
Prabhudattas-MacBook-Pro:DeepSpeech pd$ ./bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --checkpoint_dir =ds2-v2
Traceback (most recent call last):
  File "DeepSpeech.py", line 1602, in <module>
    tf.app.run()
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1565, in main
    train()
  File "DeepSpeech.py", line 1405, in train
    step = session.run(global_step, feed_dict=feed_dict)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'is_training' with dtype bool
	 [[Node: is_training = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'is_training', defined at:
  File "DeepSpeech.py", line 1602, in <module>
    tf.app.run()
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1565, in main
    train()
  File "DeepSpeech.py", line 1340, in train
    is_training_ph = tf.placeholder(tf.bool, name="is_training")
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
    name=name)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/pd/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'is_training' with dtype bool
	 [[Node: is_training = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by pdcoded** [comment]
@kdavis-mozilla implementing ds2-v2 branch using ./bin/run-ldc93s1.sh .

**Comment by pdcoded** [comment]
any update on this ? Not able to run the ds2-v2 branch of ldc93s1 code @reuben

**Comment by kdavis-mozilla** [comment]
@pdcoded this is @reuben code and he's off from work today, but he can take a look on Monday.

From a quick look it seems as if the placeholder `is_training` is not properly set. My guess is that one has to set this boolean value in the `feed_dict` passed to the `Session.run` call to either true or false dependent upon if one is training or not.

**Comment by pdcoded** [comment]
yeah seems like that though this part of the code 
is_training = job.set_name == 'train'
does the same thing essentially.

@reuben can you look at the code when you get time.

**Comment by pdcoded** [comment]
any help here @reuben?

**Comment by reuben** [comment]
That part of the code is not where the error is coming from, it's from the previous session.run call that restores the initial training step.

**Comment by reuben** [comment]
Fixed in commit fa64815.
