### ISSUE TITLE
Averaging only on parameter server

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/DeepSpeech#591]
This effectively means to factor out the "tower" code.
Considered an experiment - only merged into master, if there is no performance degradation.

**Comment by kdavis-mozilla** [comment]
Note, the batch size 10 on TED still gives OOM on the server, only now much later after epoch 12
```bash
...
[worker 0] I --------------------------------------------------------------------------------
[worker 0] I WER: 0.500000, loss: 9.299366, mean edit distance: 0.176471
[worker 0] I  - src: "the sun is rising"
[worker 0] I  - res: "the son es rising"
[worker 0] I --------------------------------------------------------------------------------
[worker 0] I Training of Epoch 11 - loss: 80.546075
[worker 0] Exception in thread Thread-27:
[worker 0] Traceback (most recent call last):
...
[worker 0] Caused by op u'concat_8', defined at:
[worker 0]   File "DeepSpeech.py", line 1647, in <module>
[worker 0]     tf.app.run()
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
[worker 0]     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
[worker 0]   File "DeepSpeech.py", line 1632, in main
[worker 0]     train(server)
[worker 0]   File "DeepSpeech.py", line 1391, in train
[worker 0]     avg_tower_gradients = average_gradients(gradients)
[worker 0]   File "DeepSpeech.py", line 633, in average_gradients
[worker 0]     grad = tf.concat(grads, 0)
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1034, in concat
[worker 0]     name=name)
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 519, in _concat_v2
[worker 0]     name=name)
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
[worker 0]     op_def=op_def)
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
[worker 0]     original_op=self._default_original_op, op_def=op_def)
[worker 0]   File "/usr/local/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
[worker 0]     self._traceback = _extract_stack()
[worker 0]
[worker 0] ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8,6144,8192]
[worker 0]       [[Node: concat_8 = ConcatV2[N=8, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:worker/replica:0/task:0/gpu:0"](ExpandDims_64, ExpandDims_65, ExpandDims_66, ExpandDims_67, ExpandDims_68, ExpandDims_69, ExpandDims_70, ExpandDims_71, concat_8/axis)]]
[worker 0]       [[Node: Mean_3_S1419 = _Recv[client_terminated=false, recv_device="/job:ps/replica:0/task:0/cpu:0", send_device="/job:worker/replica:0/task:0/gpu:0", send_device_incarnation=6225271070185582065, tensor_name="edge_16461_Mean_3", tensor_type=DT_FLOAT, _device="/job:ps/replica:0/task:0/cpu:0"]()]]
```
so this issue is a blocker for use of the new servers.

**Comment by kdavis-mozilla** [comment]
@tilmankamp I think PR #609 obsoletes this issue

**Comment by tilmankamp** [comment]
@kdavis-mozilla I don't think it obsoletes it - it just de-prioritizes it. Let's keep it for now.

**Comment by kdavis-mozilla** [comment]
Ok

**Comment by kdavis-mozilla** [comment]
With our current hardware this doesn't make sense, we've 8 GPU's on a single PCIe bus.
