### ISSUE TITLE
Can't find created model

### ISSUE THREAD

**Issue by elpimous** [mozilla/DeepSpeech#736]
`hello all.`
**I'm newbie, so, sorry for answer !**

working on a french lm (I used pocketsphinx adaptation for years)

I tested DeepSpeech train model from scratch, with a small try: 
    I don't use git lfs, I create myself directories, wavefiles and transcriptions

**transcription.csv :** 
```
wav_filename,wav_filesize,transcript
/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/adapt1.wav,205724,neo quand tu auras le temps recherche sur internet le temps qu' il fera
/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/adapt2.wav,131080,bonjour neo comment vas tu aujourd' hui
/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/adapt3.wav,158138,neo peux tu me dire la temperature de la maison
/home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/adapt4.wav,135866,je te souhaite une agreable soiree
```

**transcription.sh :** 
```
#!/bin/sh
set -xe
if [ ! -f DeepSpeech.py ]; then
    echo "doit etre demarre a partir du repertoire DeepSpeech."
    exit 1
fi;

python -u DeepSpeech.py \
  --train_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv \
  --dev_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv \
  --test_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv \
  --train_batch_size 3 \
  --dev_batch_size 2 \
  --test_batch_size 1 \
  --n_hidden 494 \
  --epoch 10 \
  --export_dir /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.model \
  --checkpoint_dir "$checkpoint_dir" \
  "$@"
```

**terminal :** 
```
nvidia@tegra-ubuntu:~/deepspeech/DeepSpeech$ sudo ./data/deepspeech_material/transcriptions.sh
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py --train_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv --dev_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv --test_files /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.csv --train_batch_size 3 --dev_batch_size 2 --test_batch_size 1 --n_hidden 494 --epoch 10 --export_dir /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.model --checkpoint_dir 
W Parameter --validation_step needs to be >0 for early stopping to work
I STARTING Optimization
I Training of Epoch 0 - loss: 633.970093
I Training of Epoch 1 - loss: 220.964981
I Training of Epoch 2 - loss: 256.804565
I Training of Epoch 3 - loss: 203.154480
I Training of Epoch 4 - loss: 206.644745
I Training of Epoch 5 - loss: 175.403656
I Training of Epoch 6 - loss: 170.658890
I Training of Epoch 7 - loss: 175.496277
I Training of Epoch 8 - loss: 153.884644
I Training of Epoch 9 - loss: 153.248489
I FINISHED Optimization - training time: 0:00:15
E Cannot read model './data/lm/lm.binary' (util/file.cc:76 in int util::OpenReadOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 00))'. No such file or directory while opening /home/nvidia/deepspeech/DeepSpeech/data/lm/lm.binary)
Traceback (most recent call last):
  File "DeepSpeech.py", line 1729, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1689, in main
    train()
  File "DeepSpeech.py", line 1587, in train
    hook.end(session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 360, in end
    self._save(last_step, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 371, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1358, in save
    raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7f512c7710>
```

when looking on /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/   directory, I can't find transcriptions.model !

(And perhaps could you tell me how to correct 'session'  error,)

Thanks all

**Comment by tilmankamp** [comment]
@elpimous You need git LFS for downloading the required language model.
```
No such file or directory while opening /home/nvidia/deepspeech/DeepSpeech/data/lm/lm.binary
```
Unfortunately the current language model is for English only. For French you'd have to provide an own language model.

**Comment by elpimous** [comment]
@tilmankamp 
Hi,
well, I don't anderstand !
git-lsf is a storage for downoading big internet models... I don't use them, so I don't need it ! correct?

I'm building/creating my own model, with only my wavefiles and their transcriptions
I use my transcription.sh to build a new model (no need to compare to an existing langage model. correct?)

**Comment by tilmankamp** [comment]
@elpimous The [**language model**](https://en.wikipedia.org/wiki/Language_model) `lm.binary` is not the same as the **acoustic** model that you are about to train. It is an additional requirement. @kdavis once created/imported an English one and we provide it for convenience reasons.
For this we need git LFS support.

**Comment by tilmankamp** [comment]
@elpimous As you don't have a French LM at the moment, you could turn this feature off by replacing [this lines](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L715-L716) with:
```
sample_wer = wer(label, decoding)
```
The language model will not get loaded and should not fail anymore.

**Comment by elpimous** [comment]
@tilmankamp 
Thanks friend.
just loaded a small cmusphinx binary fr model, renamed as lm.binary, and pulled in right place.
result in terminal is : 
```
I FINISHED Optimization - training time: 0:00:16
Loading the LM will be faster if you build a binary file.
Reading /home/nvidia/deepspeech/DeepSpeech/data/lm/lm.binary
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
E Cannot read model './data/lm/lm.binary' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "Trie Language Model��)
Traceback (most recent call last):
  File "DeepSpeech.py", line 1729, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1689, in main
    train()
  File "DeepSpeech.py", line 1587, in train
    hook.end(session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 360, in end
    self._save(last_step, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/basic_session_run_hooks.py", line 371, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1358, in save
    raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7f519a8710>
```
It seems it can completely read my lm, but there is an error anyway.

Trying sample-wer.

Like this, i think i'll be able to create a minimalist model, specific to learned sentences (it's what I want, for a robotic conversation)
Thanks

**Comment by elpimous** [comment]
tried with mod in Deepspeech.py : L711 :  sample_wer = wer(label, decoding)
****************************************************************************************************
`E Cannot read model './data/lm/lm.binary' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "Trie Language Model��)`

**Comment by elpimous** [comment]
**so I did some more mods :  # IS IT CORRECT ?**
```
    for label, decoding, distance, loss in items:
        #corrected = correction(decoding)

        #sample_wer = wer(label, corrected)
        sample_wer = wer(label, decoding)

        #sample = Sample(label, corrected, loss, distance, sample_wer)
        sample = Sample(label, decoding, loss, distance, sample_wer)
```

**and no more errors :** 
```
I FINISHED Optimization - training time: 0:00:16
I Test of Epoch 10 - WER: 1.000000, loss: 142.468503952, mean edit distance: 0.856894
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 95.285553, mean edit distance: 0.764706
I  - src: "je te souhaite une agreable soiree"
I  - res: "eeeeeeeeee"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 112.162834, mean edit distance: 0.947368
I  - src: "bonjour neo comment vas tu aujourd hui"
I  - res: "eeeeeeeeee"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 129.862839, mean edit distance: 0.829787
I  - src: "neo peux tu me dire la temperature de la maison"
I  - res: "eeeeeeeeeee"
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 232.562790, mean edit distance: 0.885714
I  - src: "neo quand tu auras le temps recherche sur internet le temps qu il fera"
I  - res: "eeeeeeee"
I --------------------------------------------------------------------------------
I Exporting the model...
I Restored checkpoint at training epoch 11
Converted 14 variables to const ops.
308 ops in the final graph.
I Models exported at /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.model
```
**perhaps you could confirm that my results are good, regarding to my poor material and my 10 epochs ?**

**Comment by tilmankamp** [comment]
@kdavis-mozilla Do you have any input on the model loading question?
@elpimous I forgot some detail in the "language model deactivation" patch - [lines](https://github.com/mozilla/DeepSpeech/blob/master/DeepSpeech.py#L715-L717) have to be:
```
sample_wer = wer(label, decoding)
sample = Sample(label, decoding, loss, distance, sample_wer)
```
If I missed something else: You have to remove all calls to the `util/spell` module.

**Comment by tilmankamp** [comment]
@elpimous It's looking good now.

**Comment by elpimous** [comment]
Thanks a lot for your help.
Perhaps I'll post here a tuto for french users, when my tests will be as expected.
See U
