### ISSUE TITLE
Python binding should depend against numpy, scipy

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#744]
Running `pip install --upgrade deepspeech[...].whl` results in:
```
$ pip install --upgrade https://queue.taskcluster.net/v1/task/EERLLrilSby5GnGjPRb8VA/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
Collecting deepspeech==0.0.1 from https://queue.taskcluster.net/v1/task/EERLLrilSby5GnGjPRb8VA/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
  Downloading https://queue.taskcluster.net/v1/task/EERLLrilSby5GnGjPRb8VA/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl (111kB)
    100% |████████████████████████████████| 112kB 217kB/s 
Installing collected packages: deepspeech
Successfully installed deepspeech-0.0.1
```

And then, with `scipy` already installed,
```
 python native_client/client.py 
Traceback (most recent call last):
  File "native_client/client.py", line 2, in <module>
    import scipy.io.wavfile as wav
  File "/home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocalMaster/local/lib/python2.7/site-packages/scipy/__init__.py", line 61, in <module>
    from numpy import show_config as show_numpy_config
ImportError: No module named numpy
```

And if `scipy` is not installed,
```
$ python native_client/client.py 
Traceback (most recent call last):
  File "native_client/client.py", line 2, in <module>
    import scipy.io.wavfile as wav
ImportError: No module named scipy.io.wavfile
```

**Comment by lissyx** [comment]
With proper dependencies:
```
$ pip install --upgrade https://queue.taskcluster.net/v1/task/f8mu4kU-R3i696xlwjMCQQ/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
Collecting deepspeech==0.0.1 from https://queue.taskcluster.net/v1/task/f8mu4kU-R3i696xlwjMCQQ/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl
  Downloading https://queue.taskcluster.net/v1/task/f8mu4kU-R3i696xlwjMCQQ/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_x86_64.whl (111kB)
    100% |████████████████████████████████| 112kB 204kB/s 
Collecting numpy (from deepspeech==0.0.1)
  Using cached numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy (from deepspeech==0.0.1)
  Using cached scipy-0.19.1-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: numpy, scipy, deepspeech
Successfully installed deepspeech-0.0.1 numpy-1.13.1 scipy-0.19.1
$ python native_client/client.py 
Traceback (most recent call last):
  File "native_client/client.py", line 3, in <module>
    from deepspeech.model import Model
  File "/home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocalMaster/local/lib/python2.7/site-packages/deepspeech/model.py", line 28, in <module>
    _model = swig_import_helper()
  File "/home/alex/codaz/Mozilla/DeepSpeech/tensorflow/tensorflowLocalMaster/local/lib/python2.7/site-packages/deepspeech/model.py", line 20, in swig_import_helper
    import _model
ImportError: libdeepspeech.so: cannot open shared object file: No such file or directory
```
