### ISSUE TITLE
Not enough time for target transition sequence (required: 26, available: 1)

### ISSUE THREAD

**Issue by elpimous** [mozilla/DeepSpeech#746]
Could anyone help me to anderstand this error ?

my material is 242 wavefiles (mono, nearly 2-3seconds each, 16000)

my csv file (sample : 
wav_filename,wav_filesize,transcript
/home/nvidia/Documents/wav/record.1.wav,76218,qui est alfred mon robot
/home/nvidia/Documents/wav/record.2.wav,95198,qui est ce petit robot noir et blanc
/home/nvidia/Documents/wav/record.3.wav,65882,toc toc toc qui est la
/home/nvidia/Documents/wav/record.4.wav,44,ou habites tu en ce moment
/home/nvidia/Documents/wav/record.5.wav,52134,ou est-ce que tu habites
/home/nvidia/Documents/wav/record.6.wav,61888,tu resides ou aujourd' hui
...)

```
+ [ ! -f DeepSpeech.py ]
+ python -u DeepSpeech.py --train_files /home/nvidia/Documents/sentences.csv --dev_files /home/nvidia/Documents/sentences.csv --test_files /home/nvidia/Documents/sentences.csv --train_batch_size 4 --dev_batch_size 2 --test_batch_size 1 --n_hidden 494 --epoch 30 --export_dir /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/transcriptions.model --checkpoint_dir /home/nvidia/deepspeech/DeepSpeech/data/deepspeech_material/checkout/
W Parameter --validation_step needs to be >0 for early stopping to work
E Not enough time for target transition sequence (required: 26, available: 1), skipping data instance in batch: 0
E 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](tower_0/Reshape_7/_527, tower_0/ToInt64/_529, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
E 
E Caused by op u'tower_0/CTCLoss', defined at:
E   File "DeepSpeech.py", line 1735, in <module>
E     tf.app.run()
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
E     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
E   File "DeepSpeech.py", line 1695, in main
E     train()
E   File "DeepSpeech.py", line 1455, in train
E     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
E   File "DeepSpeech.py", line 591, in get_tower_results
E     calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
E   File "DeepSpeech.py", line 478, in calculate_mean_edit_distance_and_loss
E     total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/ctc_ops.py", line 145, in ctc_loss
E     ctc_merge_repeated=ctc_merge_repeated)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_ctc_ops.py", line 164, in _ctc_loss
E     name=name)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
E     op_def=op_def)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
E     original_op=self._default_original_op, op_def=op_def)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
E     self._traceback = _extract_stack()
E 
E InvalidArgumentError (see above for traceback): Not enough time for target transition sequence (required: 26, available: 1), skipping data instance in batch: 0
E 	 [[Node: tower_0/CTCLoss = CTCLoss[ctc_merge_repeated=true, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](tower_0/Reshape_7/_527, tower_0/ToInt64/_529, tower_0/Gather, tower_0/Gather_DequeueMany:1)]]
E 
Traceback (most recent call last):
  File "DeepSpeech.py", line 1735, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1695, in main
    train()
  File "DeepSpeech.py", line 1599, in train
    sys.exit(1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 478, in __exit__
    self._close_internal(exception_type)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 511, in _close_internal
    self._sess.close()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 739, in close
    self._sess.close()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 827, in close
    self._coord.join()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 390, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: Thread-8 Thread-7 Thread-5 Thread-6
```

**Comment by elpimous** [comment]
Hello all.
My fault.... There was a "ç" lost im my sentences.
I think that non ascii will be hard to integrate..(I'll try)
without any special charachers, It works. Thanks for this amazing project.

**Comment by MuruganR96** [comment]
Sir i am also facing this issue. in my training csv file i was removed Non ASCII, special characters and conv  all lowercase but  stil now that same error was shown. what i do, help me. @elpimous sir.


python3 DeepSpeech.py --n_hidden 2048 --initialize_from_frozen_model ../models/output_graph.pb --checkpoint_dir fine_tuning_checkpoints3 --epoch 3 --train_files /home/dell/Documents/train_file1/train1.csv --dev_files /home/dell/Documents/train_file1/dev1.csv --test_files /home/dell/Documents/train_file1/test1.csv --learning_rate 0.0001 --decoder_library_path new_native_client/libctc_decoder_with_kenlm.so --alphabet_config_path data/alphabet.txt --lm_binary_path data/lm/lm.binary  --lm_trie_path data/lm/trie
Preprocessing ['/home/dell/Documents/train_file1/train1.csv']
Preprocessing done
Preprocessing ['/home/dell/Documents/train_file1/dev1.csv']
Preprocessing done
Preprocessing ['/home/dell/Documents/train_file1/test1.csv']
Preprocessing done
W Parameter --validation_step needs to be >0 for early stopping to work
I Initializing from frozen model: ../models/output_graph.pb
I STARTING Optimization
I Training epoch 0...
E Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs                                  
E 	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
E 	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
E 
E Caused by op 'tower_0/CTCLoss', defined at:
E   File "DeepSpeech.py", line 1976, in <module>
E     tf.app.run(main)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
E     _sys.exit(main(argv))
E   File "DeepSpeech.py", line 1932, in main
E     train()
E   File "DeepSpeech.py", line 1525, in train
E     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
E   File "DeepSpeech.py", line 639, in get_tower_results
E     calculate_mean_edit_distance_and_loss(model_feeder, i, dropout_rates, reuse=i>0)
E   File "DeepSpeech.py", line 526, in calculate_mean_edit_distance_and_loss
E     total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/ctc_ops.py", line 158, in ctc_loss
E     ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 286, in ctc_loss
E     name=name)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
E     op_def=op_def)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
E     return func(*args, **kwargs)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
E     op_def=op_def)
E   File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
E     self._traceback = tf_stack.extract_stack()
E 
E InvalidArgumentError (see above for traceback): Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
E 	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
E 	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
  4% (1289 of 30017) |######                                                                                                                                         | Elapsed Time: 0:09:33 ETA:   4:08:28Traceback (most recent call last):
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1731, in train
    _, current_step, batch_loss, batch_report, step_summary = session.run([train_op, global_step, loss, report_params, step_summaries_op], **extra_params)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'tower_0/CTCLoss', defined at:
  File "DeepSpeech.py", line 1976, in <module>
    tf.app.run(main)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1932, in main
    train()
  File "DeepSpeech.py", line 1525, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 639, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, dropout_rates, reuse=i>0)
  File "DeepSpeech.py", line 526, in calculate_mean_edit_distance_and_loss
    total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/ctc_ops.py", line 158, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 286, in ctc_loss
    name=name)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Traceback (most recent call last):
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1731, in train
    _, current_step, batch_loss, batch_report, step_summary = session.run([train_op, global_step, loss, report_params, step_summaries_op], **extra_params)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1148, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1239, in run
    raise six.reraise(*original_exc_info)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1224, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1296, in run
    run_metadata=run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'tower_0/CTCLoss', defined at:
  File "DeepSpeech.py", line 1976, in <module>
    tf.app.run(main)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1932, in main
    train()
  File "DeepSpeech.py", line 1525, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 639, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, dropout_rates, reuse=i>0)
  File "DeepSpeech.py", line 526, in calculate_mean_edit_distance_and_loss
    total_loss = tf.nn.ctc_loss(labels=batch_y, inputs=logits, sequence_length=batch_seq_len)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/ctc_ops.py", line 158, in ctc_loss
    ignore_longer_outputs_than_inputs=ignore_longer_outputs_than_inputs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/ops/gen_ctc_ops.py", line 286, in ctc_loss
    name=name)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Not enough time for target transition sequence (required: 77, available: 76)0You can turn this error into a warning by using the flag ignore_longer_outputs_than_inputs
	 [[{{node tower_0/CTCLoss}} = CTCLoss[ctc_merge_repeated=true, ignore_longer_outputs_than_inputs=false, preprocess_collapse_repeated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](tower_0/raw_logits/_631, tower_0/ToInt64/_633, tower_0/GatherV2, tower_0/GatherV2_DequeueMany:1)]]
	 [[{{node Mean_7/_673}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_742_Mean_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1976, in <module>
    tf.app.run(main)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1932, in main
    train()
  File "DeepSpeech.py", line 1770, in train
    hook.end(session)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 587, in end
    self._save(session, last_step)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 598, in _save
    self._get_saver().save(session, self._save_path, global_step=step)
  File "/home/dell/tmp/DeepSpeech_v0.2.0/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1421, in save
    raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x7faa2c1583c8>
