### ISSUE TITLE
ImportError: /home/sekar/anaconda3/lib/python3.5/site-packages/kenlm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by sekarpdkt** [mozilla/DeepSpeech#794]
hi

I checked the issue #523. And checked that I installed kenlm. Kindly note that in changed requirement.txt to install BeautifulSoup4 instead BeautifulSoup as later was not getting installed.

```

sekar@sekar-J1900NH2:~/machineLearning/DeepSpeech$ /home/sekar/anaconda3/bin/pip3 install -r requirements.txt
Collecting https://github.com/kpu/kenlm/archive/master.zip (from -r requirements.txt (line 15))
  Downloading https://github.com/kpu/kenlm/archive/master.zip (518kB)
    100% |████████████████████████████████| 522kB 97kB/s 
  Requirement already satisfied (use --upgrade to upgrade): kenlm==0.0.0 from https://github.com/kpu/kenlm/archive/master.zip in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: pandas in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: progressbar2 in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: python-utils in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: tensorflow in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: numpy in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: scipy in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: paramiko in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pysftp in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: sox in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: python_speech_features in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: BeautifulSoup4 in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: pyxdg in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: bs4 in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: six in /home/sekar/anaconda3/lib/python3.5/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: python-dateutil>=2 in /home/sekar/anaconda3/lib/python3.5/site-packages (from pandas->-r requirements.txt (line 1))
Requirement already satisfied: pytz>=2011k in /home/sekar/anaconda3/lib/python3.5/site-packages (from pandas->-r requirements.txt (line 1))
Requirement already satisfied: bleach==1.5.0 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: werkzeug>=0.11.10 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: backports.weakref==1.0rc1 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: markdown>=2.6.8 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: wheel>=0.26 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: html5lib==0.9999999 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: protobuf>=3.2.0 in /home/sekar/anaconda3/lib/python3.5/site-packages (from tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: pyasn1>=0.1.7 in /home/sekar/anaconda3/lib/python3.5/site-packages (from paramiko->-r requirements.txt (line 7))
Requirement already satisfied: cryptography>=1.1 in /home/sekar/anaconda3/lib/python3.5/site-packages (from paramiko->-r requirements.txt (line 7))
Requirement already satisfied: pynacl>=1.0.1 in /home/sekar/anaconda3/lib/python3.5/site-packages (from paramiko->-r requirements.txt (line 7))
Requirement already satisfied: bcrypt>=3.1.3 in /home/sekar/anaconda3/lib/python3.5/site-packages (from paramiko->-r requirements.txt (line 7))
Requirement already satisfied: setuptools in /home/sekar/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from protobuf>=3.2.0->tensorflow->-r requirements.txt (line 4))
Requirement already satisfied: asn1crypto>=0.21.0 in /home/sekar/anaconda3/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 7))
Requirement already satisfied: cffi>=1.7 in /home/sekar/anaconda3/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 7))
Requirement already satisfied: idna>=2.1 in /home/sekar/anaconda3/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->-r requirements.txt (line 7))
Requirement already satisfied: pycparser in /home/sekar/anaconda3/lib/python3.5/site-packages (from cffi>=1.7->cryptography>=1.1->paramiko->-r requirements.txt (line 7))
sekar@sekar-J1900NH2:~/machineLearning/DeepSpeech$ cat requirements.txt
pandas
progressbar2
python-utils
tensorflow
numpy
scipy
paramiko
pysftp
sox
python_speech_features
BeautifulSoup4
pyxdg
bs4
six
https://github.com/kpu/kenlm/archive/master.zip
sekar@sekar-J1900NH2:~/machineLearning/DeepSpeech$ ./DeepSpeech.py --help
Traceback (most recent call last):
  File "./DeepSpeech.py", line 26, in <module>
    from util.spell import correction
  File "/home/sekar/machineLearning/DeepSpeech/util/spell.py", line 3, in <module>
    import kenlm
ImportError: /home/sekar/anaconda3/lib/python3.5/site-packages/kenlm.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE
sekar@sekar-J1900NH2:~/machineLearning/DeepSpeech$ 

```
Any help?

**Comment by lissyx** [comment]
My money is on mismatch of std::string, cf https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by sekarpdkt** [comment]
anything I can do to get it move forward?

**Comment by lissyx** [comment]
I cannot tell what your anaconda pip does when building KenLM, so I cannot really help.

**Comment by sekarpdkt** [comment]
Ok.. Looks like this one solved my issue. 

```
sekar@sekar-J1900NH2:~/machineLearning/DeepSpeech$ /usr/bin/pip3 install kenlm
sekar@sekar-J1900NH2:~/machineLearning/DeepSpeechPackages$ cd ~/anaconda3/lib
sekar@sekar-J1900NH2:~/anaconda3/lib$ mv -vf libstdc++.so.6 libstdc++.so.6.old
'libstdc++.so.6' -> 'libstdc++.so.6.old'
sekar@sekar-J1900NH2:~/anaconda3/lib$ ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./libstdc++.so.6

```

**Comment by lissyx** [comment]
@sekarpdkt it might be working, but I'm not sure it is the proper way to fix it :)

**Comment by lissyx** [comment]
@sekarpdkt Searching your error on Google yielded that kind of issues: https://github.com/stan-dev/pystan/issues/292

It seems more of a legit fix to me :)

**Comment by sekarpdkt** [comment]
@lissyx Looks like i have to do a fresh installation of conda. I might better start afresh from start as need to install all afresh in a new machine. I might in that case avoid conda etc. Thanks for the hint
