### ISSUE TITLE
OOM error for very small bacth size aswell

### ISSUE THREAD

**Issue by sruteesh** [mozilla/DeepSpeech#831]
Hello,
I'm training my own data of Indian English audio ( each file roughly between 200-300 KB) . I am training on K80 GPU with 12GB RAM using the `run-librivox.py.` I tried training with batch sizes of 60,20,10,5,4. I have got OOM for all of them.
for 60,20,10 I agree I was being too ambitious. For 5,4 I was able to complete 1 epoch but am getting OOM errors after that. 
My question:
Why did it fail when it was able to complete 1 epoch succesfully?
```
E OOM when allocating tensor with shape[5745,4,2048]
E 	 [[Node: tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@tower_0/bidirectional_rnn/bw/bw/TensorArray"], dtype=DT_FLOAT, element_shape=[?,2048], _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/bidirectional_rnn/bw/bw/TensorArray, tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/range, tower_0/bidirectional_rnn/bw/bw/while/Exit_1)]]
E 	 [[Node: Adam/update/_954 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1511_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 
E Caused by op u'tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3', defined at:
E   File "DeepSpeech.py", line 1737, in <module>
E     tf.app.run()
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
E     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
E   File "DeepSpeech.py", line 1697, in main
E     train()
E   File "DeepSpeech.py", line 1456, in train
E     results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
E   File "DeepSpeech.py", line 595, in get_tower_results
E     calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
E   File "DeepSpeech.py", line 476, in calculate_mean_edit_distance_and_loss
E     logits = BiRNN(batch_x, tf.to_int64(batch_seq_len), dropout)
E   File "DeepSpeech.py", line 428, in BiRNN
E     sequence_length=seq_length)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 368, in bidirectional_dynamic_rnn
E     time_major=time_major, scope=bw_scope)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 546, in dynamic_rnn
E     dtype=dtype)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 716, in _dynamic_rnn_loop
E     final_outputs = tuple(ta.stack() for ta in output_final_ta)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 716, in <genexpr>
E     final_outputs = tuple(ta.stack() for ta in output_final_ta)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 301, in stack
E     return self.gather(math_ops.range(0, self.size()), name=name)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/tensor_array_ops.py", line 328, in gather
E     element_shape=element_shape)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 2226, in _tensor_array_gather_v3
E     element_shape=element_shape, name=name)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
E     op_def=op_def)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
E     original_op=self._default_original_op, op_def=op_def)
E   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
E     self._traceback = _extract_stack()
E 
E ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[5745,4,2048]
E 	 [[Node: tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@tower_0/bidirectional_rnn/bw/bw/TensorArray"], dtype=DT_FLOAT, element_shape=[?,2048], _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/bidirectional_rnn/bw/bw/TensorArray, tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/range, tower_0/bidirectional_rnn/bw/bw/while/Exit_1)]]
E 	 [[Node: Adam/update/_954 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1511_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
E 
Traceback (most recent call last):
  File "DeepSpeech.py", line 1566, in train
    _, current_step, batch_loss, batch_report = session.run([train_op, global_step, loss, report_params], **extra_params)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 462, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 891, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 744, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
ResourceExhaustedError: OOM when allocating tensor with shape[5745,4,2048]
	 [[Node: tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/TensorArrayGatherV3 = TensorArrayGatherV3[_class=["loc:@tower_0/bidirectional_rnn/bw/bw/TensorArray"], dtype=DT_FLOAT, element_shape=[?,2048], _device="/job:localhost/replica:0/task:0/gpu:0"](tower_0/bidirectional_rnn/bw/bw/TensorArray, tower_0/bidirectional_rnn/bw/bw/TensorArrayStack/range, tower_0/bidirectional_rnn/bw/bw/while/Exit_1)]]
	 [[Node: Adam/update/_954 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1511_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by kdavis-mozilla** [comment]
My guess, though you'd have to confirm, is that the fact that
```
epoch_size % batch_size != 0
```
conspire with curriculum learning and feeding the GPU's with what amounts to a circular queue.

To wit, the last batch of the first epoch contains many large elements, but also some small elements, due to the circular queue. The next time around this shifts a bit more, and a bit more, and...until you run in to the case where there's a batch, say, with enough large elements to causes an OOM.

One way around this is to reverse the ordering in [feeding.py#L95](https://github.com/mozilla/DeepSpeech/blob/master/util/feeding.py#L95), then set the batch size to say 3, as you know 4 fails, and start a run. If 3 is too big, it will fail right away and you can set the batch size to 2 and tray again... However, if it's fine, then you've just handled the worst case scenario as all the largest elements are in the first batch.

Once you've found the maximal batch size, then you can revert the change in [feeding.py#L95](https://github.com/mozilla/DeepSpeech/blob/master/util/feeding.py#L95) to go back to using curriculum learning.

**Comment by sruteesh** [comment]
@kdavis-mozilla 
Thanks for the input
Yeah going through some of the earlier issues I tried changing the sort order in `feeding.py` and debug.
But the reason I think it failed even for very small batch_size was I was trying to reload the model trained until that step and continued training.
Once I cleared the prvs checkpoints and started a fresh run it worked with batch_size of 10.
