### ISSUE TITLE
Training with run-ldc93s1.sh gives unicode error in Python 3

### ISSUE THREAD

**Issue by nmstoker** [mozilla/DeepSpeech#849]
## Problem description

I have gone through the installation, but when I try to run the example training with `./bin/run-ldc93s1.sh` I get an error message relating to unicode:

```
Traceback (most recent call last):                                                                                                                                                                   
  File "DeepSpeech.py", line 1554, in train                                                                                                                                                          
    COORD.start_coordination(model_feeder, step)                                                                                                                                                     
  File "DeepSpeech.py", line 1183, in start_coordination                                                                                                                                             
    log_info('STARTING Optimization')                                                                                                                                                                
  File "DeepSpeech.py", line 327, in log_info                                                                                                                                                        
    prefix_print('I ', unicode(message))                                                                                                                                                             
NameError: name 'unicode' is not defined                                                                                                                                                             

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1766, in <module>
    tf.app.run()
  File "/home/neil/Projects/DeepSpeechFiles/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1726, in main
    train()
  File "DeepSpeech.py", line 1620, in train
    log_error(e)
  File "DeepSpeech.py", line 335, in log_error
    prefix_print('E ', unicode(message))
NameError: name 'unicode' is not defined
```
## My setup
* OS: Arch Linux
* Python version: 3.6
* Using a virtual environment
* Tensorflow version: 1.3.0

## My initial thoughts
I'm thinking it could be something stupid I've done with the setup or it might really be a problem running this on Python 3 (but clearly others are doing so fine, as I see lots of 3.5 and 3.6 details in the issues)

I installed it on 22-Sep-2017, but I did notice that there was a commit (#806) which seems to have replaced various `str` references with `unicode` ones, purportedly to make it Python 2 compatible and i wondered if this might have broken it in Python 3 (and perhaps the Python 3 users successfully running it all installed an earlier version???)

**Has anyone else run into this? And any suggestions or extra info I should supply to help diagnose this?**

For now, I'll give it a go with the various `unicode(...)` changes switched back to `str(...)` as they were pre-#806 and see if that gets it working.

**Comment by nmstoker** [comment]
Reverting the changes from #806 does the trick for me.

Is there something that's _meant_ to make it work in 3 that might not be working for me that I should double-check?

**Comment by reuben** [comment]
No, the changes from #806 shouldn't have added those unicode calls, just the unicode_literals import should be enough. That was my error. I'll create a PR for it.

**Comment by nmstoker** [comment]
Thanks for that @reuben

**Comment by reuben** [comment]
Ran into a bunch of bazel issues trying to test this today so I'll only be able to finish it tomorrow, but I'll do it first thing.
