### ISSUE TITLE
Pyenv may fail on OSX due to moving path

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#852]

**Comment by lissyx** [comment]
```

ERROR: /Users/build-user/TaskCluster/LightTasks/2/tasks/task_1506326142/.bazel_cache/output/external/llvm/BUILD:186:1: Executing genrule @llvm//:abi_breaking_gen failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "bazel-out/host/bin/third_party/llvm/expand_cmake_vars", line 176, in <module>
    Main()
  File "bazel-out/host/bin/third_party/llvm/expand_cmake_vars", line 168, in Main
    os.execv(args[0], args)
OSError: [Errno 2] No such file or directory: '/Users/build-user/TaskCluster/HeavyTasks/2/tasks/task_1506092223/pyenv//versions/2.7.13/envs/tf-venv/bin/python'
____Elapsed time: 36,716s, Critical Path: 0,13s
```
