### ISSUE TITLE
unable to restore model

### ISSUE THREAD

**Issue by sruteesh** [mozilla/DeepSpeech#859]
Hello,
I have trained a model in `TF 1.0.1` using `run-librivox.sh`. I wish to use the newly updated decoder `(libctc_decoder_with_kenlm.so)` but it was built on `TF 1.3`. I am getting the following errors when restoring the model in `TF 1.3`. 

```
Traceback (most recent call last):
  File "DeepSpeech.py", line 1766, in <module>
    tf.app.run()
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1726, in main
    train()
  File "DeepSpeech.py", line 1546, in train
    config=session_config) as session:
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 365, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 668, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 490, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 842, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 847, in _create_session
    return self._sess_creator.create_session()
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 551, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 425, in create_session
    init_fn=self._scaffold.init_fn)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 274, in prepare_session
    config=config)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 206, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/root/github_folders/deepspeeech_with_lm/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key bidirectional_rnn/bw/basic_lstm_cell/bias/Adam not found in checkpoint
	 [[Node: save_1/RestoreV2_19 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_19/tensor_names, save_1/RestoreV2_19/shape_and_slices)]]
```
Any idea what changes I need to make to be able to restore the model in `TF 1.3`.
I know that TF has backwards compatibility allowing to restore models from previous versions.

**Comment by reuben** [comment]
TensorFlow's backward compatibility is more of a soft promise than a thing you can depend on. They've renamed internal layer variables in the past for example, breaking the models. 

I haven't seen that exact error before, you need to check what the variable names are for the bidirectional layer on master/1.3 and use the name mapping feature to map from the old name (the one in your error message) to the new name. Check out the documentation for loading models for more info: https://www.tensorflow.org/programmers_guide/saved_model

**Comment by sruteesh** [comment]
Thanks I was able to change the names of the variables and was able to successfully retore.
Key `bidirectional_rnn/bw/basic_lstm_cell/bias/Adam` was saved as `bidirectional_rnn/bw/basic_lstm_cell/biases/Adam in TF 1.0.1` and `weights` were named `kernel` in `TF 1.3.0`

**Comment by reuben** [comment]
Thanks for giving us an update. Do you mind sharing the changes you made to the codeso that I can put it on the FAQ on our wiki?

**Comment by sruteesh** [comment]
Sure
Here is a quick hack. Please modify accordingly.
```
import tensorflow as tf


def rename(checkpoint_dir,dry_run=True):
    checkpoint = tf.train.get_checkpoint_state(checkpoint_dir)
    with tf.Session() as sess:
        for var_name, _ in tf.contrib.framework.list_variables(checkpoint_dir):
            # Load the variable
            var = tf.contrib.framework.load_variable(checkpoint_dir, var_name)

            # Set the new name
            new_name = var_name
            if 'biases' in new_name:
                new_name = new_name.replace("biases", "bias")
            if 'weights' in new_name:
                new_name = new_name.replace("weights", "kernel")

            if dry_run:
                print('%s would be renamed to %s.' % (var_name, new_name))
            else:
                print('Renaming %s to %s.' % (var_name, new_name))
                # Rename the variable
                var = tf.Variable(var, name=new_name)

        if not dry_run:
            # Save the variables
            saver = tf.train.Saver()
            sess.run(tf.global_variables_initializer())
            saver.save(sess, checkpoint_dir+'new-model-ckpt')

# Usage
model_dir = "/path/to/older_version_ckpts"
rename(model_dir,dry_run=False)
```
Thanks.
