### ISSUE TITLE
NotFoundError when executing run-librivox.sh

### ISSUE THREAD

**Issue by byuns9334** [mozilla/DeepSpeech#881]
I am trying to use ds2-v2 branch of deepspeech on librivox corpus and when I run librivox.sh, I get the following error: 

Traceback (most recent call last):
  File "DeepSpeech.py", line 1703, in <module>
    tf.app.run()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1663, in main
    train()
  File "DeepSpeech.py", line 1481, in train
    config=session_config) as session:
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 333, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 627, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 456, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 800, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 805, in _create_session
    return self._sess_creator.create_session()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 517, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 393, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 256, in prepare_session
    config=config)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 188, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key rnn/multi_rnn_cell/cell_2/gru_cell/gates/r/scale/Adam not found in checkpoint
	 [[Node: save_1/RestoreV2_45 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_45/tensor_names, save_1/RestoreV2_45/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_45', defined at:
  File "DeepSpeech.py", line 1703, in <module>
    tf.app.run()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1663, in main
    train()
  File "DeepSpeech.py", line 1481, in train
    config=session_config) as session:
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 333, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 627, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 456, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 800, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 805, in _create_session
    return self._sess_creator.create_session()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 517, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 384, in create_session
    self._scaffold.finalize()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 186, in finalize
    lambda: training_saver.Saver(sharded=True, allow_empty=True,
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 238, in get_or_default
    op = default_constructor()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 187, in <lambda>
    write_version=saver_pb2.SaverDef.V2))
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 687, in build
    restore_sequentially, reshape)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 450, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/byuns9334/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key rnn/multi_rnn_cell/cell_2/gru_cell/gates/r/scale/Adam not found in checkpoint
	 [[Node: save_1/RestoreV2_45 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_45/tensor_names, save_1/RestoreV2_45/shape_and_slices)]]

I've tried so hard to solve this problem but I can't. 
How should I manage this?

**Comment by kdavis-mozilla** [comment]
The branch ds2-v2 is a work in progress and should not be expected to work at any particular moment in time.

**Comment by byuns9334** [comment]
@kdavis-mozilla thanks so much! Is there any open code for deepspeech2 project?
