### ISSUE TITLE
bin/run-ldc93s1.sh  

### ISSUE THREAD

**Issue by veritastry** [mozilla/DeepSpeech#888]
bin/run-ldc93s1.sh      --ps_hosts=host0:2233      --worker_hosts=host0:2222      --job_name=worker --task_index=0 --log_traffic True --coord_host host0 --coord_port 2501 --log_level 0 |& tee -a worker0_train.log
+ '[' '!' -f DeepSpeech.py ']'
+ '[' '!' -f data/ldc93s1/ldc93s1.csv ']'
+ '[' -d '' ']'
++ python -c 'from xdg import BaseDirectory as xdg; print(xdg.save_data_path("deepspeech/ldc93s1"))'
+ checkpoint_dir=/home/pandayu/.local/share/deepspeech/ldc93s1
+ python -u DeepSpeech.py --train_files data/ldc93s1/ldc93s1.csv --dev_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50 --checkpoint_dir /home/pandayu/.local/share/deepspeech/ldc93s1 --ps_hosts=host0:2233 --worker_hosts=host0:2222 --job_name=worker --task_index=0 --log_traffic True --coord_host host0 --coord_port 2501 --log_level 0
Traceback (most recent call last):
  File "DeepSpeech.py", line 1765, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1720, in main
    initialize_globals()
  File "DeepSpeech.py", line 170, in initialize_globals
    COORD = TrainingCoordinator()
  File "DeepSpeech.py", line 1113, in __init__
    self._httpd = BaseHTTPServer.HTTPServer((FLAGS.coord_host, FLAGS.coord_port), TrainingCoordinator.TrainingCoordinationHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.gaierror: [Errno -2] Name or service not known

**Comment by lissyx** [comment]
This is a network issue on your side, please check your system, you should be able to access https://catalog.ldc.upenn.edu/
