### ISSUE TITLE
GTX 960M Fails on minimal [train/dev/test]_batch_size=1

### ISSUE THREAD

**Issue by dogrishin** [mozilla/DeepSpeech#914]
Hello,
I am trying to run DeepSpeech.py on my GTX 960M 2GB using spanish corpus from VoxForge 
http://www.repository.voxforge1.org/downloads/es/Trunk/Audio/Main/16kHz_16bit/

and getting into this error:
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8192]

I tried to set different values for these params:
--train_batch_size 1 --dev_batch_size 1 --test_batch_size 1
, but it looks like it does not affect and I always get same shape, even with all [train/dev/test]_batch_size=1

I also tried cleaning checkpoints dir and setting ascending=False in feeding.py but always same result.

BTW, I run ./bin/run-ldc93s1.sh successfully

Please point me to what I am doing wrong,   Thanks!

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 960M    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    N/A /  N/A |    179MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1109      G   /usr/lib/xorg/Xorg                           154MiB |
|    0      1544      G   compiz                                        23MiB |
+-----------------------------------------------------------------------------+

+ python -u DeepSpeech.py --train_files data/voxforge-es/voxforge-train.csv --dev_files data/voxforge-es/voxforge-dev.csv --test_files data/voxforge-es/voxforge-test.csv --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --learning_rate 0.0001 --epoch 1 --display_step 5 --validation_step 1 --dropout_rate 0.30 --default_stddev 0.046875 --checkpoint_dir data/voxforge-es/checkpoint_dir --export_dir data/voxforge-es/export_dir --decoder_library_path /home/dg/ml/svano/native_client_gpu/libctc_decoder_with_kenlm.so
Traceback (most recent call last):
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8192]
	 [[Node: bidirectional_rnn/fw/basic_lstm_cell/bias/Assign = Assign[T=DT_FLOAT, _class=["loc:@bidirectional_rnn/fw/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](bidirectional_rnn/fw/basic_lstm_cell/bias, bidirectional_rnn/fw/basic_lstm_cell/bias/Initializer/Const)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepSpeech.py", line 1765, in <module>
    tf.app.run()
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1725, in main
    train()
  File "DeepSpeech.py", line 1546, in train
    config=session_config) as session:
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 365, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 668, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 490, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 842, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 847, in _create_session
    return self._sess_creator.create_session()
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 551, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 425, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 279, in prepare_session
    sess.run(init_op, feed_dict=init_feed_dict)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8192]
	 [[Node: bidirectional_rnn/fw/basic_lstm_cell/bias/Assign = Assign[T=DT_FLOAT, _class=["loc:@bidirectional_rnn/fw/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](bidirectional_rnn/fw/basic_lstm_cell/bias, bidirectional_rnn/fw/basic_lstm_cell/bias/Initializer/Const)]]

Caused by op 'bidirectional_rnn/fw/basic_lstm_cell/bias/Assign', defined at:
  File "DeepSpeech.py", line 1765, in <module>
    tf.app.run()
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "DeepSpeech.py", line 1725, in main
    train()
  File "DeepSpeech.py", line 1484, in train
    results_tuple, gradients, mean_edit_distance, loss = get_tower_results(model_feeder, optimizer)
  File "DeepSpeech.py", line 625, in get_tower_results
    calculate_mean_edit_distance_and_loss(model_feeder, i, no_dropout if optimizer is None else dropout_rates)
  File "DeepSpeech.py", line 506, in calculate_mean_edit_distance_and_loss
    logits = BiRNN(batch_x, tf.to_int64(batch_seq_len), dropout)
  File "DeepSpeech.py", line 436, in BiRNN
    sequence_length=seq_length)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 405, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 598, in dynamic_rnn
    dtype=dtype)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 761, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 744, in _time_step
    skip_conditionals=True)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 236, in _rnn_step
    new_output, new_state = call_cell()
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn.py", line 732, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 774, in __call__
    output, new_state = self._cell(inputs, state, scope)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/layers/base.py", line 450, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 401, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1053, in _linear
    initializer=bias_initializer)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in _rnn_get_variable
    variable = getter(*args, **kwargs)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 725, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 320, in _init_from_args
    validate_shape=validate_shape).op
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 274, in assign
    validate_shape=validate_shape)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 43, in assign
    use_locking=use_locking, name=name)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[8192]
	 [[Node: bidirectional_rnn/fw/basic_lstm_cell/bias/Assign = Assign[T=DT_FLOAT, _class=["loc:@bidirectional_rnn/fw/basic_lstm_cell/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](bidirectional_rnn/fw/basic_lstm_cell/bias, bidirectional_rnn/fw/basic_lstm_cell/bias/Initializer/Const)]]

ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables_1/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "DeepSpeech.py", line 1765, in <module>\n    tf.app.run()', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run\n    _sys.exit(main(_sys.argv[:1] + flags_passthrough))', 'File "DeepSpeech.py", line 1725, in main\n    train()', 'File "DeepSpeech.py", line 1546, in train\n    config=session_config) as session:', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 365, in MonitoredTrainingSession\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 668, in __init__\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 490, in __init__\n    self._sess = _RecoverableSession(self._coordinated_creator)', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 842, in __init__\n    _WrappedSession.__init__(self, self._create_session())', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 847, in _create_session\n    return self._sess_creator.create_session()', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 551, in create_session\n    self.tf_sess = self._session_creator.create_session()', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 416, in create_session\n    self._scaffold.finalize()', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 196, in finalize\n    default_ready_for_local_init_op)', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 258, in get_or_default\n    op = default_constructor()', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 193, in default_ready_for_local_init_op\n    variables.global_variables())', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 175, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 144, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/home/dg/tensorflow/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 101, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================

**Comment by guruCDL** [comment]
@dogrishin - It looks like you do not have enough memory left on your GPU to run the whole test data. Try with smaller data sets.

**Comment by dogrishin** [comment]
@guruCDL Thanks for reply! It looks like I figured that out finally.
The other parameter to play with when one has OOM errors is n_hidden.
By default it's:
# Geometry
tf.app.flags.DEFINE_integer ('n_hidden',         2048,        'layer width to use when initialising layers')
So it failed with default value in my case,but when I changed to n_hidden 494 like in run-tc-ldc93s1.sh, I started getting some results. 
Also another parameters to play with while debugging big dataset are:
  --limit_train 10 \
  --limit_dev 10 \
  --limit_test 10

**Comment by lissyx** [comment]
I'm closing this since it seems @dogrishin found the issue :)
