### ISSUE TITLE
Prebuilt RPi3 ARMv6 Python & NodeJS bindings

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#915]

**Comment by lissyx** [comment]
Building python wheel can be achieved not too hard so far, by exporting proper `AS`, `CC`, `CXX` and `LD` for the cross-build toolchain from `definitions.mk`, and we get a `dist/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl` we can install. On the RPi3 system it requires a `pip install --user --upgrade pip` then a `$HOME/.local/bin/pip install --user deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl`, with `python-scipy` installed on the system.

**Comment by lissyx** [comment]
And then it fails, because `NumPy` bundled in my current Raspbian system is too old 👍:
```
pi@raspberrypi:~ $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH python -c "from deepspeech.model import Model"
RuntimeError: module compiled against API version 0xb but this version of numpy is 0x9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/deepspeech/model.py", line 17, in <module>
    _model = swig_import_helper()
  File "/home/pi/.local/lib/python2.7/site-packages/deepspeech/model.py", line 16, in swig_import_helper
    return importlib.import_module('_model')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: numpy.core.multiarray failed to import
```

**Comment by lissyx** [comment]
Targetting NodeJS packages, it works:
```
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH nodejs client.js ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
she had your dark suit in greasy wash water all year
pi@raspberrypi:~/tmp $ LD_DEBUG=libs LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH nodejs client.js ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 2>&1 |grep -i deepspeech.node
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	 search path=./tls/v7l/neon/vfp:./tls/v7l/neon:./tls/v7l/vfp:./tls/v7l:./tls/neon/vfp:./tls/neon:./tls/vfp:./tls:./v7l/neon/vfp:./v7l/neon:./v7l/vfp:./v7l:./neon/vfp:./neon:./vfp:.:RIGIN/tls/v7l/neon/vfp:RIGIN/tls/v7l/neon:RIGIN/tls/v7l/vfp:RIGIN/tls/v7l:RIGIN/tls/neon/vfp:RIGIN/tls/neon:RIGIN/tls/vfp:RIGIN/tls:RIGIN/v7l/neon/vfp:RIGIN/v7l/neon:RIGIN/v7l/vfp:RIGIN/v7l:RIGIN/neon/vfp:RIGIN/neon:RIGIN/vfp:RIGIN		(RPATH from file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node)
     16503:	calling init: /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node
     16503:	calling fini: /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node [0]
pi@raspberrypi:~/tmp $ file /home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node
/home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, not stripped
```

**Comment by lissyx** [comment]
Using proper `numpy` includes from Raspbian yields a working package:
```
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH nodejs client.js ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
she had your dark suit in greasy wash water all year
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH python client.py ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
she had your dark suit in greasy wash water all year
pi@raspberrypi:~/tmp $ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~/tmp $ file ~/tmp/ds-lib/libdeepspeech.so
/home/pi/tmp/ds-lib/libdeepspeech.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (GNU/Linux), dynamically linked, BuildID[md5/uuid]=90a62471426aa7c8b5ce21f34622ae49, not stripped
pi@raspberrypi:~/tmp $ 
```

**Comment by lissyx** [comment]
And out of TaskCluster:
```
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH python client.py ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
Traceback (most recent call last):
  File "client.py", line 7, in <module>
    from deepspeech.model import Model
ImportError: No module named deepspeech.model
pi@raspberrypi:~/tmp $ PATH=$HOME/.local/bin/:$PATH pip install --user --verbose https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl
Collecting deepspeech==0.0.1 from https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl
  Looking up "https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl" in the cache
  No cache entry available
  Starting new HTTPS connection (1): queue.taskcluster.net
  "GET /v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl HTTP/1.1" 303 29
  Status code 303 not in [200, 203, 300, 301]
  Looking up "https://public-artifacts.taskcluster.net/XNAanHdDSL25ZaZjUaYBTg/0/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl" in the cache
  Current age based on date: 34
  Starting new HTTPS connection (1): public-artifacts.taskcluster.net
  "GET /XNAanHdDSL25ZaZjUaYBTg/0/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl HTTP/1.1" 304 0
  Using cached https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl
  Downloading from URL https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1-cp27-cp27mu-linux_armv7l.whl
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from deepspeech==0.0.1)
Installing collected packages: deepspeech

Successfully installed deepspeech-0.0.1
Cleaning up...
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH python client.py ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
she had your dark suit in greasy wash water all year
```

And:
```
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH nodejs client.js ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
module.js:471
    throw err;
    ^

Error: Cannot find module 'deepspeech'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/tmp/client.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
pi@raspberrypi:~/tmp $ npm install https://queue.taskcluster.net/v1/task/XNAanHdDSL25ZaZjUaYBTg/runs/0/artifacts/public/deepspeech-0.0.1.tgz

> deepspeech@0.0.1 install /home/pi/node_modules/deepspeech
> node-pre-gyp install --fallback-to-build

[deepspeech] Success: "/home/pi/node_modules/deepspeech/lib/binding/v0.0.1/node-v48-linux-arm/deepspeech.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
/home/pi
└─┬ deepspeech@0.0.1 
  └─┬ node-pre-gyp@0.6.38 
    ├─┬ hawk@3.1.3 
    │ ├── boom@2.10.1 
    │ ├── cryptiles@2.0.5 
    │ ├── hoek@2.16.3 
    │ └── sntp@1.0.9 
    ├─┬ mkdirp@0.5.1 
    │ └── minimist@0.0.8 
    ├─┬ nopt@4.0.1 
    │ ├── abbrev@1.1.1 
    │ └─┬ osenv@0.1.4 
    │   ├── os-homedir@1.0.2 
    │   └── os-tmpdir@1.0.2 
    ├─┬ npmlog@4.1.2 
    │ ├─┬ are-we-there-yet@1.1.4 
    │ │ └── delegates@1.0.0 
    │ ├── console-control-strings@1.1.0 
    │ ├─┬ gauge@2.7.4 
    │ │ ├── aproba@1.2.0 
    │ │ ├── has-unicode@2.0.1 
    │ │ ├── object-assign@4.1.1 
    │ │ ├── signal-exit@3.0.2 
    │ │ ├─┬ string-width@1.0.2 
    │ │ │ ├── code-point-at@1.1.0 
    │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
    │ │ │   └── number-is-nan@1.0.1 
    │ │ ├─┬ strip-ansi@3.0.1 
    │ │ │ └── ansi-regex@2.1.1 
    │ │ └── wide-align@1.1.2 
    │ └── set-blocking@2.0.0 
    ├─┬ rc@1.2.2 
    │ ├── deep-extend@0.4.2 
    │ ├── ini@1.3.4 
    │ ├── minimist@1.2.0 
    │ └── strip-json-comments@2.0.1 
    ├─┬ request@2.81.0 
    │ ├── aws-sign2@0.6.0 
    │ ├── aws4@1.6.0 
    │ ├── caseless@0.12.0 
    │ ├─┬ combined-stream@1.0.5 
    │ │ └── delayed-stream@1.0.0 
    │ ├── extend@3.0.1 
    │ ├── forever-agent@0.6.1 
    │ ├─┬ form-data@2.1.4 
    │ │ └── asynckit@0.4.0 
    │ ├─┬ har-validator@4.2.1 
    │ │ ├─┬ ajv@4.11.8 
    │ │ │ ├── co@4.6.0 
    │ │ │ └─┬ json-stable-stringify@1.0.1 
    │ │ │   └── jsonify@0.0.0 
    │ │ └── har-schema@1.0.5 
    │ ├─┬ http-signature@1.1.1 
    │ │ ├── assert-plus@0.2.0 
    │ │ ├─┬ jsprim@1.4.1 
    │ │ │ ├── assert-plus@1.0.0 
    │ │ │ ├── extsprintf@1.3.0 
    │ │ │ ├── json-schema@0.2.3 
    │ │ │ └─┬ verror@1.10.0 
    │ │ │   └── assert-plus@1.0.0 
    │ │ └─┬ sshpk@1.13.1 
    │ │   ├── asn1@0.2.3 
    │ │   ├── assert-plus@1.0.0 
    │ │   ├── bcrypt-pbkdf@1.0.1 
    │ │   ├─┬ dashdash@1.14.1 
    │ │   │ └── assert-plus@1.0.0 
    │ │   ├── ecc-jsbn@0.1.1 
    │ │   ├─┬ getpass@0.1.7 
    │ │   │ └── assert-plus@1.0.0 
    │ │   ├── jsbn@0.1.1 
    │ │   └── tweetnacl@0.14.5 
    │ ├── is-typedarray@1.0.0 
    │ ├── isstream@0.1.2 
    │ ├── json-stringify-safe@5.0.1 
    │ ├─┬ mime-types@2.1.17 
    │ │ └── mime-db@1.30.0 
    │ ├── oauth-sign@0.8.2 
    │ ├── performance-now@0.2.0 
    │ ├── qs@6.4.0 
    │ ├── safe-buffer@5.1.1 
    │ ├── stringstream@0.0.5 
    │ ├─┬ tough-cookie@2.3.3 
    │ │ └── punycode@1.4.1 
    │ ├── tunnel-agent@0.6.0 
    │ └── uuid@3.1.0 
    ├─┬ rimraf@2.6.2 
    │ └─┬ glob@7.1.2 
    │   ├── fs.realpath@1.0.0 
    │   ├── inflight@1.0.6 
    │   ├─┬ minimatch@3.0.4 
    │   │ └─┬ brace-expansion@1.1.8 
    │   │   ├── balanced-match@1.0.0 
    │   │   └── concat-map@0.0.1 
    │   └── path-is-absolute@1.0.1 
    ├── semver@5.4.1 
    ├─┬ tar@2.2.1 
    │ ├── block-stream@0.0.9 
    │ ├─┬ fstream@1.0.11 
    │ │ └── graceful-fs@4.1.11 
    │ └── inherits@2.0.3 
    └─┬ tar-pack@3.4.1 
      ├─┬ debug@2.6.9 
      │ └── ms@2.0.0 
      ├── fstream-ignore@1.0.5 
      ├─┬ once@1.4.0 
      │ └── wrappy@1.0.2 
      ├─┬ readable-stream@2.3.3 
      │ ├── core-util-is@1.0.2 
      │ ├── isarray@1.0.0 
      │ ├── process-nextick-args@1.0.7 
      │ ├── string_decoder@1.0.3 
      │ └── util-deprecate@1.0.2 
      └── uid-number@0.0.6 

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
pi@raspberrypi:~/tmp $ LD_LIBRARY_PATH=$HOME/tmp/ds-lib/:$LD_LIBRARY_PATH nodejs client.js ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
she had your dark suit in greasy wash water all year
```
