### ISSUE TITLE
Broken merge automation

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#922]
```
+ python3 /home/build-user/DeepSpeech/ds/tc-decision.py
cache miss test-nodejs_4x-linux-amd64-opt HVbn4pjhQ0-Dvk6K6FR-cQ
cache miss test-training-linux-amd64-opt G609lqJHRc6nwZzx5yyWNA
cache miss test-python_27-linux-amd64-opt LJKOpItrTdewf7WgP9yV8Q
cache miss test-cpp-linux-amd64-opt S6vYZRzzRZ2hdmpo5Bptvw
cache miss test-python_36-linux-amd64-opt c3R7QLn6TFqDya2SvlvJjQ
cache miss linux-amd64-cpu-opt TeamB89JQ7GWgL05wyaj3g
cache hit test-training-linux-amd64-opt G609lqJHRc6nwZzx5yyWNA
cache miss test-python_34-linux-amd64-opt GCMR9cyHSPK7gM2jC35bqw
cache miss linux-rpi3-cpu-opt FT_WnL5VRrm6owWS-d1Cgw
cache hit test-training-linux-amd64-opt G609lqJHRc6nwZzx5yyWNA
cache miss linux-amd64-ctc-opt C6T9S95ZT9azzmRrk2LehA
cache hit test-training-linux-amd64-opt G609lqJHRc6nwZzx5yyWNA
Traceback (most recent call last):
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 180, in property_dot
    return left[k]
KeyError: 'routes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 170, in <module>
    t = create_task_payload(build, base_context)
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 126, in create_task_payload
    return jsone.render(template, contextes)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/__init__.py", line 19, in render
    rv = renderValue(template, full_context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 279, in renderValue
    return dict(updated())
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 270, in updated
    v = renderValue(v, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 261, in renderValue
    return operators[matches[0]](template, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 115, in ifConstruct
    return renderValue(rv, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 261, in renderValue
    return operators[matches[0]](template, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 59, in eval
    return evaluateExpression(renderValue(template['$eval'], context), context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 23, in evaluateExpression
    return evaluator.parse(expr)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 68, in parse
    return super(ExpressionEvaluator, self).parse(expression)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/prattparser.py", line 91, in parse
    result = pc.parse()
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/prattparser.py", line 188, in parse
    left = parser.infix_rules[kind](parser, left, token, self)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 182, in property_dot
    raise TemplateError('{} not found in {}'.format(k, json.dumps(left)))
jsone.shared.TemplateError: TemplateError at template.routes: routes not found in {"dependencies": [], "git_lfs": ["export PATH=/home/build-user/bin:$PATH && wget https://github.com/git-lfs/git-lfs/releases/download/v2.3.1/git-lfs-linux-amd64-2.3.1.tar.gz -O - | tar -C /tmp -zxf - && PREFIX=/home/build-user/ /tmp/git-lfs-2.3.1/install.sh\n"], "metadata": {"description": "Building DeepSpeech CTC KenLM Decoder for Linux/AMD64, CPU only, optimized version", "name": "DeepSpeech CTC KenLM Decoder Linux AMD64 CPU"}, "system_config": ["true\n"], "args": {"tests_cmdline": ""}, "maxRunTime": 3600, "summarize_graph": "https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/summarize_graph", "system_setup": ["true\n"], "tensorflow": "https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/home.tar.xz", "scripts": {"build": "taskcluster/decoder-build.sh", "package": "taskcluster/decoder-package.sh"}, "template_file": "linux-opt-base.tyml"}
```

**Comment by lissyx** [comment]
First failure in: https://github.com/mozilla/DeepSpeech/commit/9be2fbaf9adb7035694ccd0d5ebfc8811de47a1b
