### ISSUE TITLE
Broken decision task because of invalid task definition

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#925]

**Comment by lissyx** [comment]
```
+ pip3 install --quiet --user --upgrade pip
+ curl -L --silent https://raw.githubusercontent.com/lissyx/taskcluster-github-decision/0ee93e9f36ef1fc77218a96e865daa80d36b87e5/requirements.txt
+ pip3 install --quiet --user --upgrade -r /dev/stdin
+ curl -L --silent https://raw.githubusercontent.com/lissyx/taskcluster-github-decision/0ee93e9f36ef1fc77218a96e865daa80d36b87e5/tc-decision.py
+ python3 /home/build-user/DeepSpeech/ds/tc-decision.py
cache miss test-cpp-linux-amd64-opt KIV0klH_R_GOx2cd-WtNWw
Traceback (most recent call last):
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 170, in <module>
    t = create_task_payload(build, base_context)
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 126, in create_task_payload
    return jsone.render(template, contextes)
```
