### ISSUE TITLE
Broken decision task on merge after AOT

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#940]
```
Traceback (most recent call last):
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 181, in property_dot
    return left[k]
KeyError: 'routes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 170, in <module>
    t = create_task_payload(build, base_context)
  File "/home/build-user/DeepSpeech/ds/tc-decision.py", line 126, in create_task_payload
    return jsone.render(template, contextes)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/__init__.py", line 18, in render
    rv = renderValue(template, full_context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 321, in renderValue
    return dict(updated())
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 312, in updated
    v = renderValue(v, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 299, in renderValue
    return operators[matches[0]](template, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 136, in ifConstruct
    return renderValue(rv, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 299, in renderValue
    return operators[matches[0]](template, context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 75, in eval
    return evaluateExpression(renderValue(template['$eval'], context), context)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/render.py", line 24, in evaluateExpression
    return evaluator.parse(expr)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 68, in parse
    return super(ExpressionEvaluator, self).parse(expression)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/prattparser.py", line 91, in parse
    result = pc.parse()
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/prattparser.py", line 190, in parse
    left = parser.infix_rules[kind](parser, left, token, self)
  File "/home/build-user/.local/lib/python3.4/site-packages/jsone/interpreter.py", line 184, in property_dot
    '{} not found in {}'.format(k, json.dumps(left)))
jsone.shared.TemplateError: TemplateError at template.routes: routes not found in {"git_lfs": "export PATH=/home/build-user/bin:$PATH && wget https://github.com/git-lfs/git-lfs/releases/download/v2.3.1/git-lfs-linux-amd64-2.3.1.tar.gz -O - | tar -C /tmp -zxf - && PREFIX=/home/build-user/ /tmp/git-lfs-2.3.1/install.sh\n", "summarize_graph": "https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/summarize_graph", "template_file": "linux-opt-base.tyml", "metadata": {"description": "Building DeepSpeech for Linux/AMD64, AOT Test model, CPU only, optimized version", "name": "DeepSpeech Linux AMD64 CPU AOT (Test)"}, "system_config": "true\n", "maxRunTime": 3600, "scripts": {"build": "taskcluster/aot-test-model-build.sh", "package": "taskcluster/package.sh"}, "system_setup": "echo \"deb http://deb.nodesource.com/node_6.x trusty main\" > /etc/apt/sources.list.d/nodesource.list && wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && apt-get -qq update && apt-get -qq -y install nodejs python-yaml && apt-get -qq -y install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev && wget http://mirrors.kernel.org/ubuntu/pool/universe/s/swig/swig_3.0.10-1.1_amd64.deb -O /tmp/swig_3.0.10-1.1_amd64.deb && wget http://mirrors.kernel.org/ubuntu/pool/universe/s/swig/swig3.0_3.0.10-1.1_amd64.deb -O /tmp/swig3.0_3.0.10-1.1_amd64.deb && dpkg -i /tmp/swig_3.0.10-1.1_amd64.deb /tmp/swig3.0_3.0.10-1.1_amd64.deb\n", "tensorflow": "https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/home.tar.xz", "args": {"tests_cmdline": ""}, "dependencies": ["test-training-linux-amd64-opt"]}
```

**Comment by lissyx** [comment]
Since it is not the first time I am breaking merges, PR #943 includes dry-run of `tc-decision.py` to avoid that.
