### ISSUE TITLE
run-cluster.sh returning pandas IO error

### ISSUE THREAD

**Issue by dcam0050** [mozilla/DeepSpeech#945]
Hi I'm trying to run ```./bin/run-cluster.sh 1:1:2 --script ./bin/run-ldc93s1.sh``` because I have 2 nvidia cards on a single computer and wanted to distribute the load but I get the following error. 

```[worker 0] Traceback (most recent call last):
[worker 0]   File "DeepSpeech.py", line 1769, in <module>
[worker 0]     tf.app.run()
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
[worker 0]     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
[worker 0]   File "DeepSpeech.py", line 1754, in main
[worker 0]     train(server)
[worker 0]   File "DeepSpeech.py", line 1452, in train
[worker 0]     next_index=lambda i: COORD.get_next_index('train'))
[worker 0]   File "/home/icub/user_files/Deep_Speech/DeepSpeech/util/feeding.py", line 90, in __init__
[worker 0]     file = pandas.read_csv(csv, encoding='utf-8')
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 562, in parser_f
[worker 0]     return _read(filepath_or_buffer, kwds)
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 315, in _read
[worker 0]     parser = TextFileReader(filepath_or_buffer, **kwds)
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 645, in __init__
[worker 0]     self._make_engine(self.engine)
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 799, in _make_engine
[worker 0]     self._engine = CParserWrapper(self.f, **self.options)
[worker 0]   File "/usr/local/src/robot/anaconda2/lib/python2.7/site-packages/pandas/io/parsers.py", line 1213, in __init__
[worker 0]     self._reader = _parser.TextReader(src, **kwds)
[worker 0]   File "pandas/parser.pyx", line 358, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3427)
[worker 0]   File "pandas/parser.pyx", line 628, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6861)
[worker 0] IOError: File  does not exist```

Do you have any insight?

**Comment by dcam0050** [comment]
I've figured out that the issue arises when you send a script to run-cluster.sh but does not occur when I send in the parameters for deepSpeech directly with run-cluster instead of using the script

**Comment by reuben** [comment]
run-cluster.sh is for coordinating training across several machines. For a single machine with several GPUs, you can use the normal run scripts.

**Comment by dcam0050** [comment]
Ok i tried that, however when using run-cluster.sh for training specifying 2 workers with 1 GPU each I see better GPU utilisation across time. Using deepSpeech.py directly however I see the utilisation spike to 100% on both GPUs for 3s followed by 16s at 0%.

**Comment by tilmankamp** [comment]
`run-cluster.sh` got removed through #1988.
