### ISSUE TITLE
Unused data-sets should be optional

### ISSUE THREAD

**Issue by 0shape** [mozilla/DeepSpeech#947]
trying to run test task
```
python -u DeepSpeech.py \
   --notrain
   --train False
   --test True
   --test_files data/ivr/conv/task.csv \
   --test_batch_size 1 \
   --n_hidden 494 \
   --checkpoint_dir "./export" \
   "$@"
```
get exception 
```
 + [ ! -f DeepSpeech.py ]
 + python -u DeepSpeech.py --notrain
Traceback (most recent call last):
   File "DeepSpeech.py", line 1768, in <module>
     tf.app.run()
   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
   File "DeepSpeech.py", line 1728, in main
     train()
   File "DeepSpeech.py", line 1451, in train
     next_index=lambda i: COORD.get_next_index('train'))
   File "/DeepSpeech/util/feeding.py", line 90, in __init__
     file = pandas.read_csv(csv, encoding='utf-8')
   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 705, in parser_f
     return _read(filepath_or_buffer, kwds)
   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 445, in _read
     parser = TextFileReader(filepath_or_buffer, **kwds)
   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 814, in __init__
     self._make_engine(self.engine)
   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1045, in _make_engine
     self._engine = CParserWrapper(self.f, **self.options)
   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1684, in __init__
     self._reader = parsers.TextReader(src, **kwds)
   File "pandas/_libs/parsers.pyx", line 391, in pandas._libs.parsers.TextReader.__cinit__
   File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source
 IOError: File  does not exist
```
looks like looks it cannot find file task.csv but it`s in the place

**Comment by tilmankamp** [comment]
This is failing, as there were no CSV files specified for train and dev. At the moment all three sets are always mandatory - even if not using all of them.

**Comment by crazygirl1992** [comment]
hello,when i process the data,with command : bin/import_cv.py path/to/target/directory, i create a target directory,i put my have downloaded data in it,and i have install the sox  but the result is:
sh: 1: sox: not found
SoX could not be found!

    If you do not have SoX, proceed here:
     - - - http://sox.sourceforge.net/ - - -

    If you do (or think that you should) have SoX, double-check your
    path variables.
    
Found archive "/home/cww/deepspeechdataset/cv_corpus_v1.tar.gz" - not downloading.
Found directory "/home/cww/deepspeechdataset/cv_corpus_v1.tar.gz" - not extracting it from archive.

No CSV file "/home/cww/deepspeechdataset/cv-other-test.csv" - importing "/home/cww/deepspeechdataset/cv_corpus_v1/cv-other-test.csv"...
Importing mp3 files...
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .wav files.
This install of SoX cannot process .mp3 files.
Traceback (most recent call last):
  File "import_cv.py", line 143, in <module>
    _download_and_preprocess_data(sys.argv[1])
This install of SoX cannot process .wav files.
  File "import_cv.py", line 37, in _download_and_preprocess_data
    _maybe_convert_sets(target_dir, ARCHIVE_DIR_NAME)
  File "import_cv.py", line 72, in _maybe_convert_sets
    _maybe_convert_set(extracted_dir, source_csv, path.join(target_dir, os.path.split(source_csv)[-1]))
This install of SoX cannot process .mp3 files.
  File "import_cv.py", line 115, in _maybe_convert_set
This install of SoX cannot process .wav files.
    pool.map(one_sample, samples)
  File "/home/cww/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
This install of SoX cannot process .mp3 files.
    return self.map_async(func, iterable, chunksize).get()
This install of SoX cannot process .mp3 files.
  File "/home/cww/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
sox.coreThis install of SoX cannot process .wav files.
.SoxError: Stdout: 
Stderr: /bin/sh: 1: sox: not found

This install of SoX cannot process .wav   @tilmankamp

**Comment by sukhoi** [comment]
is anyone working on this? or has this been fixed? 
would like to pick this up!
- H

**Comment by reuben** [comment]
Nobody is working on it AFAIK. Feel free to work on it! If you have any questions you can ask here or over on our IRC channel, #machinelearning at irc.mozilla.org: https://wiki.mozilla.org/IRC

**Comment by reuben** [comment]
This was fixed at some point. Now if you don't specify train set, no training will be done. Same idea for dev and test sets.
