### ISSUE TITLE
taskcluster.py downloads invalid .whl files (broken URLS?)

### ISSUE THREAD

**Issue by dogrishin** [mozilla/DeepSpeech#973]
Hi, 

when I run below:

python util/taskcluster.py --target /tmp --source tensorflow --artifact tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl
pip install /tmp/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl

I get following:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/local/lib/python2.7/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

It looks like URLS are invalid.
Even if I run wget https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl

or 
wget https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.gpu/artifacts/public/tensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl

I get following:
--2017-11-18 20:43:05--  https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.gpu/artifacts/public/tensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl
Resolving index.taskcluster.net (index.taskcluster.net)... 23.23.74.217, 54.197.255.25, 174.129.218.85
Connecting to index.taskcluster.net (index.taskcluster.net)|23.23.74.217|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://queue.taskcluster.net/v1/task/eFgJZQe4S_mspbbi8eVF6g/artifacts/public%2Ftensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl [following]
--2017-11-18 20:43:06--  https://queue.taskcluster.net/v1/task/eFgJZQe4S_mspbbi8eVF6g/artifacts/public%2Ftensorflow_gpu_warpctc-1.3.0rc0-cp27-cp27mu-manylinux1_x86_64.whl
Resolving queue.taskcluster.net (queue.taskcluster.net)... 174.129.218.85, 23.23.74.217, 54.197.255.25
Connecting to queue.taskcluster.net (queue.taskcluster.net)|174.129.218.85|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-18 20:43:07 ERROR 404: Not Found.

I cannot open URL as I did before and navigate via Mozilla FireFox, I get following:
{
  "code": "ResourceNotFound",
  "message": "Artifact not found\n----\nmethod:     getLatestArtifact\nerrorCode:  ResourceNotFound\nstatusCode: 404\ntime:       2017-11-18T20:45:10.079Z",
  "requestInfo": {
    "method": "getLatestArtifact",
    "params": {
      "0": "public/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-anylinux1_x86_64.whl",
      "taskId": "F2VACXHDRwed3jVuvHiqOw",
      "name": "public/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-anylinux1_x86_64.whl"
    },
    "payload": {},
    "time": "2017-11-18T20:45:10.079Z"
  }
}

Please provide valid URLS.

Thanks, 
Dima

**Comment by reuben** [comment]
Sorry about that, I broke the documentation in #962 by doing a careless replace-all. The correct artifact name is tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl. I'll fix the docs.

**Comment by billzo** [comment]
The URLs in the documentation appear to be broken again. Running these commands:

```
python util/taskcluster.py --target /tmp --source tensorflow --artifact tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl
pip install /tmp/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl
```

Gives me the same error message as above. On the artifacts list page (https://queue.taskcluster.net/v1/task/AgAS3ClkRVSole-v-fJlvQ/artifacts), this entry:

    {
      "storageType": "s3",
      "name": "public/tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl",
      "expires": "2018-05-30T20:12:35.650Z",
      "contentType": "application/octet-stream"
    },

lead me to try changing the URL again.

When using these two commands:

```
python util/taskcluster.py --target /tmp --source tensorflow --artifact tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl
pip install /tmp/tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl
```

I was able to get it working again.

**Comment by lissyx** [comment]
@billzo Do you mind to point which documentation is not uptodate ? I fixed the name of the artifact from 1.3.0rc0 to 1.4.0 as you can see here: https://github.com/mozilla/DeepSpeech#installing-prerequisites-for-training

**Comment by billzo** [comment]
Ah. I can only assume that I had a cached version of the ReadMe on my browser or happened to start on the project just before you pushed that commit. My apologies.

**Comment by kuanzi** [comment]
The URLs in the documentation appear to be broken again. Running these commands:

python util/taskcluster.py --target /tmp --source tensorflow --artifact tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl
pip install /tmp/tensorflow_warpctc-1.3.0rc0-cp27-cp27mu-linux_x86_64.whl

**Comment by kuanzi** [comment]
The URLs in the documentation appear to be broken again. Running these commands:

python util/taskcluster.py --target /tmp --source tensorflow --artifact tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl

and I get the message 

> `Downloading https://index.taskcluster.net/v1/task/project.deepspeech.tensorflow.pip.master.cpu/artifacts/public/tensorflow_warpctc-1.4.0-cp27-cp27mu-linux_x86_64.whl ...
Traceback (most recent call last):
  File "util/taskcluster.py", line 85, in <module>
    maybe_download_tc(target_dir=args.target, tc_url=get_tc_url(args.arch, args.artifact))
  File "util/taskcluster.py", line 49, in maybe_download_tc
    urllib.request.urlretrieve(tc_url, target_file, reporthook=(report_progress if progress else None))
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 451, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 669, in http_error_303
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
    data)
  File "/usr/lib/python2.7/urllib.py", line 661, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 451, in open_https
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 669, in http_error_303
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
    data)
  File "/usr/lib/python2.7/urllib.py", line 661, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1216, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 111] Connection refused
`

[https://github.com/mozilla/DeepSpeech#installing-prerequisites-for-training]


![image](https://user-images.githubusercontent.com/10894071/34904619-3e2220f0-f884-11e7-8292-c23ac359d84a.png)
