### ISSUE TITLE
 absl.flags._exceptions.IllegalFlagValueError: flag --coord_retries=100: flag value must be a string, found "<type 'int'>"

### ISSUE THREAD

**Issue by spakhomov** [mozilla/DeepSpeech#999]
I am getting this error when running ./DeepSpeech.py script after compiling with TensorFlow 1.4. Everything compiled w/o errors.

pakh0002@gpunode:~/DeepSpeech$ ./DeepSpeech.py --help
/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.2.2 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)
Traceback (most recent call last):
  File "./DeepSpeech.py", line 49, in <module>
    tf.app.flags.DEFINE_string  ('coord_retries',    100,         'number of tries of workers connecting to training coordinator before failing')
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 108, in __init__
    self._set_default(default)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 197, in _set_default
    self.default = self._parse(value)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 170, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --coord_retries=100: flag value must be a string, found "<type 'int'>"

I tried changing the flag type to integer and that error went away but another one showed up:

pakh0002@gpunode:~/DeepSpeech$ ./DeepSpeech.py 
/usr/local/lib/python2.7/dist-packages/pandas/core/computation/__init__.py:18: UserWarning: The installed version of numexpr 2.2.2 is not supported in pandas and will be not be used
The minimum supported version is 2.4.6

  ver=ver, min_ver=_MIN_NUMEXPR_VERSION), UserWarning)
ERROR:root:Trying to access flag --decoder_library_path before flags were parsed.
Traceback (most recent call last):
  File "./DeepSpeech.py", line 463, in <module>
    if not os.path.exists(os.path.abspath(FLAGS.decoder_library_path)):
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 509, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --decoder_library_path before flags were parsed

This makes me think that I am missing something in my python setup. Any suggestions on how to fix this?

**Comment by kdavis-mozilla** [comment]
Did you try updating numexpr to version 2.4.6 or above?

**Comment by spakhomov** [comment]
Upgraded to 2.4.6 but get the same error (now w/o numexpr warning):

pakh0002@gpunode:~/DeepSpeech$ ./DeepSpeech.py
Traceback (most recent call last):
  File "./DeepSpeech.py", line 49, in <module>
    tf.app.flags.DEFINE_string  ('coord_retries',    100,         'number of tries of workers connecting to training coordinator before failing')
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 241, in DEFINE_string
    DEFINE(parser, name, default, help, flag_values, serializer, **args)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_defines.py", line 81, in DEFINE
    DEFINE_flag(_flag.Flag(parser, serializer, name, default, help, **args),
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 108, in __init__
    self._set_default(default)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 197, in _set_default
    self.default = self._parse(value)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flag.py", line 170, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --coord_retries=100: flag value must be a string, found "<type 'int'>"

**Comment by Foaloke** [comment]
I got the same error. Code was fine. I also tried to upgrade numexpr with no luck...

**Comment by crazygirl1992** [comment]
i dont know why this happened????? who can help me?
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found


Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found


Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cww/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cww/DeepSpeech-master/util/feeding.py", line 146, in _populate_batch_queue
    source = audiofile_to_input_vector(wav_file, self._model_feeder.numcep, self._model_feeder.numcontext)
  File "/home/cww/DeepSpeech-master/util/audio.py", line 66, in audiofile_to_input_vector
    fs, audio = wav.read(audio_filename)
  File "/home/cww/anaconda2/lib/python2.7/site-packages/scipy/io/wavfile.py", line 233, in read
    fid = open(filename, 'rb')
TypeError: coercing to Unicode: need string or buffer, numpy.float64 found

**Comment by MikalaiDrabovich** [comment]
The issue is still present, is there any update about it?

**Comment by tilmankamp** [comment]
The training coordinator got removed through #1988.
